### ISSUE TITLE
Excessive Error Logs When Saving UserPreferences

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1004]
Users have not yet complained about the functionality not working, but it seems like the UserPreferences saving process is throwing lots of errors in a client Documentum environment (could be an Alfresco problem too, but can't confirm).

My guess is that it is the first time a user saves the user pref there isn't any object so it errors, but I could be way off.

```
2016-02-09 17:26:59,348 449625407   http-bio-8080-exec-6572 ERROR   RESTConfigService   Error creating JSON object with the request and grabbing name of user preference: A JSONObject text must begin with '{' at character 0
org.json.JSONException: A JSONObject text must begin with '{' at character 0
    at org.json.JSONTokener.syntaxError(JSONTokener.java:410)
    at org.json.JSONObject.<init>(JSONObject.java:179)
    at org.json.JSONObject.<init>(JSONObject.java:402)
    at com.tsgrp.opencontent.core.userpreferences.persistence.RESTUserPreferencesService.updateUserPreferences(RESTUserPreferencesService.java:261)
    at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
    at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:426)
    at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:414)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:790)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)
    at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:571)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by mikeblum** [comment]
Logged here as well with some context: https://github.com/tsgrp/OpenContent/issues/69

**Comment by eschwarzbeck** [comment]
So do we just want this to have a single `logger.error` line?

**Comment by gsteimer** [comment]
I think better would be if we always save a valid json.  Based on the error, it looks like at some point we're trying to save something that's not valid.

**Comment by eschwarzbeck** [comment]
Is this still open?

**Comment by gsteimer** [comment]
We happened to just create some users yesterday on release1 and I don't see this error anywhere.  From talking to @benallenallen I think we can consider this resolved
