### ISSUE TITLE
Wizard Questions with special HTML characters in answers causing PDF generation to fail

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/hpi#1017]
With input like we have below:

![selection_161](https://cloud.githubusercontent.com/assets/3905463/13150604/125762a4-d62c-11e5-8d4a-7fc9e55283a4.png)
![selection_162](https://cloud.githubusercontent.com/assets/3905463/13150605/1258c4be-d62c-11e5-9865-6cef3b03f528.png)

Finishing and submitting a form fails with the following trace:

```
2016-02-18 10:31:56,024    37271313    TP-Processor10    ERROR    RESTService    Error creating pdf rendition of wizard form!
com.tsgrp.opencontent.core.exception.OCRuntimeException: Error creating pdf rendition of wizard form!
    at com.tsgrp.opencontent.wizard.PSIJSONUtil.jsonToPdf(PSIJSONUtil.java:664)
    at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.executeImpl(FinishAndSubmitPSIActionExecutor.java:56)
    at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:183)

...
Caused by: com.itextpdf.tool.xml.exceptions.RuntimeWorkerException: Invalid nested tag <3test</td found, expected closing tag td.
    at com.itextpdf.tool.xml.XMLWorker.endElement(XMLWorker.java:135)
    at com.itextpdf.tool.xml.parser.XMLParser.endElement(XMLParser.java:396)
```

This issue doesn't seem to affect WYSWIG questions - only Textboxes and Tex tAreas. This is most likely because of CKEditor's intervention with WYSWIG questions.

**Comment by gsteimer** [comment]
When fixing this, we should test all characters that can be typed on a standard keyboard are valid input and display correctly in the PDF.

**Comment by mikeblum** [comment]
Trunk also fails if an ampersand (&) is in the answer text of a question. Fixed on client branch.

**Comment by mikeblum** [comment]
r13875 | mblum | 2016-02-18 16:43:44 -0600 (Thu, 18 Feb 2016) | 1 line
Changed paths:
   M /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/PSIJSONUtil.java

WIZARD FORMS with special HTML characters like & - we now escape each question answer before passing it to the freemaker FTL -> iText - closing HPI issue: https://github.com/tsgrp/hpi/issues/1017
