### ISSUE TITLE
Group Based Tasks Broken for Alfresco and HBase

### ISSUE THREAD

**Issue by aviking** [tsgrp/HPI#1020]
When attempting to acquire or reassign a group based task Alfresco and HBase throw and error. The error is caused by OC searching for a user with a group name.

**Comment by aviking** [comment]
Fixed with OC Commit: 13916
Code Review: Ben A.

**Comment by gsteimer** [comment]
Just tried to route a group task on edge2 and acquire is not working properly:

![aw-group-based-task](https://cloud.githubusercontent.com/assets/1377228/13923857/2f0f87e0-ef50-11e5-860d-c7d5ab332a8a.gif)

```
org.alfresco.service.cmr.security.NoSuchPersonException: 02210110 User does not exist and could not be created: GROUP_wizard_contributors
	at org.alfresco.repo.security.person.PersonServiceImpl.getPersonImpl(PersonServiceImpl.java:500)
	at org.alfresco.repo.security.person.PersonServiceImpl.getPerson(PersonServiceImpl.java:473)
	at org.alfresco.repo.security.person.PersonServiceImpl.getPerson(PersonServiceImpl.java:430)
	at sun.reflect.GeneratedMethodAccessor771.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at 
...
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy390.getUser(Unknown Source)
	at com.tsgrp.opencontent.wizard.activiti.workflow.WizardWorkflowHelper.updateSignatureEvents(WizardWorkflowHelper.java:261)
	at com.tsgrp.opencontent.wizard.activiti.workflow.listener.WizardApprovalWorkflowSubprocessOnAssignment.notify(WizardApprovalWorkflowSubprocessOnAssignment.java:202)
```

**Comment by ZachGerth** [comment]
Fixed with OC Revision # 14816.
