### ISSUE TITLE
Cannot finish Simple CR form when Hotdocs module is deployed

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1029]
Finishing a Simple CR form on edge2 fails with the following error:

```
14:57:08,536 ERROR [com.tsgrp.opencontent.rest.RESTService] [ajp-apr-8009-exec-2] Failed to parse questions and answers for: workspace://SpacesStore/02174d33-a397-4edf-9fdc-2a531bdf4d27
com.tsgrp.opencontent.core.exception.OCRuntimeException: Failed to parse questions and answers for: workspace://SpacesStore/02174d33-a397-4edf-9fdc-2a531bdf4d27
	at com.tsgrp.opencontent.wizard.PSIJSONUtil.indexQuestionsAndAnswers(PSIJSONUtil.java:392)
	at com.tsgrp.opencontent.wizardhotdocs.action.executor.WizardHotDocsFinishAndSubmitPSIActionExecutor.doPostSubmitActions(WizardHotDocsFinishAndSubmitPSIActionExecutor.java:89)
	at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.executeImpl(FinishAndSubmitPSIActionExecutor.java:115)
...
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1911)
	at com.tsgrp.opencontent.wizard.PSIJSONUtil.indexQuestionsAndAnswers(PSIJSONUtil.java:356)
```

Here's the code from PSIJSONUtil:355-357

```Java
 for(int r = 0; r < tempQA.length; r++){
	 currentQuestionAnswer += tempQA[r].substring(1, tempQA[r].length()-1) + ", ";
 }
```

@mikeblum @alieblich - it looks like something is failing when the form as a multi-select.  Can one of you guys look into this?  I can't let this to to release next week because of demos scheduled mid-week.

**Comment by mikeblum** [comment]
r13946 | mblum | 2016-02-26 16:12:27 -0600 (Fri, 26 Feb 2016) | 1 line
Changed paths:
   M /webservices/trunk/SourceCode/OpenContent/modules/tsg/3.wizard/src/com/tsgrp/opencontent/wizard/PSIJSONUtil.java

PSIJSONUtil: botched refoactoring of the Wizard uestion types - now have a constant for multitextinput - closing https://github.com/tsgrp/HPI/issues/1029
