### ISSUE TITLE
View Versions fails if user doesn't have VIEW permissions on prior version

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1030]
In the compliance solution, when a 2.0 becomes Effective, the 1.0 is Superseded, and permissions change so that very few users can see the 1.0 version.

If a user with full AW admin access views the Effective version and executes the view versions action, it works fine.  However, if a regular consumer user tries the view versions action, it fails.

In the below example, `TSG-109` version 2.0 is Effective, and 1.0 is Superseded.

**Searching on TSG-109 with admin user**
![image](https://cloud.githubusercontent.com/assets/1377228/13438999/29f4fd7a-dfb1-11e5-92d3-7e4f6c42c75f.png)

**Searching on TSG-109 with consumer user**
![image](https://cloud.githubusercontent.com/assets/1377228/13439021/3e29ca00-dfb1-11e5-99c2-78d40d083580.png)

**Viewing Versions of TSG-109, 2.0 with consumer user**
![image](https://cloud.githubusercontent.com/assets/1377228/13439037/5156aff8-dfb1-11e5-9672-5ea9bc5f00f3.png)

@dgrumieaux @nwoodbine @ZachGerth - I'm guessing this is going to be an issue for your current client

**Comment by gsteimer** [comment]
OC error is:

```
2017-07-17 15:00:58,294	http-apr-8080-exec-1	ERROR	EmbeddedAlfrescoAdvice	Access Denied
org.alfresco.repo.security.permissions.AccessDeniedException: 06170093 Access Denied.  You do not have the appropriate permissions to perform this operation.
	at org.alfresco.repo.security.permissions.impl.ExceptionTranslatorMethodInterceptor.invoke(ExceptionTranslatorMethodInterceptor.java:57) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.alfresco.repo.audit.AuditMethodInterceptor.proceedWithAudit(AuditMethodInterceptor.java:256) ~[alfresco-repository-5.1.2.jar:5.1.2]
...
	at com.tsgrp.opencontent.alfresco.extendedcontent.AlfrescoEmbExtendedContentImpl.getAllVersions(AlfrescoEmbExtendedContentImpl.java:367) ~[bin/:2.6]
...
	at com.tsgrp.opencontent.core.action.executer.ViewVersionsExecuter.executeImpl(ViewVersionsExecuter.java:30) [bin/:2.6]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:198) [bin/:2.6]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:137) [bin/:2.6]
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:471) [bin/:2.6]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:198) [bin/:2.6]
```

**Comment by gsteimer** [comment]
Fixed with OC Rev 16911
