### ISSUE TITLE
If a user uses the back button to get back into an AW form to edit, cancel checkout fails

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1034]
A couple of things with the fix for #1021:

**issue**
After using the back button to get into an AW form, if you try to cancel the checkout (exit without saving), an error is thrown:

```
2016-03-03 13:36:58,752	48296744	TP-Processor8	ERROR	RESTService	required condition condition-lockedbyme   failed, cannot execute action
com.tsgrp.opencontent.core.exception.OCRuntimeException: required condition condition-lockedbyme   failed, cannot execute action
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:179)
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:321)
```

It looks like the code that fixed #1021 simply sends the user to the newest version of the form - it doesn't actually check it out again.

**Enhancement**
While fixing this, can we give the use a "no" option when using the back button?  Our solution to #1021 fixes the issue, but also basically forces the user to edit the form.  We should give the user the option to _not_ edit the form.

![image](https://cloud.githubusercontent.com/assets/1377228/13506908/e889bad8-e145-11e5-8955-83b25af4a61b.png)

FYI - @benallenallen @mikeblum @alieblich

**Comment by mikeblum** [comment]
so if the user selects OK we need to make sure the checkout happens when visiting a */edit/* route and then add a cancel button that hits the /exit route.

**Comment by gsteimer** [comment]
yep - probably hook up the [X] in the top right to do the same thing as the [Cancel] button.  Right now, no matter what you do, it takes the user into editing the current form (without checking it out)
