### ISSUE TITLE
All documents fail when viewing using PDF.js

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1040]
With the initial OC commit for #529, PDF.js now consistently fails with the following error:

```
10:44:03,712 ERROR [com.tsgrp.opencontent.core.content.RESTContent] [ajp-apr-8009-exec-6] Failed to retrieve content.
java.lang.NullPointerException
	at com.tsgrp.opencontent.core.util.OCContentUtil.isModified(OCContentUtil.java:71)
	at com.tsgrp.opencontent.core.content.RESTContent.downloadContent(RESTContent.java:792)
	at com.tsgrp.opencontent.core.content.RESTContent.getContent(RESTContent.java:634)
```

It looks like the ECO is null...

Also - I noticed this code in `RESTContent#downloadContent` on line 792:

```java
if(OCContentUtil.isModified(modifiedSince,eco)){						
							if (logger.isDebugEnabled())
								logger.debug("Returning 304 Not Modified.");
							resp.setStatus(HttpServletResponse.SC_NOT_MODIFIED);
							resp.setHeader(HEADER_ETAG, "\"" + Long.toString(OCContentUtil.getModifiedDate(ticket,eco,id).getTime()) + "\"");
							return;
					}
```

The `OCContentUtil.isModified` returns `true` if the object _is_ modified, so we should go into that block if the method returns false, not true.  We only want to return the 304 Not Modified if the object has NOT been modified.

Note - when testing the `isModified` method, do NOT use Wizard forms or Controlled Docs.  These documents by default are told to never return a 304 (they're "no cache types" by default).

**Comment by gsteimer** [comment]
Fixed with OC Rev 14029.

Note - the modified logic wasn't backwards, but the method was named backwards.  `isModified` is now `hasNotBeenModified` to better reflect how the method works.
