### ISSUE TITLE
Collections list view does not show attributes and fails on refresh

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1069]
When viewing a collection using list view, none of the attributes show up:

![image](https://cloud.githubusercontent.com/assets/1377228/14610752/becf71b4-0554-11e6-8112-7dc8b8a0127f.png)

In the admin, attributes are setup as:

![image](https://cloud.githubusercontent.com/assets/1377228/14610781/dbd9e032-0554-11e6-8149-238b53ac4f73.png)

Also - if you hard refresh a collection while on list view (see #1062), the following error occurs:

```
org.alfresco.service.cmr.repository.MalformedNodeRefException: 03180079 Invalid node ref - does not contain forward slash: undefined
    at org.alfresco.service.cmr.repository.NodeRef.<init>(NodeRef.java:106)
    at com.tsgrp.opencontent.alfresco.extendedcontent.AlfrescoEmbExtendedContentImpl.getAvailableThumbnails(AlfrescoEmbExtendedContentImpl.java:998)
    at sun.reflect.GeneratedMethodAccessor1088.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
```

**Comment by gsteimer** [comment]
Closing this one since List view is no longer a valid search results option
