### ISSUE TITLE
Update Doc properties with folder notes integration off causes error in OC

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1077]
In my stage config, I have the Folder Note integration set to off:

![image](https://cloud.githubusercontent.com/assets/1377228/14748911/fb57ba4e-0881-11e6-9888-edf381522c60.png)

However, when I change document properties, this error gets spammed to the logs:

```
11:55:57,537 ERROR [com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice] [ajp-apr-8009-exec-7] Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.content.IContent| name: addRelation
java.lang.IllegalArgumentException: Association {}hpi_folder_note has not been defined in the data dictionary
	at org.alfresco.repo.policy.AssociationPolicyDelegate.checkAssocType(AssociationPolicyDelegate.java:83)
	at org.alfresco.repo.policy.AssociationPolicyDelegate.get(AssociationPolicyDelegate.java:169)
	at org.alfresco.repo.node.AbstractNodeServiceImpl.invokeOnCreateAssociation(AbstractNodeServiceImpl.java:685)
	at org.alfresco.repo.node.db.DbNodeServiceImpl.createAssociation(DbNodeServiceImpl.java:2019)
	at sun.reflect.GeneratedMethodAccessor1048.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:309)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)

```

**Comment by peterkk** [comment]
Closed with HPI commit #14918
