### ISSUE TITLE
Export with Annotations - Trying to get user by pretty name only works for Documentum

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1083]
I'm seeing an issue with the export with annotations feature (I was on edge2).  When I try email, the sending fails if any documents have annotations.  With advanced combine to PDF, it's throwing a similar error, although the action completes successfully (but the final PDF doesn't include any docs with annotations). 

It looks like this is an issue with the code assuming that it can use the user's pretty name to find the user object.  Instead, the code should be using the user ID (login name).  Here are the errors:

Send Email Error
```
11:08:37,291 ERROR [com.tsgrp.opencontent.universal.annotation.XFDFAnnotationImpl] [ajp-apr-8009-exec-6] Error getting the annotated PDF.
com.tsgrp.opencontent.core.exception.OCRuntimeException: Failed to fetch user for provided username: George Steimer
	at com.tsgrp.opencontent.universal.annotation.XFDFAnnotationImpl.getAnnotatedPDF(XFDFAnnotationImpl.java:1024)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:309)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:196)
	at com.sun.proxy.$Proxy340.getAnnotatedPDF(Unknown Source)
	at com.tsgrp.opencontent.universal.action.executer.SendFolderEmailActionExecuter.setupEmail(SendFolderEmailActionExecuter.java:299)
	at com.tsgrp.opencontent.universal.action.executer.SendFolderEmailActionExecuter.executeImpl(SendFolderEmailActionExecuter.java:168)
	at com.tsgrp.opencontent.core.action.executer.EmailWithFolderNoteActionExecuter.executeImpl(EmailWithFolderNoteActionExecuter.java:22)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:183)
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:321)
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:190)
```

Combine PDF error:
```
11:12:35,056 ERROR [com.tsgrp.opencontent.universal.annotation.XFDFAnnotationImpl] [ajp-apr-8009-exec-8] Error getting the annotated PDF.
com.tsgrp.opencontent.core.exception.OCRuntimeException: Failed to fetch user for provided username: George Steimer
	at com.tsgrp.opencontent.universal.annotation.XFDFAnnotationImpl.getAnnotatedPDF(XFDFAnnotationImpl.java:1024)
```

**Comment by vachanta93** [comment]
It seems that getAnnotatedPDF didn't really like that we used the user's pretty name instead of just the login name, so we are now sending only the user's login name to the getAnnotatedPDF call.

Rev #14301
