### ISSUE TITLE
Cannot route AW Form that was generated using an Adobe Template

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1289]
If an AW form template utilizes a Adobe Form template, signoff fails during an Active Wizard review (and I'm assuming approval) route.  Steps to reproduce:

1. Create a form that utilizes an Adobe Form template
1. Route the form for approval
1. Attempt to sign off.  

Error in OC is:

```
2017-01-20 14:25:46,365	ajp-apr-8009-exec-4	ERROR	EmbeddedAlfrescoAdvice	An unspecified OC exception occurred
com.tsgrp.opencontent.core.exception.OCRuntimeException: Error creating audit event in WizardReviewCompleteServiceTask: 
	at com.tsgrp.opencontent.wizard.activiti.workflow.listener.WizardReviewWorkflowCompleteServiceTask.execute(WizardReviewWorkflowCompleteServiceTask.java:94) ~[oc-hpiDemoAlf.3.wizard-2.5.jar:2.5]
Caused by: java.lang.RuntimeException: there was an error trying to reset approval details
	at com.tsgrp.opencontent.wizard.activiti.workflow.ActivitiClientWizardWorkflowImpl.resetApprovalDetails(ActivitiClientWizardWorkflowImpl.java:372) ~[oc-hpiDemoAlf.3.wizard-2.5.jar:2.5]
	at com.tsgrp.opencontent.wizard.activiti.workflow.listener.WizardReviewWorkflowCompleteServiceTask.execute(WizardReviewWorkflowCompleteServiceTask.java:85) ~[oc-hpiDemoAlf.3.wizard-2.5.jar:2.5]
	... 111 more
Caused by: com.tsgrp.opencontent.core.exception.OCRuntimeException: could not find workflow definition object in the repository. Cannot create new approval details object
	at com.tsgrp.opencontent.wizard.activiti.workflow.WizardWorkflowHelper.generateNewApprovalDetails(WizardWorkflowHelper.java:63) ~[oc-hpiDemoAlf.3.wizard-2.5.jar:2.5]
	at com.tsgrp.opencontent.wizard.activiti.workflow.ActivitiClientWizardWorkflowImpl.resetApprovalDetails(ActivitiClientWizardWorkflowImpl.java:369) ~[oc-hpiDemoAlf.3.wizard-2.5.jar:2.5]
	at com.tsgrp.opencontent.wizard.activiti.workflow.listener.WizardReviewWorkflowCompleteServiceTask.execute(WizardReviewWorkflowCompleteServiceTask.java:85) ~[oc-hpiDemoAlf.3.wizard-2.5.jar:2.5]
	... 111 more
```
I've only tried review routes, but when updating this, we should test that AW forms that use Adobe templates work with:

- [ ] Review Route
- [ ] Approval route with no signature pages
- [ ] Approval route with signature pages
- [ ] Delegate during review route (including multiple delegates)
- [ ] Delegate during approval route (including multiple delegates)
- [ ] Reassign during review route (including multiple reassigns)
- [ ] Reassign during approval route (including multiple reassigns)
- [ ] Delegate during review route and then reassign
- [ ] Delegate during approval route and then reassign

**Comment by gsteimer** [comment]
See #1370.  My original thought was incorrect - this error has nothing to do with Adobe Forms.
