### ISSUE TITLE
Some Activiti Workflow Templates do not deploy on non-Alfresco Activiti 5.19.0.3

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1322]
When upgrading OC defaults to match Alfresco 5.1.2, we upgraded the default Activiti version to `5.19.0.3`.  For some reason, during OC startup the bootstrap deployer fails to deploy all non-AW activiti workflow templates with this error:

```
2017-03-03 00:11:32,398	TP-Processor3	ERROR	ActivitiWorkflowBootstrapDeployer	failed to deploy workflow definition with injected name: hpi_review_workflow.bpmn
org.activiti.engine.ActivitiException: couldn't initialize process engine from spring configuration resource file:/D:/Apache/Tomcat6-edge/webapps/OpenContent/WEB-INF/classes/activiti-context.xml: Class org.activiti.engine.ProcessEngines can not access a member of class org.activiti.spring.SpringConfigurationHelper with modifiers "public static"
	at org.activiti.engine.ProcessEngines.initProcessEngineFromSpringResource(ProcessEngines.java:130) ~[activiti-engine-5.19.0.3.jar:5.19.0.3]
	at org.activiti.engine.ProcessEngines.init(ProcessEngines.java:109) ~[activiti-engine-5.19.0.3.jar:5.19.0.3]
	at org.activiti.engine.ProcessEngines.getProcessEngine(ProcessEngines.java:224) ~[activiti-engine-5.19.0.3.jar:5.19.0.3]
	at org.activiti.engine.ProcessEngines.getDefaultProcessEngine(ProcessEngines.java:217) ~[activiti-engine-5.19.0.3.jar:5.19.0.3]
	at com.tsgrp.opencontent.activiti.services.ActivitiContext.isWorkflowDefinitionDeployed(ActivitiContext.java:68) ~[oc-hpiDemoDctm.2.activiti-2.5.jar:2.5]
	at com.tsgrp.opencontent.activiti.workflow.ActivitiWorkflowBootstrapDeployer.init(ActivitiWorkflowBootstrapDeployer.java:51) [oc-hpiDemoDctm.2.activiti-2.5.jar:2.5]

...
Caused by: java.lang.IllegalAccessException: Class org.activiti.engine.ProcessEngines can not access a member of class org.activiti.spring.SpringConfigurationHelper with modifiers "public static"
	at sun.reflect.Reflection.ensureMemberAccess(Unknown Source) ~[?:1.7.0_60]
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(Unknown Source) ~[?:1.7.0_60]
```

Active Wizard workflows seem to be working fine, not sure why.

**Comment by gsteimer** [comment]
"Fixed" this by downgrading the Activiti version back to what it was before: `5.13-alf-20140708`.  We'll have to figure this out if we want to upgrade at some point to newer versions of Activiti.

OC REV: 16082
