### ISSUE TITLE
DocuSign Retrieval Job Fails

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1331]
Not sure what's changed, but it looks like the DocuSign retrieval job no longer works on edge2 (Alfresco 5.1.2) and Release2 (Alfresco 4.2.3.1, soon to be 5.1.2).  The error in the logs is:

```
09:00:04,271 ERROR [org.quartz.core.ErrorLogger] [DefaultScheduler_Worker-6] Job (DEFAULT.com.tsgrp.opencontent.alfresco.job.retrieveDocusignContentJob threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.alfresco.error.AlfrescoRuntimeException: 02142016 Failed to execute transaction-level behaviour public abstract void org.alfresco.repo.node.NodeServicePolicies$OnAddAspectPolicy.onAddAspect(org.alfresco.service.cmr.repository.NodeRef,org.alfresco.service.namespace.QName) in transaction 492f484f-f7a9-49d7-9627-ece61e7423a6]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:227)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
Caused by: org.alfresco.error.AlfrescoRuntimeException: 02142016 Failed to execute transaction-level behaviour public abstract void org.alfresco.repo.node.NodeServicePolicies$OnAddAspectPolicy.onAddAspect(org.alfresco.service.cmr.repository.NodeRef,org.alfresco.service.namespace.QName) in transaction 492f484f-f7a9-49d7-9627-ece61e7423a6
	at org.alfresco.repo.policy.TransactionBehaviourQueue.execute(TransactionBehaviourQueue.java:257)
...
	at com.tsgrp.opencontent.alfresco.job.RetrieveDocusignContentJob$2.doWork(RetrieveDocusignContentJob.java:241)
	at com.tsgrp.opencontent.alfresco.job.RetrieveDocusignContentJob$2.doWork(RetrieveDocusignContentJob.java:238)
	at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:548)
	at com.tsgrp.opencontent.alfresco.job.RetrieveDocusignContentJob.execute(RetrieveDocusignContentJob.java:238)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
	... 1 more
Caused by: org.alfresco.service.cmr.repository.InvalidNodeRefException: Node does not exist: workspace://SpacesStore/440811c4-e151-4d0d-bfff-da3663c51f9d(Status[id=72408changeTxnId=492f484f-f7a9-49d7-9627-ece61e7423a6, dbTxnId=19210, deleted=true])
	at org.alfresco.repo.node.db.DbNodeServiceImpl.getNodePairNotNull(DbNodeServiceImpl.java:189)
	at org.alfresco.repo.node.db.DbNodeServiceImpl.hasAspect(DbNodeServiceImpl.java:1007)
	at sun.reflect.GeneratedMethodAccessor312.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:309)
	at 
...
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy99.isWorkingCopy(Unknown Source)
	at com.tsgrp.alfresco.wizard.behaviour.ControlledDocLifecycleWorkflowBehaviours.onAddAspect(ControlledDocLifecycleWorkflowBehaviours.java:86)


```

Looking at the repository, I'm not sure where that `workspace://SpacesStore/440811c4-e151-4d0d-bfff-da3663c51f9d` ID is coming from.  It's not the ID of the document that was sent to DocuSign and it's not the ID of the DocuSign tracking object in `/hpi/docuSignData`

**Comment by gsteimer** [comment]
Fixed with OC Rev 16115

**Comment by gsteimer** [comment]
Not sure what's going on, but now we're running into a new error:

```
2017-03-14 14:54:02,242 ERROR [org.quartz.core.ErrorLogger] Job (DEFAULT.com.tsgrp.opencontent.alfresco.job.retrieveDocusignContentJob threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: com.tsgrp.opencontent.core.exception.OCRuntimeException: Failed to fetch objects with the tsg:docusignable aspect]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:227)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
Caused by: com.tsgrp.opencontent.core.exception.OCRuntimeException: Failed to fetch objects with the tsg:docusignable aspect
	at com.tsgrp.opencontent.alfresco.job.RetrieveDocusignContentJob$1.execute(RetrieveDocusignContentJob.java:225)
	at com.tsgrp.opencontent.alfresco.job.RetrieveDocusignContentJob$1.execute(RetrieveDocusignContentJob.java:88)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:352)
	at com.tsgrp.opencontent.alfresco.job.RetrieveDocusignContentJob$2.doWork(RetrieveDocusignContentJob.java:241)
	at com.tsgrp.opencontent.alfresco.job.RetrieveDocusignContentJob$2.doWork(RetrieveDocusignContentJob.java:238)
	at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:555)
	at com.tsgrp.opencontent.alfresco.job.RetrieveDocusignContentJob.execute(RetrieveDocusignContentJob.java:238)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
	... 1 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.tsgrp.opencontent.alfresco.job.RetrieveDocusignContentJob$1.execute(RetrieveDocusignContentJob.java:211)
```

The code in question is here:

```java
if (results.getNumberFound() == 1) {
	NodeRef curEnvelopeRef = results.getNodeRef(0);
	List<AssociationRef> children = serviceRegistry.getNodeService().getTargetAssocs(curEnvelopeRef, HPIModel.ASSOC_OUT_TO_DOCUSIGN);
```

The code is explicity checking to make sure there's at least one result, so I'm not sure what's happening.  Note that this worked perfectly fine on my local.  The error above is happening on edge2.  Once release2 rebuilds we can test to see if the same thing is happening there...

**Comment by gsteimer** [comment]
Upon further inspection, it looks like it was bad data in the repository that was causing that issue.  It was actually a few lines below that was the problem:

```java
if (results.getNumberFound() == 1) {
	NodeRef curEnvelopeRef = results.getNodeRef(0);
	List<AssociationRef> children = serviceRegistry.getNodeService().getTargetAssocs(curEnvelopeRef, HPIModel.ASSOC_OUT_TO_DOCUSIGN);
	NodeRef docRef = children.get(0).getTargetRef();
```

It turns out that it was a bad object in `/hpi/docuSignData` that wasn't attached to any objects.

OC REV 16119 updates the code to log a warning rather than failing with the `IndexOutOfBoundsException`
