### ISSUE TITLE
Alfresco - Cannot delete objects from non tag tracking folder

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1358]
It looks like the `TagTrackingFolderBehaviour` is being fired when it shouldn't be upon document delete in a non tag tracking folder.  Currently, the Human Resources trac on edge2 has tag tracking on.  Deletes work here, but fail with the error below in any other trac.

Here's the error stack from Alfresco:

```
com.tsgrp.opencontent.core.exception.OCRuntimeException: Error in DeleteDocumentActionExecuter: org.alfresco.error.AlfrescoRuntimeException: 03070580 Failed to execute transaction-level behaviour public abstract void org.alfresco.repo.node.NodeServicePolicies$OnUpdatePropertiesPolicy.onUpdateProperties(org.alfresco.service.cmr.repository.NodeRef,java.util.Map,java.util.Map) in transaction 847c2f10-8dee-461e-ae58-e4c1c5edc024
	at 
...
com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:85)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy365.enhancedDeleteObject(Unknown Source)
	at com.tsgrp.opencontent.core.action.executer.DeleteDocumentActionExecuter.executeImpl(DeleteDocumentActionExecuter.java:90)
	at 
...
Caused by: java.lang.NullPointerException
	at com.tsgrp.alfresco.behaviour.TagTrackingFolderBehaviour.processCompleteness(TagTrackingFolderBehaviour.java:80)
	at com.tsgrp.alfresco.behaviour.TagTrackingFolderBehaviour.onUpdateProperties(TagTrackingFolderBehaviour.java:128)
	at sun.reflect.GeneratedMethodAccessor1515.invoke(Unknown Source)

```

**Comment by grahamsinger** [comment]
Fixed with revision 16281
