### ISSUE TITLE
Cannot edit AW form with attached document

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1359]
Steps to recreate:

1. Create a form with an attached document.  For example: Simple CR, upload document for Description and Rationale of Change
1. Finish the form, should work correctly and upload the document as a supporting document
1. Edit the form and attempt to go to the summary page.  Fails with the following error:

```
Uncaught TypeError: Cannot read property 'substring' of undefined
    at Object.ImagePreview.isImage (http://release2.tsgrp.com/hpi/assets/require-e7f045ca4ef885db6119e7ab8c111768.js:134947:18)
    at http://release2.tsgrp.com/hpi/assets/require-e7f045ca4ef885db6119e7ab8c111768.js:140721:29
    at Array.forEach (native)
    at Function.x.each.x.forEach (http://release2.tsgrp.com/hpi/assets/require-e7f045ca4ef885db6119e7ab8c111768.js:3366:37)
    at parseFileUploadQuestion (http://release2.tsgrp.com/hpi/assets/require-e7f045ca4ef885db6119e7ab8c111768.js:140717:11)
    at parseQuestionIntoSimpleQuestionModel (http://release2.tsgrp.com/hpi/assets/require-e7f045ca4ef885db6119e7ab8c111768.js:140743:27)
    at http://release2.tsgrp.com/hpi/assets/require-e7f045ca4ef885db6119e7ab8c111768.js:140829:49
```

The above stack trace looks to be related to the image preview code that attempts to display the document inline with the form.  Note - I tried attaching a PDF (which shouldn't show the preview) and a JPG (which should) and both failed with the same error

**Comment by gpolonus** [comment]
WIZARD IMAGE PREVIEW - File type object was being processed upon upload of an image when creating a new form, but when the same form is edited, the variable is an object type object instead of a file type object, so errors were thrown. Now the object type object gets processed differently because its content is already there instead of needing to be read. Image preview now works in upload portion of form creation and on the summary page of the form creation. Fixed with commit #17717 CR : Andy, Dan
