### ISSUE TITLE
Required Docs - Mutliple Document Upload

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1363]
When uploading to a Required Documents (sometimes called Tag Tracking) folder in Documentum, one document always fails when a user uploads more than one document in the Bulk Upload action.

- [x] Upload one document - works 
- [ ] Upload two documents - one works and one fails
- [ ] Upload three documents - two work and one fails
- [ ] Upload four documents - three work and one fails

The error in every case is:

```
2017-04-18 09:29:36,977	TP-Processor2	ERROR	RESTService	Docbase error: [DM_SYSOBJECT_E_VERSION_MISMATCH]error:  &quot;save of object failed because of version mismatch: old version was 9&quot;
com.tsgrp.opencontent.core.exception.OCRuntimeException: Docbase error: [DM_SYSOBJECT_E_VERSION_MISMATCH]error:  "save of object failed because of version mismatch: old version was 9"
	at com.tsgrp.opencontent.dctm.content.DCTMContentImpl.updateObject(DCTMContentImpl.java:2137) ~[oc-hpiDemoDctm.2.dctm-2.5.jar:2.5]
	at com.tsgrp.opencontent.core.action.executer.AddDocumentActionExecuter.processRequiredDocuments(AddDocumentActionExecuter.java:559) ~[oc-hpiDemoDctm.1.core-2.5.jar:2.5]
	at com.tsgrp.opencontent.core.action.executer.AddDocumentActionExecuter.doUpload(AddDocumentActionExecuter.java:503) ~[oc-hpiDemoDctm.1.core-2.5.jar:2.5]
	at com.tsgrp.opencontent.core.action.executer.AddDocumentActionExecuter.executeImpl(AddDocumentActionExecuter.java:244) ~[oc-hpiDemoDctm.1.core-2.5.jar:2.5]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:198) ~[oc-hpiDemoDctm.1.core-2.5.jar:2.5]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:137) ~[oc-hpiDemoDctm.1.core-2.5.jar:2.5]
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:471) ~[oc-hpiDemoDctm.1.core-2.5.jar:2.5]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeWithAttachment(RESTAction.java:663) ~[oc-hpiDemoDctm.1.core-2.5.jar:2.5]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPostWithAttachment(RESTAction.java:545) ~[oc-hpiDemoDctm.1.core-2.5.jar:2.5]
...
Caused by: com.documentum.fc.common.DfException: [DM_SYSOBJECT_E_VERSION_MISMATCH]error:  "save of object failed because of version mismatch: old version was 9"
	at com.documentum.fc.client.impl.docbase.DocbaseExceptionMapper.newException(DocbaseExceptionMapper.java:57) ~[dfc-7.1.jar:?]
...
	at com.documentum.fc.client.DfFolder___PROXY.save(DfFolder___PROXY.java) ~[?:?]
	at com.tsgrp.opencontent.dctm.content.DCTMContentImpl.updateObject(DCTMContentImpl.java:2134) ~[oc-hpiDemoDctm.2.dctm-2.5.jar:2.5]
```

**Comment by gsteimer** [comment]
It seems that the problem is that Documentum doesn't like when more than one thread is trying to update properties on the same folder at the same time.  We looked into doing something like this:

1. checkout the folder
1. update properties
1. save the folder (as the same version, don't try to version)

This seems to work fine in Documentum and HBase, but will not work in Alfresco with the way that our AlfrescoEmb content impl works.  Side note, it does look like the checkout API works in alfresco, but the lock type is `READ_ONLY_LOCK`.  This is leading us to believe that it may not be possible to use this approach with Alfresco.

To work around the problem, it is recommended to utilize the "Synchronous Upload" feature of Bulk Import when working with Required Docs folders on Documentum.  Note that this feature is currently awaiting a merge from a client branch.

**Comment by gsteimer** [comment]
Note - in case we want to resurrect this, my attempt to synchronize just the folder update portion of the action executer is here: `feature_branches/req-docs-synchronized-folder-update-attempt`

**Comment by gsteimer** [comment]
Note - we've tried this with @grahamsinger's update to make Bulk Upload synchronous, but unfortunately we still see the `DM_SYSOBJECT_E_VERSION_MISMATCH` error.  More investigation is needed because this shouldn't happen in synchronous mode.

**Comment by gsteimer** [comment]
@grahamsinger's fixes detailed here seem to have fixed the issue: https://github.com/tsgrp/HPI/issues/1369#issuecomment-303431208

Going forward, we will recommend synchronous mode for all Documentum clients who want to use required documents.
