### ISSUE TITLE
ShareFile - Fails Closing Session

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1372]
Sending via ShareFile seems to work in trunk, but for some reason, I see this in the logs when OC is done uploading documents:

```
2017-04-25 14:01:03,043	http-apr-8080-exec-8	ERROR	TSGShareFile	Failed to close Sharefile session.
com.citrix.sharefile.api.exceptions.SFOtherException: java.net.ProtocolException: cannot write to a URLConnection if doOutput=false - call setDoOutput(true)
	at com.citrix.sharefile.api.SFApiQueryExecutor.executeBlockingQuery(SFApiQueryExecutor.java:311) ~[sharefile-api-3.1.2.jar:?]
	at com.citrix.sharefile.api.SFApiClient.executeQuery(SFApiClient.java:260) ~[sharefile-api-3.1.2.jar:?]
	at com.citrix.sharefile.api.SFApiQuery.execute(SFApiQuery.java:28) ~[sharefile-api-3.1.2.jar:?]
	at com.citrix.sharefile.api.SFApiQuery.execute(SFApiQuery.java:11) ~[sharefile-api-3.1.2.jar:?]
	at com.tsgrp.opencontent.sharefile.impl.TSGShareFile.shareEmailAttachments(TSGShareFile.java:68) [oc-hpiDemoAlf.3.sharefile-2.6.jar:2.6]
	at com.tsgrp.opencontent.universal.action.executer.SendFolderEmailActionExecuter.setupEmail(SendFolderEmailActionExecuter.java:327) [bin/:2.6]
	at com.tsgrp.opencontent.universal.action.executer.SendFolderEmailActionExecuter.executeImpl(SendFolderEmailActionExecuter.java:171) [bin/:2.6]
	at com.tsgrp.opencontent.core.action.executer.EmailWithFolderNoteActionExecuter.executeImpl(EmailWithFolderNoteActionExecuter.java:22) [bin/:2.6]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:198) [bin/:2.6]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:137) [bin/:2.6]
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:471) [bin/:2.6]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:198) [bin/:2.6]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
...
Caused by: java.net.ProtocolException: cannot write to a URLConnection if doOutput=false - call setDoOutput(true)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source) ~[?:1.8.0_112]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source) ~[?:1.8.0_112]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source) ~[?:1.8.0_112]
	at com.citrix.sharefile.api.https.SFHttpsCaller.postBody(SFHttpsCaller.java:55) ~[sharefile-api-3.1.2.jar:?]
	at com.citrix.sharefile.api.SFApiQueryExecutor.handleHttPost(SFApiQueryExecutor.java:115) ~[sharefile-api-3.1.2.jar:?]
	at com.citrix.sharefile.api.SFApiQueryExecutor.executeBlockingQuery(SFApiQueryExecutor.java:221) ~[sharefile-api-3.1.2.jar:?]
	... 55 more
```

@Swence32 @dhartman25 - did you guys see this on your client branch?  If so, is there a fix?

**Comment by kgarelli** [comment]
OC revision 20635
now closing our ShareFile session over REST rather than the SDK.
