### ISSUE TITLE
Alfresco - Cannot View Audit After Permanent Redact

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1377]
Steps to recreate:

1. Make sure alfresco is setup to audit whatever doctype you're working with
1. Redact a document
1. Try to view audit... 💥 

```
2017-04-27 16:09:27,847	http-apr-8080-exec-2	ERROR	EmbeddedAlfrescoAdvice	Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.audit.IAudit| name: getAuditEvents
java.lang.NullPointerException
	at com.tsgrp.opencontent.core.user.UserUtil.getLabelName(UserUtil.java:45) ~[bin/:2.6]
	at com.tsgrp.opencontent.alfresco.audit.AlfrescoEmbAuditImpl$1$1.handleAuditEntry(AlfrescoEmbAuditImpl.java:220) ~[bin/:2.6]
	at org.alfresco.repo.domain.audit.AbstractAuditDAOImpl$AuditQueryRowHandler.processResult(AbstractAuditDAOImpl.java:441) ~[alfresco-repository-5.1.2.jar:5.1.2]
```

**Comment by gsteimer** [comment]
Fixed in OC Rev 16409
