### ISSUE TITLE
Activiti expressions failing - cannot find variable

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1446]
The Policy Contract Annual Review template looks like this:

![image](https://user-images.githubusercontent.com/1377228/28674196-57785bf6-72aa-11e7-8d42-eccb6da40ce7.png)

For the decision point, we use an expression to know whether to go to the escalated or normal approval step.  The `Go To Normal` decision condition looks like this:

![image](https://user-images.githubusercontent.com/1377228/28674423-fa60568e-72aa-11e7-8fdc-d8e9c10f38c2.png)

However, when this condition runs during a workflow instance, the following error is thrown in OC:

```
2017-07-27 09:06:09,877	ajp-apr-8009-exec-4	ERROR	EmbeddedAlfrescoAdvice	Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.workflow.IWorkflow| name: completeTask
org.activiti.engine.ActivitiException: Unknown property used in expression: ${amount < 500}
...
	at org.activiti.engine.impl.TaskServiceImpl.complete(TaskServiceImpl.java:179) ~[activiti-engine-5.19.0.3.jar:5.19.0.3]
	at com.tsgrp.opencontent.activiti.workflow.ActivitiWorkflowImpl.completeTask(ActivitiWorkflowImpl.java:570) ~[oc-hpiDemoAlf.2.activiti-2.6.jar:2.6]
...
Caused by: org.activiti.engine.impl.javax.el.PropertyNotFoundException: Cannot resolve identifier 'amount'
	at org.activiti.engine.impl.juel.AstIdentifier.eval(AstIdentifier.java:83) ~[activiti-engine-5.19.0.3.jar:5.19.0.3]
```

@nquillin91

**Comment by nquillin91** [comment]
Fixed with REV 17032
