### ISSUE TITLE
Search fails when user has no groups

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1471]
STS tests found this one on edge1 (not sure if this would be an issue on Alfresco or Hbase, but I'm guessing yes).

If a user does not have any groups (both `jconsumer` and `stsconsumer` on edge1 are not in any groups), any search in HPI fails with the following error:

```
2017-09-05 10:22:42,144	TP-Processor7	ERROR	RESTService	null
java.lang.NullPointerException
	at com.tsgrp.opencontent.core.query.RESTQueryUtil.parseRestrictionConfig(RESTQueryUtil.java:403) ~[oc-hpiDemoDctm.1.core-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.query.RESTQuery.ocQuery(RESTQuery.java:164) ~[oc-hpiDemoDctm.1.core-2.6.jar:2.6]
```

From talking to @b-k-white the issue has to do with the code he updated in commit 17230 to move query restriction logic to OC.

**Comment by b-k-white** [comment]
Added null check. Fixed with revision 17241
