### ISSUE TITLE
Cannot create a non-quality controlled document with chain versionable AMP applied

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1486]
When attempting to create a controlled document that is not a quality document (Ex: `aw:controlledDocument` or `tsg:contract`) the following error occurs:

```
2017-09-21 16:25:34,749	http-apr-8080-exec-9	DEBUG	TSGControlledDocumentBehaviors	Start TSGControlledDocumentBehaviors.onAddAspect
2017-09-21 16:25:34,780	http-apr-8080-exec-9	DEBUG	TSGControlledDocumentBehaviors	End TSGControlledDocumentBehaviors.onAddAspect
2017-09-21 16:25:34,787	http-apr-8080-exec-9	ERROR	AlfrescoEmbContentImpl	Unhandled exception: 08210168 Access Denied.  You do not have the appropriate permissions to perform this operation.
org.alfresco.repo.security.permissions.AccessDeniedException: 08210168 Access Denied.  You do not have the appropriate permissions to perform this operation.
	at org.alfresco.repo.security.permissions.impl.ExceptionTranslatorMethodInterceptor.invoke(ExceptionTranslatorMethodInterceptor.java:57) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.alfresco.repo.audit.AuditMethodInterceptor.proceedWithAudit(AuditMethodInterceptor.java:256) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at org.alfresco.repo.audit.AuditMethodInterceptor.proceed(AuditMethodInterceptor.java:216) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at org.alfresco.repo.audit.AuditMethodInterceptor.invoke(AuditMethodInterceptor.java:171) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) ~[spring-tx-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) ~[spring-tx-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at com.sun.proxy.$Proxy57.getWriter(Unknown Source) ~[?:?]
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.enhancedCreateObject(AlfrescoEmbContentImpl.java:432) [bin/:2.6]
	at sun.reflect.GeneratedMethodAccessor875.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(Unknown Source) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_112]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) [spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) [spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice$1.execute(EmbeddedAlfrescoAdvice.java:72) [bin/:2.6]
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464) [alfresco-repository-5.1.2.jar:5.1.2]
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:85) [bin/:2.6]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) [spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at com.sun.proxy.$Proxy370.enhancedCreateObject(Unknown Source) [?:?]
	at com.tsgrp.opencontent.core.action.executer.AddDocumentActionExecuter.doUpload(AddDocumentActionExecuter.java:453) [bin/:2.6]
	at com.tsgrp.opencontent.core.action.executer.AddDocumentActionExecuter.executeImpl(AddDocumentActionExecuter.java:245) [bin/:2.6]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:198) [bin/:2.6]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:137) [bin/:2.6]
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:471) [bin/:2.6]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeWithAttachment(RESTAction.java:663) [bin/:2.6]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPostWithAttachment(RESTAction.java:545) [bin/:2.6]

```

**Comment by ZachGerth** [comment]
Resolved with OC Commit 17415.
