### ISSUE TITLE
HBase 64k Audit Trail Limit

### ISSUE THREAD

**Issue by benallenallen** [tsgrp/HPI#1491]
Right now there is code in the HBaseUtil that uses readUTF and writeUTF methods on DataInputStream and DataOutputStream objects, which have a 64k limit (see: https://www.drillio.com/en/2009/java-encoded-string-too-long-64kb-limit/)

This shouldn't ordinarily be an issue as 64k in a single property is a TON of information to store as the value to a property, but since the audit trail also stores the entire audit trail using the same methods as storing a property, the way that we are storing/retrieving audits will fail if the audit trail for a single entry gets large. We really should just be storing the auditTrail like we are storing content, which doesn't have this issue.

The error that shows up now is:
```
2017-09-29 13:27:07,604	ajp-8509-5	ERROR	HBaseJSONUtil	Error updating JSON for 68695956-bcdd-4a08-a047-f9e6ce6ea2a8-0.1, auditTrailcom.tsgrp.opencontent.core.exception.OCRuntimeException: Unexpected error has occurred during array/list to byte array conversion. 
com.tsgrp.opencontent.core.exception.OCRuntimeException: Unexpected error has occurred during array/list to byte array conversion. 
	at com.tsgrp.opencontent.hbase.utilities.HBaseUtil.convertToByteArray(HBaseUtil.java:187) ~[oc-wizardHbase.2.hbase-2.6.jar:2.6]
	at com.tsgrp.opencontent.hbase.utilities.HBaseJSONUtil.updateJSONProperty(HBaseJSONUtil.java:57) [oc-wizardHbase.2.hbase-2.6.jar:2.6]
	at com.tsgrp.opencontent.hbase.audit.HBaseAuditImpl.createAuditEvent(HBaseAuditImpl.java:77) [oc-wizardHbase.2.hbase-2.6.jar:2.6]
	at com.tsgrp.opencontent.hbase.utilities.HBaseAuditUtil.createPropertiesAuditEvent(HBaseAuditUtil.java:110) [oc-wizardHbase.2.hbase-2.6.jar:2.6]
	at com.tsgrp.opencontent.hbase.content.HBaseContentImpl.enhancedUpdateObject(HBaseContentImpl.java:860) [oc-wizardHbase.2.hbase-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.preferences.GenericPreferencesService.updatePreferencesByName(GenericPreferencesService.java:230) [oc-wizardHbase.1.core-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.userpreferences.persistence.RESTUserPreferencesService.saveUserPreference(RESTUserPreferencesService.java:128) [oc-wizardHbase.3.hpi-2.6.jar:2.6]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176) [spring-web-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:440) [spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:428) [spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933) [spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867) [spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953) [spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:855) [spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:643) [servlet-api.jar:?]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829) [spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290) [catalina.jar:6.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:6.0.37]
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:107) [catalina.jar:6.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235) [catalina.jar:6.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:6.0.37]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233) [catalina.jar:6.0.37]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191) [catalina.jar:6.0.37]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127) [catalina.jar:6.0.37]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:6.0.37]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [catalina.jar:6.0.37]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293) [catalina.jar:6.0.37]
	at org.apache.coyote.ajp.AjpAprProcessor.process(AjpAprProcessor.java:448) [tomcat-coyote.jar:6.0.37]
	at org.apache.coyote.ajp.AjpAprProtocol$AjpConnectionHandler.process(AjpAprProtocol.java:403) [tomcat-coyote.jar:6.0.37]
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1760) [tomcat-coyote.jar:6.0.37]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_60]
Caused by: java.io.UTFDataFormatException: encoded string too long: 65548 bytes
	at java.io.DataOutputStream.writeUTF(Unknown Source) ~[?:1.7.0_60]
	at java.io.DataOutputStream.writeUTF(Unknown Source) ~[?:1.7.0_60]
	at com.tsgrp.opencontent.hbase.utilities.HBaseUtil.convertToByteArray(HBaseUtil.java:160) ~[oc-wizardHbase.2.hbase-2.6.jar:2.6]
```

**Comment by benallenallen** [comment]
Fixed in OC Rev 17555
