### ISSUE TITLE
Major Version Quality Document cannot be edited with OneDrive

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1501]
When attempting to edit a major version quality document (ex: 1.0, Effective) - it shouldn't matter whether or not the user goes through the normal checkin/checkout or edits the document with OneDrive.  This fails differently depending on if Chain Versionable is used or not:

**With Chain Versionable**
The document checks out successfully to OneDrive, however upon checkin it fails with the following error:

![image](https://user-images.githubusercontent.com/1377228/31450277-a7f89014-ae6e-11e7-9845-f35809e5c2ee.png)

In the `alfresco.log`, I see this error:

```
2017-10-11 10:25:51,864 ERROR [com.tsgrp.alfresco.chained.versionable.VersionChainPolicy] Failed running doWork!
org.alfresco.service.namespace.InvalidQNameException: A QName must consist of a local name
	at org.alfresco.service.namespace.QName.createQName(QName.java:94)
	at org.alfresco.service.namespace.QName.createQName(QName.java:131)
	at com.tsgrp.alfresco.chained.versionable.VersionChainPolicy.associationShouldBeMoved(VersionChainPolicy.java:408)
	at com.tsgrp.alfresco.chained.versionable.VersionChainPolicy.updateSourceTargetAssociations(VersionChainPolicy.java:388)
	at com.tsgrp.alfresco.chained.versionable.VersionChainPolicy.createVersionCopy(VersionChainPolicy.java:350)
	at com.tsgrp.alfresco.chained.versionable.VersionChainPolicy.access$100(VersionChainPolicy.java:52)
	at com.tsgrp.alfresco.chained.versionable.VersionChainPolicy$1.doWork(VersionChainPolicy.java:205)
	at com.tsgrp.alfresco.chained.versionable.VersionChainPolicy$1.doWork(VersionChainPolicy.java:174)
	at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:555)
	at com.tsgrp.alfresco.chained.versionable.VersionChainPolicy.beforeCheckIn(VersionChainPolicy.java:174)

```

**Without Chain Versionable**
The checkin works in this case, but the new x.1, Draft node is not created.  Instead, you end up with a 1.1, Effective document.  In a regulated environment, this is worse than if it had just failed.

**Comment by ZachGerth** [comment]
That error is identical to #1493. I believe that it is related to some of the changes to ensure CVN and OC are fully decoupled.

**Comment by gsteimer** [comment]
Looks like this was fixed with the update to the Chain Versionable amp along with #1488.  I'll test #1493 next.

**Comment by gsteimer** [comment]
Reopening - this now works for new controlled documents using Chain Versionable.  It's still an issue for Legacy documents.
