### ISSUE TITLE
Complete Wizard Task Fails on Alfresco due to oa:annotated aspect

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1516]
Finishing a workflow task fails due to the behavior associated with the `oa:annotated` aspect.  The error in OC is:

```
2017-10-30 14:34:36,015	ajp-apr-8009-exec-9	ERROR	TSGAnnotationAspectBehavior	Failed running doWork!
org.alfresco.service.cmr.repository.InvalidNodeRefException: Node does not exist: workspace://SpacesStore/ffa2564f-f96b-4007-82d4-16f0135e1b7b (status:Status[id=217050changeTxnId=ea9ea49b-497f-4eda-bc8a-488b6f0ff420, dbTxnId=56890, deleted=true])
	at org.alfresco.repo.node.db.DbNodeServiceImpl.getNodePairNotNull(DbNodeServiceImpl.java:198) ~[alfresco-repository-5.1.2.jar:5.1.2]
...
	at com.tsgrp.alfresco.behaviour.TSGAnnotationAspectBehavior$1.doWork(TSGAnnotationAspectBehavior.java:103) [oc-hpiDemoAlf.2.alfrescoEmb-2.6.jar:2.6]
	at com.tsgrp.alfresco.behaviour.TSGAnnotationAspectBehavior$1.doWork(TSGAnnotationAspectBehavior.java:85) [oc-hpiDemoAlf.2.alfrescoEmb-2.6.jar:2.6]
	at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:555) [alfresco-data-model-5.1.2.jar:5.1.2]
	at com.tsgrp.alfresco.behaviour.TSGAnnotationAspectBehavior.beforeDeleteAssociation(TSGAnnotationAspectBehavior.java:85) [oc-hpiDemoAlf.2.alfrescoEmb-2.6.jar:2.6]
...
	at com.tsgrp.opencontent.wizard.action.executer.CompleteWizardApprovalRouteActionExecuter.executeImpl(CompleteWizardApprovalRouteActionExecuter.java:36) [oc-hpiDemoAlf.3.wizard-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:198) [oc-hpiDemoAlf.1.core-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:137) [oc-hpiDemoAlf.1.core-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:471) [oc-hpiDemoAlf.1.core-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:205) [oc-hpiDemoAlf.1.core-2.6.jar:2.6]
...
Caused by: org.alfresco.service.cmr.repository.InvalidNodeRefException: Node does not exist: workspace://SpacesStore/ffa2564f-f96b-4007-82d4-16f0135e1b7b (status:Status[id=217050changeTxnId=ea9ea49b-497f-4eda-bc8a-488b6f0ff420, dbTxnId=56890, deleted=true])
	at org.alfresco.repo.node.db.DbNodeServiceImpl.getNodePairNotNull(DbNodeServiceImpl.java:198) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at org.alfresco.repo.node.db.DbNodeServiceImpl.hasAspect_aroundBody38(DbNodeServiceImpl.java:1043) ~[alfresco-repository-5.1.2.jar:5.1.2]
```

**Comment by gsteimer** [comment]
Fixed with OC Rev 17623.  CR: Rudra
