### ISSUE TITLE
View Audit fails on Chain Versionable Document after property update

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1524]
View Audit fails on a chain versionable document after editing properties.  The error is:

```
2017-11-06 10:15:56,844	ajp-apr-8009-exec-3	ERROR	EmbeddedAlfrescoAdvice	Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.audit.IAudit| name: getAuditEvents
java.lang.NullPointerException
	at com.tsgrp.opencontent.alfresco.audit.AlfrescoEmbAuditImpl.createAddPropsMap(AlfrescoEmbAuditImpl.java:401) ~[oc-hpiDemoAlf.2.alfrescoEmb-2.6.jar:2.6]
	at com.tsgrp.opencontent.alfresco.audit.AlfrescoEmbAuditImpl.access$300(AlfrescoEmbAuditImpl.java:54) ~[oc-hpiDemoAlf.2.alfrescoEmb-2.6.jar:2.6]
	at com.tsgrp.opencontent.alfresco.audit.AlfrescoEmbAuditImpl$1$1.handleAuditEntry(AlfrescoEmbAuditImpl.java:278) ~[oc-hpiDemoAlf.2.alfrescoEmb-2.6.jar:2.6]
```

It seems that the issue is in the formatting of values in this code here:

```java
	private Map<String, String> createAddPropsMap(Map<String, String> add){
		Map<String, String> map = new HashMap<String, String>();
		Iterator it = add.entrySet().iterator();
		while (it.hasNext()) {
			Map.Entry pair = (Map.Entry)it.next();
			String addVal = (String) pair.getValue();
			addVal = addVal.substring(addVal.lastIndexOf('}') + 1, addVal.length());
			map.put((String) pair.getKey(), "Property added - " + addVal);
		}

		return map;
	}
```

It's failing because the pair in question is: `{http://www.tsgrp.com/model/tsg/1.0}periodicReviewDate=null`

This must be a behavior that is clearing out the PR date.  So this begs the question - we can easily fix the issue by updating the code to handle the `null`.  But how should we do that?  Don't update the props map if the value is null?  Or put something in there like "property cleared"?  Initially I was thinking the latter, but wouldn't that audit start happening all the time for CVN docs?

**Comment by gsteimer** [comment]
Fixed with OC REV 17690
