### ISSUE TITLE
View Versions action fails

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1549]
The view versions action fails across all repositories.  The error in OC is:

```
2017-12-07 12:04:28,915	ajp-apr-8009-exec-41	ERROR	RESTService	Could not read JSON: Unrecognized field &quot;icon&quot; (Class com.tsgrp.opencontent.core.action.model.Action), not marked as ignorable
 at [Source: org.apache.catalina.connector.CoyoteInputStream@2f682db3; line: 1, column: 285] (through reference chain: com.tsgrp.opencontent.core.action.model.Action[&quot;icon&quot;]); nested exception is org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field &quot;icon&quot; (Class com.tsgrp.opencontent.core.action.model.Action), not marked as ignorable
 at [Source: org.apache.catalina.connector.CoyoteInputStream@2f682db3; line: 1, column: 285] (through reference chain: com.tsgrp.opencontent.core.action.model.Action[&quot;icon&quot;])
org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Unrecognized field "icon" (Class com.tsgrp.opencontent.core.action.model.Action), not marked as ignorable
 at [Source: org.apache.catalina.connector.CoyoteInputStream@2f682db3; line: 1, column: 285] (through reference chain: com.tsgrp.opencontent.core.action.model.Action["icon"]); nested exception is org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "icon" (Class com.tsgrp.opencontent.core.action.model.Action), not marked as ignorable
 at [Source: org.apache.catalina.connector.CoyoteInputStream@2f682db3; line: 1, column: 285] (through reference chain: com.tsgrp.opencontent.core.action.model.Action["icon"])
	at org.springframework.http.converter.json.MappingJacksonHttpMessageConverter.readJavaType(MappingJacksonHttpMessageConverter.java:181) ~[spring-web-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.http.converter.json.MappingJacksonHttpMessageConverter.readInternal(MappingJacksonHttpMessageConverter.java:166) ~[spring-web-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.http.converter.AbstractHttpMessageConverter.read(AbstractHttpMessageConverter.java:153) ~[spring-web-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.readWithMessageConverters(HandlerMethodInvoker.java:641) ~[spring-web-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.resolveRequestBody(HandlerMethodInvoker.java:605) ~[spring-web-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.resolveHandlerArguments(HandlerMethodInvoker.java:354) ~[spring-web-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:171) ~[spring-web-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:440) ~[spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:428) ~[spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933) [spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867) [spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953) [spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:855) [spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646) [servlet-api.jar:?]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829) [spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina.jar:7.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.59]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat7-websocket.jar:7.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.59]
	at org.alfresco.module.aosmodule.service.ContextRootFilter.doFilter(ContextRootFilter.java:93) [alfresco-aos-repo-binding.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.59]
	at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68) [GlobalLocalizationFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [catalina.jar:7.0.59]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504) [catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [catalina.jar:7.0.59]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.59]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.59]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421) [catalina.jar:7.0.59]
	at org.apache.coyote.ajp.AjpAprProcessor.process(AjpAprProcessor.java:188) [tomcat-coyote.jar:7.0.59]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) [tomcat-coyote.jar:7.0.59]
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2466) [tomcat-coyote.jar:7.0.59]
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2455) [tomcat-coyote.jar:7.0.59]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_65]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.59]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
Caused by: org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "icon" (Class com.tsgrp.opencontent.core.action.model.Action), not marked as ignorable
 at [Source: org.apache.catalina.connector.CoyoteInputStream@2f682db3; line: 1, column: 285] (through reference chain: com.tsgrp.opencontent.core.action.model.Action["icon"])
	at org.codehaus.jackson.map.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:53) ~[jackson-mapper-asl-1.9.13.jar:1.9.13]
	at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownFieldException(StdDeserializationContext.java:267) ~[jackson-mapper-asl-1.9.13.jar:1.9.13]
	at org.codehaus.jackson.map.deser.std.StdDeserializer.reportUnknownProperty(StdDeserializer.java:673) ~[jackson-mapper-asl-1.9.13.jar:1.9.13]
```

**Comment by joehaynes** [comment]
Fixed with HPI commit 19377. CR- Devin[0]

Fixed a bug that did not allow certain actions to be called from the new dropdown/icons. Invalid attributes were being set on the model that when passed to OC, caused OC to error.
