### ISSUE TITLE
Error message appears when finishing an existing AW Form

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1615]
When editing a form (this doesn't happen for a brand new form), after finishing editing, an error flashes on the screen briefly before the user is taken to the stage:

![aw-resume-form-error](https://user-images.githubusercontent.com/1377228/35984085-4310c7c6-0cb9-11e8-83b4-aa93d982b66d.gif)

Here's the error in OC:

```
2018-02-08 10:11:45,356	ajp-apr-8009-exec-7	DEBUG	TSGRenditionBehaviours	End TSGRenditionBehaviours.onUpdateProperties...
2018-02-08 10:11:45,450	ajp-apr-8009-exec-2	ERROR	EmbeddedAlfrescoAdvice	Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.content.IContent| name: enhancedUpdateObject
java.lang.NullPointerException
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl$3.execute(AlfrescoEmbContentImpl.java:896) ~[oc-hpiDemoAlf.2.alfrescoEmb-2.6.jar:2.6]
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl$3.execute(AlfrescoEmbContentImpl.java:790) ~[oc-hpiDemoAlf.2.alfrescoEmb-2.6.jar:2.6]
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.enhancedUpdateObject(AlfrescoEmbContentImpl.java:914) ~[oc-hpiDemoAlf.2.alfrescoEmb-2.6.jar:2.6]

...

2018-02-08 10:11:45,466	ajp-apr-8009-exec-2	ERROR	RESTService	Error Updateing Object with ID: workspace://SpacesStore/cd2faa1b-3ac4-4436-bcc8-41022535ecc5
com.tsgrp.opencontent.core.exception.OCRuntimeException: Error Updateing Object with ID: workspace://SpacesStore/cd2faa1b-3ac4-4436-bcc8-41022535ecc5
	at com.tsgrp.opencontent.wizard.core.Wizard2Impl.savePageSetInstance(Wizard2Impl.java:581) ~[oc-hpiDemoAlf.3.wizard-2.6.jar:2.6]

```

It's odd, however because it looks like it's failing in the save code.  However, the document seems fine after checkin and the PDF rendition reflects any updated values.

I tried on edge1 and I'm seeing the same behavior, so that points to this being not related to the Alfresco impl.

**Comment by gsteimer** [comment]
Here's the error that's appearing on edge1:

```
2018-02-08 10:37:41,841	TP-Processor2	ERROR	DCTMContentImpl	Error updating documentum object: [DM_SYSOBJECT_E_CANT_UNLOCK]error:  "Unsuccessful in removing the lock on SCR-109 sysobject."
com.documentum.fc.common.DfException: [DM_SYSOBJECT_E_CANT_UNLOCK]error:  "Unsuccessful in removing the lock on SCR-109 sysobject."
	at com.documentum.fc.client.impl.docbase.DocbaseExceptionMapper.newException(DocbaseExceptionMapper.java:57) ~[dfc-7.1.jar:?]
	at com.documentum.fc.client.impl.connection.docbase.MessageEntry.getException(MessageEntry.java:39) ~[dfc-7.1.jar:?]
	at com.documentum.fc.client.impl.connection.docbase.DocbaseMessageManager.getException(DocbaseMessageManager.java:137) ~[dfc-7.1.jar:?]
...
	at com.tsgrp.wizard.dctm.tbo.PageSetInstanceImpl.doCheckin(PageSetInstanceImpl.java:130) ~[?:?]
	at com.documentum.fc.client.DfSysObject.checkinEx(DfSysObject.java:831) ~[dfc-7.1.jar:?]
	at com.documentum.fc.client.DfSysObject.checkin(DfSysObject.java:824) ~[dfc-7.1.jar:?]
	at com.tsgrp.wizard.dctm.tbo.PageSetInstanceImpl___PROXY.checkin(PageSetInstanceImpl___PROXY.java) ~[?:?]
	at com.tsgrp.opencontent.dctm.content.DCTMContentImpl.enhancedUpdateObject(DCTMContentImpl.java:1489) [oc-hpiDemoDctm.2.dctm-2.6.jar:2.6]
	at com.tsgrp.opencontent.wizard.core.Wizard2Impl.savePageSetInstance(Wizard2Impl.java:579) [oc-hpiDemoDctm.3.wizard-2.6.jar:2.6]
	at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.executeImpl(FinishAndSubmitPSIActionExecutor.java:65) [oc-hpiDemoDctm.3.wizard-2.6.jar:2.6]

...

2018-02-08 10:37:41,857	TP-Processor2	DEBUG	DCTMContentImpl	END enhancedUpdateObject
2018-02-08 10:37:41,857	TP-Processor2	ERROR	RESTService	Error Updateing Object with ID: 0900000280031694
com.tsgrp.opencontent.core.exception.OCRuntimeException: Error Updateing Object with ID: 0900000280031694
	at com.tsgrp.opencontent.wizard.core.Wizard2Impl.savePageSetInstance(Wizard2Impl.java:581) ~[oc-hpiDemoDctm.3.wizard-2.6.jar:2.6]
	at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.executeImpl(FinishAndSubmitPSIActionExecutor.java:65) ~[oc-hpiDemoDctm.3.wizard-2.6.jar:2.6]
```

Looks like it's complaining about not being able to remove the lock on the object.  However, when inspecting the object after finishing the form, it's not checked out.

When debugging this on edge1 - it looks like it's calling the save process twice.  The first time it works and the second time fails.  So on Documentum at least - the error message makes sense since the second time around the document is no longer checked out.

**Comment by nreiman** [comment]
HPI Revision: 19839
CR: AK
