### ISSUE TITLE
Folder Tags fails on Alfresco

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1665]
On edge2, any related objects section (ex: Underwriting, claims tracs) will not return any results.  The error in OC is:

```
2018-03-20 12:14:24,164	ajp-apr-8009-exec-5	ERROR	AlfrescoEmbContentImpl	Unhandled Exception: null
java.lang.NullPointerException
	at org.alfresco.service.cmr.repository.NodeRef.<init>(NodeRef.java:110) ~[alfresco-data-model-5.1.2.jar:5.1.2]
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.enhancedGetProperties(AlfrescoEmbContentImpl.java:694) [oc-hpiDemoAlf.2.alfrescoEmb-2.6.jar:2.6]
...
	at com.tsgrp.opencontent.core.util.OCUtil.getOCTypeDefinition(OCUtil.java:1268) [oc-hpiDemoAlf.1.core-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.util.OCUtil.getOCObjectTypeName(OCUtil.java:1255) [oc-hpiDemoAlf.1.core-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.util.OCUtil.isTypeOrSubTypeOfExpensive(OCUtil.java:1289) [oc-hpiDemoAlf.1.core-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.action.condition.evaluator.IsSpecifiedObjectType.evaluateImpl(IsSpecifiedObjectType.java:84) [oc-hpiDemoAlf.1.core-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.action.condition.evaluator.AbstractConditionEvaluator.evaluate(AbstractConditionEvaluator.java:68) [oc-hpiDemoAlf.1.core-2.6.jar:2.6]
...
2018-03-20 12:14:24,164	ajp-apr-8009-exec-5	ERROR	CoreActionService	Failed evaluating action condition: condition-isdocumentobjecttypeorsubtype-conditionevaluator. Marking as invalid.
java.lang.RuntimeException: there was an error retrieving properties: null: java.lang.NullPointerException
	at org.alfresco.service.cmr.repository.NodeRef.<init>(NodeRef.java:110)
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.enhancedGetProperties(AlfrescoEmbContentImpl.java:694)
```

**Comment by ikaikajcorrea** [comment]
RESTHpi was comparing an ECO subtype to an OCO subtype, which resulted in a comparison of OC name to Repo name in one portion of the code. This never correctly evaluates for Alfresco implementations as they are syntaxically different (tsg:document vs. tsg_document), so I converted both strings to REPO names to ensure the correct comparison was being made.
