### ISSUE TITLE
Combine PDF - Export with Annotations does not work in Firefox

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1677]
If you have Combine PDF set to export with annotations, it fails in firefox:

![image](https://user-images.githubusercontent.com/1377228/38314556-1d2b99b0-37ec-11e8-8ca8-714c13090a61.png)

This is the OC error:

```
2018-04-04 09:34:05,705	TP-Processor1	ERROR	RESTService	Failed to convert value of type 'java.lang.String' to required type 'long'; nested exception is java.lang.NumberFormatException: For input string: &quot;NaN&quot;
org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'long'; nested exception is java.lang.NumberFormatException: For input string: "NaN"
	at org.springframework.beans.TypeConverterSupport.doConvert(TypeConverterSupport.java:77) ~[spring-beans-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:47) ~[spring-beans-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.validation.DataBinder.convertIfNecessary(DataBinder.java:603) ~[spring-context-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.resolveRequestParam(HandlerMethodInvoker.java:515) ~[spring-web-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.resolveHandlerArguments(HandlerMethodInvoker.java:348) ~[spring-web-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:171) ~[spring-web-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:440) ~[spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:428) ~[spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933) [spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867) [spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953) [spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:844) [spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617) [servlet-api.jar:?]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829) [spring-webmvc-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290) [catalina.jar:6.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:6.0.37]
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:107) [catalina.jar:6.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235) [catalina.jar:6.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:6.0.37]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233) [catalina.jar:6.0.37]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191) [catalina.jar:6.0.37]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127) [catalina.jar:6.0.37]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:6.0.37]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [catalina.jar:6.0.37]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293) [catalina.jar:6.0.37]
	at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190) [tomcat-coyote.jar:6.0.37]
	at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:311) [tomcat-coyote.jar:6.0.37]
	at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:776) [tomcat-coyote.jar:6.0.37]
	at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:705) [tomcat-coyote.jar:6.0.37]
	at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:898) [tomcat-coyote.jar:6.0.37]
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690) [tomcat-coyote.jar:6.0.37]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_60]
Caused by: java.lang.NumberFormatException: For input string: "NaN"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.7.0_60]
	at java.lang.Long.parseLong(Unknown Source) ~[?:1.7.0_60]
	at java.lang.Long.valueOf(Unknown Source) ~[?:1.7.0_60]
	at org.springframework.util.NumberUtils.parseNumber(NumberUtils.java:196) ~[spring-core-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.beans.propertyeditors.CustomNumberEditor.setAsText(CustomNumberEditor.java:113) ~[spring-beans-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.beans.TypeConverterDelegate.doConvertTextValue(TypeConverterDelegate.java:450) ~[spring-beans-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.beans.TypeConverterDelegate.doConvertValue(TypeConverterDelegate.java:423) ~[spring-beans-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:195) ~[spring-beans-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:107) ~[spring-beans-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.beans.TypeConverterSupport.doConvert(TypeConverterSupport.java:64) ~[spring-beans-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	... 32 more
```

**Comment by kpelozatsgrp** [comment]
At revision: 20315

CR: Graham and Steve.
