### ISSUE TITLE
Bulk Upload? - Silent Error in OC Logs when Viewing Stage

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1680]
Not sure exactly what's going on, but whenever I view a folder in the insurance or invoice tracs on edge2 (Alfresco), I see the following error in the logs:

```
2018-04-06 09:42:33,005	ajp-apr-8009-exec-4	ERROR	CoreActionService	Failed evaluating action condition: condition-write-conditionevaluator. Marking as invalid.
com.tsgrp.opencontent.core.exception.OCRuntimeException: pathOrId cannot be null
	at com.tsgrp.opencontent.alfresco.util.AlfrescoEmbUtil.getIdByPathOrId(AlfrescoEmbUtil.java:573) ~[oc-hpiDemoAlf.2.alfrescoEmb-2.6.jar:2.6]
	at com.tsgrp.opencontent.alfresco.core.permission.AlfrescoEmbPermissionImpl.canWrite(AlfrescoEmbPermissionImpl.java:114) ~[oc-hpiDemoAlf.2.alfrescoEmb-2.6.jar:2.6]
```

My first guess is that it's coming from the Add Documents action since that has a permission check to make sure the user has write access to the current folder.  My suspicion is that if the user doesn't have access to the folder, this error is going to make the action appear when it shouldn't.

**Comment by acastor** [comment]
Revision: 20334

SEARCH RESULT CONTROLS: Adding a check for selected objects before attempting to resolve actions. We should not make an OC call when there are no selected objects to resolve actions on. Unit Tested.

CR: Steve and Rene
