### ISSUE TITLE
Active Wizard form fails to finish when removing one or more supporting documents

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1686]
When finishing a form where supporting documents are removed, the form will not complete and the following errors display in OC.  The odd thing is it looks like the form is actually saving fine and the supporting document relationship is removed (we should still check to make sure the doc gets deleted though).  The user should be able to remove supporting documents by:

- [ ] Removing one from the list:
![image](https://user-images.githubusercontent.com/1377228/38758428-89d332e8-3f36-11e8-960d-0712c54a3333.png)

- [ ] Switching the page flow so the the page that asks the user to attach documents is no longer in the flow path.  In the Simple CR form example:
![image](https://user-images.githubusercontent.com/1377228/38758440-96fa2af8-3f36-11e8-868e-cb49cad7bf70.png)

**OC Error in Alfresco**
```
2018-04-13 16:11:32,792	ajp-apr-8009-exec-4	ERROR	RESTService	null
java.lang.NullPointerException
	at com.tsgrp.opencontent.wizard.PSIJSONUtil.resolveSupportingDocRelations(PSIJSONUtil.java:122) ~[oc-hpiDemoAlf.3.wizard-2.6.jar:2.6]
	at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.executeImpl(FinishAndSubmitPSIActionExecutor.java:80) ~[oc-hpiDemoAlf.3.wizard-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:196) ~[oc-hpiDemoAlf.1.core-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:135) ~[oc-hpiDemoAlf.1.core-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:474) ~[oc-hpiDemoAlf.1.core-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:204) ~[oc-hpiDemoAlf.1.core-2.6.jar:2.6]
```

**OC Error in Dctm**
```
2018-04-13 16:11:03,897	TP-Processor1	ERROR	RESTService	null
java.lang.NullPointerException
	at com.tsgrp.opencontent.wizard.PSIJSONUtil.resolveSupportingDocRelations(PSIJSONUtil.java:147) ~[oc-hpiDemoDctm.3.wizard-2.6.jar:2.6]
	at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.executeImpl(FinishAndSubmitPSIActionExecutor.java:80) ~[oc-hpiDemoDctm.3.wizard-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:196) ~[oc-hpiDemoDctm.1.core-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:135) ~[oc-hpiDemoDctm.1.core-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:474) ~[oc-hpiDemoDctm.1.core-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:204) ~[oc-hpiDemoDctm.1.core-2.6.jar:2.6]
```

**Comment by gsteimer** [comment]
Fixed with OC Rev 18712
