### ISSUE TITLE
Admin Search Tool - fails silently on every load

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1695]
Every time you load the admin query tool, this error is in the OC logs:

```
2018-04-26 10:43:30,316	ajp-apr-8009-exec-9	ERROR	RESTService	Unable to find object with path: hpi/default/configs/SearchConfig/undefined
com.tsgrp.opencontent.core.exception.OCObjectNotFoundException: Unable to find object with path: hpi/default/configs/SearchConfig/undefined
	at com.tsgrp.opencontent.alfresco.util.AlfrescoEmbUtil.getNodeRefByPath(AlfrescoEmbUtil.java:642) ~[oc-hpiDemoAlf.2.alfrescoEmb-2.6.jar:2.6]
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.getObjectByPath(AlfrescoEmbContentImpl.java:1430) ~[oc-hpiDemoAlf.2.alfrescoEmb-2.6.jar:2.6]
	at sun.reflect.GeneratedMethodAccessor676.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
```

I'm guessing this is because the page loads with:

![image](https://user-images.githubusercontent.com/1377228/39316566-11d2aad6-493f-11e8-88be-0ee433e4192c.png)

... and it's incorrectly trying to fetch the undefined config.  The bigger question though is - why does it need to even fetch the config here in the first place?

**Comment by jharkins2** [comment]
Fix: Only fetch config if blank isn't chosen.
File: adminsearctool.js
Revision #: 20529
CR-Nick
