### ISSUE TITLE
Admin search tool - fails with NPE

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1697]
On edge2, the admin search tool fails with Null Pointer Exceptions for every search I'm trying.  Here are some examples:

- Find Wizard forms with Name like `SCR`
- Find Quality documents with Name like `TSG`
- Find Policy folders with Policy Year 2017

All of the above fail on edge2 with:

```
2018-04-26 11:45:01,296	ajp-apr-8009-exec-10	ERROR	RESTService	Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.authentication.IAuthentication| name: runAsAdmin
com.tsgrp.opencontent.core.exception.OCRuntimeException: Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.authentication.IAuthentication| name: runAsAdmin
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:98) ~[oc-hpiDemoAlf.2.alfrescoEmb-2.6.jar:2.6]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at com.sun.proxy.$Proxy276.runAsAdmin(Unknown Source) ~[?:?]
	at com.tsgrp.opencontent.core.query.RESTQuery.ocAdminSearchQuery(RESTQuery.java:275) ~[oc-hpiDemoAlf.1.core-2.6.jar:2.6]
...
Caused by: java.lang.NullPointerException
	at com.tsgrp.opencontent.core.excel.ExcelUtil.generateCSV(ExcelUtil.java:897) ~[oc-hpiDemoAlf.1.core-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.query.RESTQuery$1.doWork(RESTQuery.java:288) ~[oc-hpiDemoAlf.1.core-2.6.jar:2.6]
	at com.tsgrp.opencontent.core.query.RESTQuery$1.doWork(RESTQuery.java:275) ~[oc-hpiDemoAlf.1.core-2.6.jar:2.6]
	at com.tsgrp.opencontent.alfresco.authentication.AlfrescoEmbAuthenticationImpl$1.doWork(AlfrescoEmbAuthenticationImpl.java:131) ~[oc-hpiDemoAlf.2.alfrescoEmb-2.6.jar:2.6]
	at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:555) ~[alfresco-data-model-5.1.2.jar:5.1.2]
	at com.tsgrp.opencontent.alfresco.authentication.AlfrescoEmbAuthenticationImpl.runAsAdmin(AlfrescoEmbAuthenticationImpl.java:126) ~[oc-hpiDemoAlf.2.alfrescoEmb-2.6.jar:2.6]
```

**Comment by jharkins2** [comment]
Fix: Using Apache Commons to build CSV files in ExcelUtil instead of building the files manually to take care of the NPE and other issues.
File: ExcelUtil.java
Revision #: 18757
CR-George
