### ISSUE TITLE
Viewing old version in the stage - error message appears

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1737]
On edge, if I open up View Versions on a document in the Policy trac and try to view an old version:

![image](https://user-images.githubusercontent.com/1377228/42971937-76710f48-8b73-11e8-8d6d-f9a94ac5cb9a.png)

When the version loads, this message is displayed to the user:

![image](https://user-images.githubusercontent.com/1377228/42971956-84573330-8b73-11e8-9cb8-3e6233ebf734.png)

If you click OK, it seems fine.  I'm guessing this error is coming from one of the condition checks or possibly a related object section in the stage.  

Here's the error in OC:

```
2018-07-19 16:14:27,517	http-apr-8080-exec-3	DEBUG	RESTAction	Resolving actions: viewProperties,viewVersions,viewRenditions,checkout,checkin,cancelCheckout,sendNotification,sendEmail,documentNotes,permanentRedact,startWorkflow,acquireWorkflowTask,completeTask,delegateWorkflowTask,cancelWorkflow,getDocumentLink,splitPdf,deleteDocument,downloadDocument,viewAuditEvents took: 0 seconds.
2018-07-19 16:14:27,490	http-apr-8080-exec-1	ERROR	RESTService	Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.extendedcontent.IExtendedContent| name: getRelatedParents
com.tsgrp.opencontent.core.exception.OCRuntimeException: Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.extendedcontent.IExtendedContent| name: getRelatedParents
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:98) ~[bin/:3.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.17.RELEASE.jar:3.2.17.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.17.RELEASE.jar:3.2.17.RELEASE]
	at com.sun.proxy.$Proxy369.getRelatedParents(Unknown Source) ~[?:?]
	at com.tsgrp.opencontent.core.content.RESTContent.getParentRelations(RESTContent.java:651) ~[bin/:3.1]
...
Caused by: java.lang.UnsupportedOperationException: This operation is not supported by a version store implementation of the node service.
	at org.alfresco.repo.version.NodeServiceImpl.getSourceAssocs(NodeServiceImpl.java:719) ~[alfresco-repository-5.2.3.jar:5.2.3]

```

**Comment by gsteimer** [comment]
Fix is most likely to ignore versions when retrieving association parent/children in the Alfresco Impl

**Comment by gsteimer** [comment]
Marking for 3.5.  This seems like something we should clean up as part of the next release unless it proves very difficult

**Comment by Kovacinski** [comment]
Closed with revision 27055
