### ISSUE TITLE
Enhanced Update Object event sometimes fires on working copy causing after event to fail

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1754]
Creating a form that has an autonumber assigned currently fails on edge2.  Not sure what's causing this, but the stacktrace is:

```
2018-08-17 10:17:23,784	ajp-apr-8009-exec-6	ERROR	AlfrescoEmbContentImpl	Unhandled Exception: The given objectID is not valid: workspace://SpacesStore/cbf87dc5-d177-4155-8e6c-8ee36654039b
com.tsgrp.opencontent.core.exception.OCObjectNotFoundException: The given objectID is not valid: workspace://SpacesStore/cbf87dc5-d177-4155-8e6c-8ee36654039b
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.enhancedGetProperties(AlfrescoEmbContentImpl.java:745) [oc-hpiDemoAlf.2.alfrescoEmb-3.1.jar:3.1]
	at sun.reflect.GeneratedMethodAccessor728.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) [spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) [spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice$1.execute(EmbeddedAlfrescoAdvice.java:72) [oc-hpiDemoAlf.2.alfrescoEmb-3.1.jar:3.1]
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464) [alfresco-repository-5.1.2.jar:5.1.2]
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:85) [oc-hpiDemoAlf.2.alfrescoEmb-3.1.jar:3.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) [spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at com.sun.proxy.$Proxy368.enhancedGetProperties(Unknown Source) [?:?]
	at com.tsgrp.opencontent.core.content.AbstractContentImpl.enhancedUpdateObject(AbstractContentImpl.java:145) [oc-hpiDemoAlf.1.core-3.1.jar:3.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) [spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) [spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice$1.execute(EmbeddedAlfrescoAdvice.java:72) [oc-hpiDemoAlf.2.alfrescoEmb-3.1.jar:3.1]
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464) [alfresco-repository-5.1.2.jar:5.1.2]
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:85) [oc-hpiDemoAlf.2.alfrescoEmb-3.1.jar:3.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) [spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at com.sun.proxy.$Proxy368.enhancedUpdateObject(Unknown Source) [?:?]
	at com.tsgrp.opencontent.wizard.core.Wizard2Impl.getNextAutoNumber(Wizard2Impl.java:754) [oc-hpiDemoAlf.3.wizard-3.1.jar:3.1]
```

**Comment by gsteimer** [comment]
Fixed with OC REV 19597.  CR: Ben
