### ISSUE TITLE
Engineering Project Folder Generation Fails

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1770]
Creating a new engineering project (which pulls documents from a template folder) fails on release2 with the following error:

```
Caused by: java.lang.NullPointerException
	at com.tsgrp.alfresco.content.util.dao.AlfrescoDaoUtils$1.doWork(AlfrescoDaoUtils.java:69) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.1.jar:3.1]
	at com.tsgrp.alfresco.content.util.dao.AlfrescoDaoUtils$1.doWork(AlfrescoDaoUtils.java:59) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.1.jar:3.1]
	at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:555) ~[alfresco-data-model-5.1.2.jar:5.1.2]
	at com.tsgrp.alfresco.content.util.dao.AlfrescoDaoUtils.synchronizeVersionStoreNodeProperties(AlfrescoDaoUtils.java:59) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.1.jar:3.1]
	at com.tsgrp.opencontent.alfresco.util.AlfrescoEmbUtil.updateVersionHistory(AlfrescoEmbUtil.java:512) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.1.jar:3.1]
	at com.tsgrp.opencontent.alfresco.rendition.AlfrescoEmbRenditionUtil.transformNativeContentAsTSGRendition(AlfrescoEmbRenditionUtil.java:153) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.1.jar:3.1]
	at com.tsgrp.opencontent.alfresco.rendition.AlfrescoEmbInternalRenditionImpl.generateRenditionSync(AlfrescoEmbInternalRenditionImpl.java:63) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.1.jar:3.1]
	at com.tsgrp.opencontent.alfresco.rendition.AlfrescoEmbInternalRenditionImpl.generateRendition(AlfrescoEmbInternalRenditionImpl.java:26) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.1.jar:3.1]
```

From looking at the code with @dgrumieaux I'm thinking that the problem is that the `updateVersionHistory` method needs to be nullsafe and ensure that the version actually exists when the method is fired:

```java
                    Version version = serviceRegistry.getVersionService().getCurrentVersion(nodeRef);

                    behaviourFilter.disableBehaviour(ContentModel.ASPECT_AUDITABLE);

                    adu.setPropertiesOnVersionNode(
                                        serviceRegistry,
                                        version.getFrozenStateNodeRef().getId(),
                                        serviceRegistry.getNodeService().getProperties(nodeRef),
                                        null);

                    behaviourFilter.enableBehaviour(ContentModel.ASPECT_AUDITABLE);

                    return true;

```

In the code above, both `version` and `version.getFrozenStateNodeRef()` are possible candidates for a `NullPointerException`

**Comment by gsteimer** [comment]
Fixed with OC REV 20121
