### ISSUE TITLE
Alfresco Content Stream fix causes bulk upload templates to break

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1787]
OC commit #20414 was implemented to prevent an issue where the content stream is exhausted but Alfresco's retrying transaction functionality attemps to run the method again, which produces a 0 byte file.

Unfortunately, it looks like this fix breaks Bulk Upload's create document from template functionality:

![image](https://user-images.githubusercontent.com/1377228/48782716-6b130380-eca4-11e8-8ea6-f42c4b745a26.png)

Error in OC is:

```
2018-11-20 09:02:44,547	ajp-apr-8009-exec-10	ERROR	AlfrescoEmbContentImpl	Unhandled Exception: Resetting to invalid mark
java.io.IOException: Resetting to invalid mark
	at java.io.BufferedInputStream.reset(Unknown Source) ~[?:1.8.0_65]
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl$1.execute(AlfrescoEmbContentImpl.java:483) [oc-hpiDemoAlf.2.alfrescoEmb-3.2.jar:3.2]
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl$1.execute(AlfrescoEmbContentImpl.java:425) [oc-hpiDemoAlf.2.alfrescoEmb-3.2.jar:3.2]
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464) [alfresco-repository-5.1.2.jar:5.1.2]
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.doEnhancedCreateObject(AlfrescoEmbContentImpl.java:425) [oc-hpiDemoAlf.2.alfrescoEmb-3.2.jar:3.2]
	at com.tsgrp.opencontent.core.content.AbstractContentImpl.enhancedCreateObject(AbstractContentImpl.java:87) [oc-hpiDemoAlf.1.core-3.2.jar:3.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) [spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) [spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice$1.execute(EmbeddedAlfrescoAdvice.java:72) [oc-hpiDemoAlf.2.alfrescoEmb-3.2.jar:3.2]
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464) [alfresco-repository-5.1.2.jar:5.1.2]
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:85) [oc-hpiDemoAlf.2.alfrescoEmb-3.2.jar:3.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) [spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at com.sun.proxy.$Proxy368.enhancedCreateObject(Unknown Source) [?:?]
	at com.tsgrp.opencontent.core.action.executer.AddDocumentActionExecuter.doUpload(AddDocumentActionExecuter.java:466) [oc-hpiDemoAlf.1.core-3.2.jar:3.2]
	at com.tsgrp.opencontent.core.action.executer.AddDocumentActionExecuter.executeImpl(AddDocumentActionExecuter.java:246) [oc-hpiDemoAlf.1.core-3.2.jar:3.2]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:196) [oc-hpiDemoAlf.1.core-3.2.jar:3.2]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:135) [oc-hpiDemoAlf.1.core-3.2.jar:3.2]
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475) [oc-hpiDemoAlf.1.core-3.2.jar:3.2]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeWithAttachment(RESTAction.java:722) [oc-hpiDemoAlf.1.core-3.2.jar:3.2]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPostWithAttachment(RESTAction.java:594) [oc-hpiDemoAlf.1.core-3.2.jar:3.2]
```

Not sure if these are related, but I also see these issuse

Note - this is a separate error, not in a "caused by" stack
```
2018-11-20 09:02:45,156	ajp-apr-8009-exec-10	ERROR	RESTService	Resetting to invalid mark
com.tsgrp.opencontent.core.exception.OCRuntimeException: Resetting to invalid mark
	at com.tsgrp.opencontent.core.action.executer.AddDocumentActionExecuter.doUpload(AddDocumentActionExecuter.java:468) ~[oc-hpiDemoAlf.1.core-3.2.jar:3.2]
	at com.tsgrp.opencontent.core.action.executer.AddDocumentActionExecuter.executeImpl(AddDocumentActionExecuter.java:246) ~[oc-hpiDemoAlf.1.core-3.2.jar:3.2]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:196) ~[oc-hpiDemoAlf.1.core-3.2.jar:3.2]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:135) ~[oc-hpiDemoAlf.1.core-3.2.jar:3.2]
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475) ~[oc-hpiDemoAlf.1.core-3.2.jar:3.2]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeWithAttachment(RESTAction.java:722) ~[oc-hpiDemoAlf.1.core-3.2.jar:3.2]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPostWithAttachment(RESTAction.java:594) ~[oc-hpiDemoAlf.1.core-3.2.jar:3.2]
```

and:

```
2018-11-20 09:02:45,312	ajp-apr-8009-exec-5	ERROR	RESTService	Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.content.IContent| name: deleteObjects
com.tsgrp.opencontent.core.exception.OCRuntimeException: Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.content.IContent| name: deleteObjects
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:98) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.jar:3.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at com.sun.proxy.$Proxy368.deleteObjects(Unknown Source) ~[?:?]
	at com.tsgrp.opencontent.core.content.RESTContent.deleteObjects(RESTContent.java:1860) ~[oc-hpiDemoAlf.1.core-3.2.jar:3.2]
...
Caused by: java.lang.NullPointerException
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.deleteObjects(AlfrescoEmbContentImpl.java:404) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.jar:3.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
```

**Comment by gsteimer** [comment]
Fixed with OC REV 20561
