### ISSUE TITLE
AW Merge with Word fails creating form

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1788]
Tested on both edge2 and release2 - something recently broke the AW integration with Word mail merge templating.  The create contract (Contract Management) and create letter (Claims) actions both fail creating the document with the following error:

```
2018-11-20 15:16:54,430	ajp-apr-8009-exec-9	DEBUG	AlfrescoEmbContentImpl	begin addRelation
2018-11-20 15:16:54,430	ajp-apr-8009-exec-9	ERROR	RESTService	Error generating merged document.
com.tsgrp.opencontent.core.exception.OCRuntimeException: Error generating merged document.
	at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.doPostSubmitActions(FinishAndSubmitPSIActionExecutor.java:309) ~[oc-hpiDemoAlf.3.wizard-3.2.jar:3.2]
	at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.executeImpl(FinishAndSubmitPSIActionExecutor.java:162) ~[oc-hpiDemoAlf.3.wizard-3.2.jar:3.2]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:196) ~[oc-hpiDemoAlf.1.core-3.2.jar:3.2]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:135) ~[oc-hpiDemoAlf.1.core-3.2.jar:3.2]
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475) ~[oc-hpiDemoAlf.1.core-3.2.jar:3.2]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:224) ~[oc-hpiDemoAlf.1.core-3.2.jar:3.2]
	at sun.reflect.GeneratedMethodAccessor1659.invoke(Unknown Source) ~[?:?]
...
Caused by: com.tsgrp.opencontent.core.exception.OCRuntimeException: Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.content.IContent| name: addRelation
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:98) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.jar:3.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at com.sun.proxy.$Proxy371.addRelation(Unknown Source) ~[?:?]
	at com.tsgrp.opencontent.wizard.core.WizardHelper.addWorkflowDocument(WizardHelper.java:566) ~[oc-hpiDemoAlf.3.wizard-3.2.jar:3.2]
	at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.doPostSubmitActions(FinishAndSubmitPSIActionExecutor.java:292) ~[oc-hpiDemoAlf.3.wizard-3.2.jar:3.2]
	... 49 more
Caused by: java.lang.NullPointerException
	at org.alfresco.service.cmr.repository.NodeRef.<init>(NodeRef.java:110) ~[alfresco-data-model-5.1.2.jar:5.1.2]
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.addRelation(AlfrescoEmbContentImpl.java:166) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.jar:3.2]
```

Line 166 of `AlfrescoEmbContentImpl` is the second line below:

```java
        for( String childId : req.getChildIds()) {
            NodeRef childNodeRef = new NodeRef(childId);
```

**Comment by grahamsinger** [comment]
related to #1787

**Comment by gsteimer** [comment]
Fixed with OC REV 20561
