### ISSUE TITLE
Silent error on bulk upload when creating doc from template

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1793]
When uploading a document from a template, the following error appears in the OC log, however no error is presented to the user:

```
2018-11-28 09:31:16,219	ajp-apr-8009-exec-1	DEBUG	XFDFAnnotationImpl	Found configured relation name: {http://www.tsgrp.com/model/openannotate/1.0}annotates
2018-11-28 09:31:16,219	ajp-apr-8009-exec-1	DEBUG	XFDFAnnotationImpl	Document is not annotated.
2018-11-28 09:31:37,540	ajp-apr-8009-exec-8	ERROR	RESTService	Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.content.IContent| name: deleteObjects
com.tsgrp.opencontent.core.exception.OCRuntimeException: Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.content.IContent| name: deleteObjects
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:98) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.jar:3.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at com.sun.proxy.$Proxy363.deleteObjects(Unknown Source) ~[?:?]
	at com.tsgrp.opencontent.core.content.RESTContent.deleteObjects(RESTContent.java:1860) ~[oc-hpiDemoAlf.1.core-3.2.jar:3.2]
...
Caused by: java.lang.NullPointerException
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.deleteObjects(AlfrescoEmbContentImpl.java:405) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.jar:3.2]
	at sun.reflect.GeneratedMethodAccessor1401.invoke(Unknown Source) ~[?:?]
```

My guess is that the Heads up indexer (BHUDI) is firing off a request to delete the temporary object that's used during indexing.  Templates are still not supported in the BHUDI, so if I'm correct, it would make sense if it's keeping track of the temp object ID.  OCMS is firing off this request:

```
Request URL: http://edge2.tsgrp.com/alfresco/OpenContent/content/deleteObjects
Request Method: POST
```

The code in OC fails because it expects at least one object ID parameter.  There are a few ways we can fix this issue:

1. Get Templates to work in the BHUDI
1. Make the delete request smarter by not firing off the request if there's no object IDs
1. Update the OC side to require an object ID (currently the param is optional)
1. Keep the param as optional, but make the back end code null safe.  I.e. - if there's no objectId, just return 200 and do nothing.
1. Some combination of the above options.

**Comment by gsteimer** [comment]
Closed with OCMS REV 22104 and OC REV 20651
