### ISSUE TITLE
Cannot load checkin actions on Alfresco when primary doc content is PDF

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1851]
When the primary content is PDF on Alfresco, the checkin action fails to load.  The error on the server is:

```
2019-03-20 08:14:05,162    ajp-apr-8009-exec-3    ERROR    RESTService    Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.extendedcontent.IExtendedContent| name: getAllVersions
com.tsgrp.opencontent.core.exception.OCRuntimeException: Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.extendedcontent.IExtendedContent| name: getAllVersions
    at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:98) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.jar:3.2]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
    at com.sun.proxy.$Proxy368.getAllVersions(Unknown Source) ~[?:?]
    at com.tsgrp.opencontent.core.action.executer.ViewVersionsExecuter.executeImpl(ViewVersionsExecuter.java:33) ~[oc-hpiDemoAlf.1.core-3.2.jar:3.2]
    at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:196) ~[oc-hpiDemoAlf.1.core-3.2.jar:3.2]
    at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:135) ~[oc-hpiDemoAlf.1.core-3.2.jar:3.2]
    at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475) ~[oc-hpiDemoAlf.1.core-3.2.jar:3.2]
    at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:224) ~[oc-hpiDemoAlf.1.core-3.2.jar:3.2]
...
Caused by: java.lang.NullPointerException
    at com.tsgrp.opencontent.alfresco.util.AlfrescoEmbUtil.createRenditionDataProperties(AlfrescoEmbUtil.java:618) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.jar:3.2]
    at com.tsgrp.opencontent.alfresco.util.AlfrescoEmbUtil.nodeRefToEnhancedProperties(AlfrescoEmbUtil.java:259) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.jar:3.2]
    at com.tsgrp.opencontent.alfresco.extendedcontent.AlfrescoEmbExtendedContentImpl.getAllVersions(AlfrescoEmbExtendedContentImpl.java:370) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.jar:3.2]
```

**Comment by ktrinh-tsgrp** [comment]
REVISION: 21687

AlfrescoEmbUtil: null checked createNativeDataProperties and createRenditionDataProperties because propValues can be null on some if they are a required aspect

CR: nquillin, gsteimer
