### ISSUE TITLE
Bulk Upload: Add Ability to Extract Attachments from Zips

### ISSUE THREAD

**Issue by keljopap-tsgrp** [tsgrp/HPI#1859]
When a user uploads a zip file through bulk upload, only the zip itself gets stored in the repository.  We want to be able to recursively extract all the attachments off of it the same way that we do for MSG files.

All the attachments will be associated as children of the original zip that was uploaded, and when clicking through the docs in stage you will see them appear in related objects (if configured properly).

**Comment by keljopap-tsgrp** [comment]
Has been developed on client branch and can be brought back to trunk if need be.

**Comment by gsteimer** [comment]
@keljopap-tsgrp @benallenallen - This should be trunk. Wasn't this developed trunk first?

**Comment by benallenallen** [comment]
@dhruvvora94 will be taking this over - it was developed trunk first, just needs to get CRed and merged in like a normal branch would be.

**Comment by gsteimer** [comment]
👍 thx!

**Comment by IanCMcKee66** [comment]
OCMS 
EXTRACTING ATTACHMENTS OFF ZIPS - adding in the functionality in bulkupload.js to parse zip files for attachments and nested attachments when being uploaded.

Revision- #23106

CR - skovacinski, rsaladrigas
_____________________________________________________________________________________________

**Comment by gsteimer** [comment]
@IanCMcKee66 @benallenallen seems like this is not working on edge2.  I just tried it and it failed on the document upload.  Error in OC was:

```
2019-06-19 14:15:53,423	ajp-apr-8009-exec-15	ERROR	AlfrescoEmbRenditionUtil	Transformer incapable of transforming content from application/x-zip-compressed to application/pdf.
2019-06-19 14:15:54,595	ajp-apr-8009-exec-15	ERROR	RESTService	Error creating zip object and attachments.
com.tsgrp.opencontent.core.exception.OCRuntimeException: Error creating zip object and attachments.
	at com.tsgrp.opencontent.core.action.executer.AddDocumentActionExecuter.createZipAttachments(AddDocumentActionExecuter.java:1033) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.executer.AddDocumentActionExecuter.doUpload(AddDocumentActionExecuter.java:537) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.executer.AddDocumentActionExecuter.executeImpl(AddDocumentActionExecuter.java:265) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:224) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:154) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeWithAttachment(RESTAction.java:718) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPostWithAttachment(RESTAction.java:594) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
...
Caused by: com.tsgrp.opencontent.core.exception.OCRuntimeException: Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.content.IContent| name: addRelation
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:98) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.0.jar:3.2.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at com.sun.proxy.$Proxy367.addRelation(Unknown Source) ~[?:?]
	at com.tsgrp.opencontent.core.util.ZipUtil.relateAttachmentsToZip(ZipUtil.java:67) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.executer.AddDocumentActionExecuter.createZipAttachments(AddDocumentActionExecuter.java:1014) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	... 55 more
Caused by: java.lang.IllegalArgumentException: Association {}hpi_related has not been defined in the data dictionary
	at org.alfresco.repo.policy.AssociationPolicyDelegate.checkAssocType(AssociationPolicyDelegate.java:90) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at org.alfresco.repo.policy.AssociationPolicyDelegate.get(AssociationPolicyDelegate.java:176) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at org.alfresco.repo.node.AbstractNodeServiceImpl.invokeOnCreateAssociation(AbstractNodeServiceImpl.java:694) ~[alfresco-repository-5.1.2.jar:5.1.2]
```

**Comment by gsteimer** [comment]
Closing - the above issue was due to an incorrect configuration in the admin
