### ISSUE TITLE
Bulk Upload - Heads up indexer MSG with attachments fails on Documentum

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1870]
When dragging in an MSG file to bulk upload, the files are pulled off correctly, but the bulk properties page fails to load with the following error:

![image](https://user-images.githubusercontent.com/1377228/55804013-22b48080-5aa1-11e9-8a61-704316f91c4a.png)

The error on the OC side is:

```
2019-04-09 08:26:51,689	TP-Processor1	ERROR	DCTMContentImpl	Error creating documentum object: DfSysObjectException:: THREAD: TP-Processor1; MSG: [DM_SYSOBJECT_E_NO_CONTENT_TYPE]error:  "No content type specified for 1554816818910-2-2013 Financials.pdf sysobject."; ERRORCODE: 100; NEXT: null
com.documentum.fc.client.DfSysObjectException: [DM_SYSOBJECT_E_NO_CONTENT_TYPE]error:  "No content type specified for 1554816818910-2-2013 Financials.pdf sysobject."
	at com.documentum.fc.client.DfSysObjectException.newNoContentTypeSpecifiedException(DfSysObjectException.java:40) ~[dfc-7.1.jar:?]
	at com.documentum.fc.client.content.impl.FormatSpecification.verifyFormatSpecified(FormatSpecification.java:22) ~[dfc-7.1.jar:?]
	at com.documentum.fc.client.content.impl.FormatSpecification.<init>(FormatSpecification.java:15) ~[dfc-7.1.jar:?]
	at com.documentum.fc.client.content.impl.ContentManager.makeContentInternal(ContentManager.java:507) ~[dfc-7.1.jar:?]
	at com.documentum.fc.client.content.impl.ContentManager.verifySetContentandLink(ContentManager.java:493) ~[dfc-7.1.jar:?]
	at com.documentum.fc.client.content.impl.ContentManager.setStream(ContentManager.java:282) ~[dfc-7.1.jar:?]
	at com.documentum.fc.client.DfSysObject.doSetContent(DfSysObject.java:2022) ~[dfc-7.1.jar:?]
	at com.documentum.fc.client.DfSysObject.setContentEx2(DfSysObject.java:2004) ~[dfc-7.1.jar:?]
	at com.documentum.fc.client.DfSysObject.setContentEx(DfSysObject.java:1998) ~[dfc-7.1.jar:?]
	at com.documentum.fc.client.DfSysObject.setContent(DfSysObject.java:1993) ~[dfc-7.1.jar:?]
	at com.documentum.fc.client.DfDocument___PROXY.setContent(DfDocument___PROXY.java) ~[?:?]
	at com.tsgrp.opencontent.dctm.content.DCTMContentImpl.doEnhancedCreateObject(DCTMContentImpl.java:1263) [oc-hpiDemoDctm.2.dctm-3.2.jar:3.2]
	at com.tsgrp.opencontent.core.content.AbstractContentImpl.enhancedCreateObject(AbstractContentImpl.java:96) [oc-hpiDemoDctm.1.core-3.2.jar:3.2]
	at com.tsgrp.opencontent.core.content.RESTContent.upload(RESTContent.java:1384) [oc-hpiDemoDctm.1.core-3.2.jar:3.2]
...
	at com.tsgrp.opencontent.core.content.RESTContent.upload(RESTContent.java:1386) [oc-hpiDemoDctm.1.core-3.2.jar:3.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]


```

Given that the file it's failing on is `1554816818910-2-2013 Financials.pdf`, this appears to be happening when it's trying to send the content of the attachments to the repo for the heads up indexer.

**Comment by gsteimer** [comment]
Something to look into - when the email code pulls off the attachments, does it set the mime type on the OCO?  If it's not setting it, it would cause this error.

**Comment by ktrinh-tsgrp** [comment]
Fixed with OC revision 22082:

``
RESTContent: ECO will try to use extension map mimetypes before it uses the multipart file mimetype

CR: gsteimer, skovacinski``
