### ISSUE TITLE
Alfresco consumer users cannot get properties of checked out controlled document

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1885]
When a controlled document is checked out, consumer users cannot get properties, even though the user can find the document in search results.  For example:

![image](https://user-images.githubusercontent.com/1377228/57383551-9fa44a00-7174-11e9-85eb-dca56c9a82bf.png)

Retrieving properties of `TSG-117` above throws the following error:

```
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.enhancedGetProperties(AlfrescoEmbContentImpl.java:817)
	at sun.reflect.GeneratedMethodAccessor762.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice$1.execute(EmbeddedAlfrescoAdvice.java:72)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464)
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:85)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy366.enhancedGetProperties(Unknown Source)
	at com.tsgrp.opencontent.universal.action.executer.ExportSearchResultsActionExecuter.executeImpl(ExportSearchResultsActionExecuter.java:71)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:196)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:135)
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475)
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionAndStreamFile(RESTAction.java:392)
```
This affects any action that retrieves document properties.  For example, Get Properties as well as Export Search Results to Excel.  I'm guessing we haven't seen this in the past since consumer users can only see Approved and Effective content, these documents are rarely checked out, and when they are they're not checked out for long).  

The line that is failing is the last line here:

``` java
NodeRef workingCopy = AlfrescoEmbUtil.getWorkingCopy(serviceRegistry, nodeRef);
if(workingCopy != null ){
	//get the originalProps
	originalProps = serviceRegistry.getNodeService().getProperties( nodeRef );
	nodeRef = workingCopy;
}

Map<QName, Serializable> nodeProps = serviceRegistry.getNodeService().getProperties( nodeRef );
```

Since the user can get properties of an un-checked out document, I'm guessing the issue is with the permissions that are applied to the working copy.

**Comment by nquillin91** [comment]
When a user doesn't have access to the checked out document's working copy properties it will default back to retrieving the properties for the original version they do have access to.

Fixed with OC REV: 22560
