### ISSUE TITLE
Export Search Results to PDF - Fails on Alfresco

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1891]
The export search results to PDF action fails on edge2.  It's currently configured on the Wizard search results on both edge1 and edge2.  Edge1 seems fine, but edge 2 fails with the following errors:

```
(Tons of these 'Ignoring null property...' lines above here)
...
2019-05-24 08:30:11,262	ajp-apr-8009-exec-7	DEBUG	AlfrescoEmbUtil	Ignoring null property...
2019-05-24 08:30:11,262	ajp-apr-8009-exec-7	DEBUG	AlfrescoEmbUtil	Ignoring null property...
2019-05-24 08:30:11,278	ajp-apr-8009-exec-7	DEBUG	AlfrescoEmbUtil	Ignoring null property...
2019-05-24 08:30:11,278	ajp-apr-8009-exec-7	DEBUG	AlfrescoEmbUtil	Ignoring null property...
2019-05-24 08:30:11,309	ajp-apr-8009-exec-7	DEBUG	AlfrescoEmbUtil	Ignoring null property...
2019-05-24 08:30:11,309	ajp-apr-8009-exec-7	DEBUG	AlfrescoEmbUtil	Ignoring null property...
2019-05-24 08:30:11,341	ajp-apr-8009-exec-7	ERROR	FreeMarkerTemplateImpl	Error processing Template
freemarker.core.ParseException: Parsing error in template "export-search-results-pdf-template.ftl" in line 19, column 44:
Unknown built-in: "counter". Help (latest version): http://freemarker.org/docs/ref_builtins.html; you're using FreeMarker 2.3.20.
The alphabetical list of built-ins:
abs, ancestors, 
byte, 
c, cap_first, capitalize, ceiling, children, chop_linebreak, chunk, contains, 
date, datetime, default, double, 
ends_with, eval, exists, 
first, float, floor, 
groups, 
has_content, html, 
if_exists, index_of, int, interpret, is_boolean, is_collection, is_date, is_directive, is_enumerable, is_hash, is_hash_ex, is_indexable, is_infinite, is_macro, is_method, is_nan, is_node, is_number, is_sequence, is_string, is_transform, iso, iso_h, iso_h_nz, iso_local, iso_local_h, iso_local_h_nz, iso_local_m, iso_local_m_nz, iso_local_ms, iso_local_ms_nz, iso_local_nz, iso_m, iso_m_nz, iso_ms, iso_ms_nz, iso_nz, iso_utc, iso_utc_h, iso_utc_h_nz, iso_utc_m, iso_utc_m_nz, iso_utc_ms, iso_utc_ms_nz, iso_utc_nz, 
j_string, join, js_string, json_string, 
keys, 
last, last_index_of, left_pad, length, long, lower_case, 
matches, 
namespace, new, node_name, node_namespace, node_type, number, number_to_date, number_to_datetime, number_to_time, 
parent, 
replace, reverse, right_pad, root, round, rtf, 
seq_contains, seq_index_of, seq_last_index_of, short, size, sort, sort_by, split, starts_with, string, substring, 
time, trim, 
uncap_first, upper_case, url, 
values, 
web_safe, word_list, 
xhtml, xml
	at freemarker.core.BuiltIn.newBuiltIn(BuiltIn.java:308) ~[freemarker-2.3.20-alfresco-patched.jar:2.3.20]
	at freemarker.core.FMParser.BuiltIn(FMParser.java:807) ~[freemarker-2.3.20-alfresco-patched.jar:2.3.20]
...
	at com.tsgrp.opencontent.core.template.FreeMarkerTemplateImpl.applyTemplate(FreeMarkerTemplateImpl.java:36) [oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.executer.ExportSearchResultsToPDFActionExecuter.generatePDFWithFTL(ExportSearchResultsToPDFActionExecuter.java:191) [oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.executer.ExportSearchResultsToPDFActionExecuter.executeImpl(ExportSearchResultsToPDFActionExecuter.java:96) [oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:196) [oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:135) [oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475) [oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionAndStreamFile(RESTAction.java:392) [oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
...
2019-05-24 08:30:11,450	ajp-apr-8009-exec-7	ERROR	RESTService	Error generating PDF rendition of Controlled Print Audit
com.tsgrp.opencontent.core.exception.OCRuntimeException: Error generating PDF rendition of Controlled Print Audit
	at com.tsgrp.opencontent.core.action.executer.ExportSearchResultsToPDFActionExecuter.generatePDFWithFTL(ExportSearchResultsToPDFActionExecuter.java:210) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.executer.ExportSearchResultsToPDFActionExecuter.executeImpl(ExportSearchResultsToPDFActionExecuter.java:96) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:196) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:135) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionAndStreamFile(RESTAction.java:392) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
...
Caused by: com.itextpdf.text.ExceptionConverter: The document has no pages.
Caused by: java.io.IOException: The document has no pages.
	at com.itextpdf.text.pdf.PdfPages.writePageTree(PdfPages.java:113) ~[itextpdf-5.5.4.1-TSG.jar:5.5.4]
	at com.itextpdf.text.pdf.PdfWriter.close(PdfWriter.java:1269) ~[itextpdf-5.5.4.1-TSG.jar:5.5.4]
```

**Comment by jackjbridge** [comment]
EXPORT SEARCH RESULTS TO PDF: Updating export-search-results-pdf-template freemarker template to no longer use the counter variable. The "counter" variable requires at least freemarker template jar 2.3.23 or above. The alfresco freemarker template jar is only up to version 2.3.20. If alfresco updates their jar, this can be added back in. This code will work in non-alfresco environments.

SVN#: 22445

CR: aking, gsteimer

**Comment by jlittle-tsg** [comment]
As the above says, this action is still not able to be run on alfresco environments. Getting the following stacktrace when running: 
`[2020-03-24 13:53:29,061|ERROR|FreeMarkerTemplateImpl|applyTemplate|46] Error processing Template
freemarker.core.ParseException: Parsing error in template "export-search-results-pdf-template.ftl" in line 48, column 18:
Unknown directive: #outputformat. Help (latest version): http://freemarker.org/docs/ref_directive_alphaidx.html; you're using FreeMarker 2.3.20.
        at freemarker.core.TokenMgrError.toParseException(TokenMgrError.java:233)
        at freemarker.template.Template.<init>(Template.java:199)
        at freemarker.cache.TemplateCache.loadTemplate(TemplateCache.java:419)
        at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:330)
        at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:205)
        at freemarker.template.Configuration.getTemplate(Configuration.java:740)
        at freemarker.template.Configuration.getTemplate(Configuration.java:665)
        at com.tsgrp.opencontent.core.template.FreeMarkerTemplateImpl.applyTemplate(FreeMarkerTemplateImpl.java:36)
        at com.tsgrp.opencontent.core.action.executer.ExportSearchResultsToPDFActionExecuter.generatePDFWithFTL(ExportSearchResultsToPDFActionExecuter.java:193)
        at com.tsgrp.opencontent.core.action.executer.ExportSearchResultsToPDFActionExecuter.executeImpl(ExportSearchResultsToPDFActionExecuter.java:98)
        at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.executeImpl(AbstractActionExecuter.java:239)
        at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:226)
        at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:156)
        at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475)
        at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionAndStreamFile(RESTAction.java:392)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:743)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:672)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:82)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:855)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at com.tsgrp.opencontent.rest.filter.OCTimingFilter.doFilterInternal(OCTimingFilter.java:83)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.alfresco.module.aosmodule.service.ContextRootFilter.doFilter(ContextRootFilter.java:93)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2466)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2455)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Unknown Source)`

**Comment by jlittle-tsg** [comment]
Fixed with OC Commit 24964
