### ISSUE TITLE
Export search results to Excel fails for consumer user when controlled document is checked out

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1901]
Found by STS.  Export search results fails for the `jconsumer` user on the Controlled Docs trac when one or more of the documents selected are checked out.

The error in OC is:

```
2019-06-12 07:42:34,915	ajp-apr-8009-exec-1	DEBUG	ExportSearchResultsActionExecuter	ExportSearchResultsActionExecuter#executeImpl - starting.
2019-06-12 07:42:34,915	ajp-apr-8009-exec-1	DEBUG	ExportSearchResultsActionExecuter	ExportSearchResultsActionExecuter#createExcelWorkbookForDownload - starting.
2019-06-12 07:42:34,978	ajp-apr-8009-exec-1	ERROR	AlfrescoEmbContentImpl	Unhandled Exception: 05120114 Access Denied.  You do not have the appropriate permissions to perform this operation.
org.alfresco.repo.security.permissions.AccessDeniedException: 05120114 Access Denied.  You do not have the appropriate permissions to perform this operation.
	at
... com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.enhancedGetProperties(AlfrescoEmbContentImpl.java:817) [oc-hpiDemoAlf.2.alfrescoEmb-3.2.0.jar:3.2.0]
...
	at com.tsgrp.opencontent.universal.action.executer.ExportSearchResultsActionExecuter.createExcelWorkbookForDownload(ExportSearchResultsActionExecuter.java:84) [oc-hpiDemoAlf.3.universal-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.universal.action.executer.ExportSearchResultsActionExecuter.executeImpl(ExportSearchResultsActionExecuter.java:61) [oc-hpiDemoAlf.3.universal-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:224) [oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:154) [oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475) [oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionAndStreamFile(RESTAction.java:392) [oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
...
Caused by: net.sf.acegisecurity.AccessDeniedException: Access is denied.
	at net.sf.acegisecurity.vote.AffirmativeBased.decide(AffirmativeBased.java:86) ~[acegi-security-0.8.2_patched.jar:?]
	at net.sf.acegisecurity.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:398) ~[acegi-security-0.8.2_patched.jar:?]

```
Based on the error, I'm guessing the problem is that the user has access to the `Effective` version that is showing up as locked, but the user does _not_ have access to the working copy.

My initial thought is that in this case, if the user doesn't have access to the working copy, we should fall back to the primary node and get properties from there.  If the user (for some odd reason), doesn't have access to _that_ node as well, we display something in the row that says something like "Access denied for object {objectId or name if available}"

Note - if this is more than a simple fix, we can bump down the priority of this one.  Consumer users really shouldn't ever be able to see checked out controlled documents since the window in which they're checked out is typically very small.  I did verify that a non-admin user who is a doc editor _can_ export search results when it includes a checked out document.

**Comment by gsteimer** [comment]
Also related to #1885

**Comment by nquillin91** [comment]
When a user doesn't have access to the checked out document's working copy properties it will default back to retrieving the properties for the original version they do have access to.

Fixed with OC REV: 22560
