### ISSUE TITLE
TSGEncrypter not working in RESTAuthentication in Alfresco 6

### ISSUE THREAD

**Issue by dgrumieaux** [tsgrp/HPI#1905]
```
Caused by: java.lang.NoClassDefFoundError: sun/misc/BASE64Decoder
        at com.tsgrp.util.TsgEncrypter.decrypt(TsgEncrypter.java:171) ~[tsgrp-1.5.4.jar:1.5.4]
        at com.tsgrp.opencontent.core.authentication.RESTAuthentication.newSession(RESTAuthentication.java:119) ~[1.core-3.2.0.jar:3.2.0]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[spring-web-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) ~[spring-web-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) ~[spring-webmvc-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) [spring-webmvc-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        ... 45 more
Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Decoder
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1309) ~[catalina.jar:8.5.34]
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1137) ~[catalina.jar:8.5.34]
        at com.tsgrp.util.TsgEncrypter.decrypt(TsgEncrypter.java:171) ~[tsgrp-1.5.4.jar:1.5.4]
        at com.tsgrp.opencontent.core.authentication.RESTAuthentication.newSession(RESTAuthentication.java:119) ~[1.core-3.2.0.jar:3.2.0]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[spring-web-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) ~[spring-web-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) ~[spring-webmvc-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) [spring-webmvc-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        ... 45 more
```

**Comment by dgrumieaux** [comment]
Note this affects Alfresco 6.1 PSA tool

**Comment by gsteimer** [comment]
Most likely related to the version of java that Alfresco is using.  Perhaps we recompile the `tsgrp.jar` using an apache util for base64 encoding?

**Comment by dgrumieaux** [comment]
Now that the `tsgrp.jar` has been updated to 2.0, this is confirmed to no longer be an issue. Closing.
