### ISSUE TITLE
Download related objects to zip - does not work on Documentum

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1916]
The download related objects to zip action does not work on edge1 (Documentum).  It does work on edge2 (Alfresco).  

Error in OC is:

```
2019-06-27 13:36:06,475	ajp-nio-9009-exec-14	ERROR	CoreActionService	Failed evaluating action condition: condition-read-conditionevaluator. Marking as invalid.
com.tsgrp.opencontent.core.exception.OCRuntimeException: [DM_API_E_BADID]error:  "Bad ID given: 090000028000a191~|~Workflow Documents"
	at com.tsgrp.opencontent.dctm.core.permission.DCTMPermissionImpl.checkPermissions(DCTMPermissionImpl.java:144) ~[oc-hpiDemoDctm.2.dctm-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.dctm.core.permission.DCTMPermissionImpl.canRead(DCTMPermissionImpl.java:53) ~[oc-hpiDemoDctm.2.dctm-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.condition.evaluator.PermissionConditionEvaluator.evaluateImpl(PermissionConditionEvaluator.java:70) ~[oc-hpiDemoDctm.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.condition.evaluator.AbstractConditionEvaluator.evaluate(AbstractConditionEvaluator.java:68) ~[oc-hpiDemoDctm.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.service.CoreActionService.evaluateAndGetCondition(CoreActionService.java:226) [oc-hpiDemoDctm.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.service.CoreActionService.evaluateAction(CoreActionService.java:142) [oc-hpiDemoDctm.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.service.CoreActionService.evaluateAction(CoreActionService.java:194) [oc-hpiDemoDctm.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateConditions(AbstractActionExecuter.java:239) [oc-hpiDemoDctm.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:143) [oc-hpiDemoDctm.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475) [oc-hpiDemoDctm.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionAndStreamFile(RESTAction.java:392) [oc-hpiDemoDctm.1.core-3.2.0.jar:3.2.0]

```

The `DownloadAsZipActionExecuter` _does_ work on edge1 in the Export Folder action.

**Comment by gsteimer** [comment]
Not for certain, but I'm guessing this would be a problem on Hbase as well

**Comment by grahamsinger** [comment]
Fixed with OC rev22762 and OCMS rev23197.
