### ISSUE TITLE
Recent updates in AbstractContentImpl causing issues in Alfresco

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1969]
A commit went in yesterday that's causing all admin config saves to fail with the following error:

```
2019-10-10 10:00:15,567	ajp-apr-8009-exec-3	ERROR	RESTService	Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.content.IContent| name: enhancedUpdateObject
com.tsgrp.opencontent.core.exception.OCRuntimeException: Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.content.IContent| name: enhancedUpdateObject
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:98) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.0.jar:3.2.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at com.sun.proxy.$Proxy461.enhancedUpdateObject(Unknown Source) ~[?:?]
	at com.tsgrp.opencontent.core.preferences.GenericPreferencesService.updatePreferencesByName(GenericPreferencesService.java:254) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.userpreferences.persistence.RESTUserPreferencesService.saveUserPreference(RESTUserPreferencesService.java:150) ~[oc-hpiDemoAlf.3.hpi-3.2.0.jar:3.2.0]
...
Caused by: java.lang.NullPointerException
	at com.tsgrp.opencontent.core.util.OCUtil.enhancedCompleteObjectToOpenContentObject(OCUtil.java:626) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.content.AbstractContentImpl.enhancedUpdateObject(AbstractContentImpl.java:200) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
```

From talking to @benallenallen, it seems that this error is caused since:

1. Alfresco has OC events wired up for Chain Versionable
1. The admin versions content, but doesn't try to update properties
1. The current code blindly expects that properties exist on the ECO

Talk to @benallenallen first to figure out how to fix this.  We have two options - fix the ECO to OCO method to handle this case (null props), or update the code in `AbstractContentImpl` that was added to not call the method if properties are `null`.

**Comment by egrahamtsg** [comment]
OC commit #23435 should fix this issue

**Comment by gsteimer** [comment]
@egrahamtsg @benallenallen - this is cropping up again.  We cannot create an autonumbered form on edge2.  Error is:

```
2019-10-10 11:46:32,933    ajp-apr-8009-exec-5    ERROR    EmbeddedAlfrescoAdvice    An unspecified OC exception occurred
com.tsgrp.opencontent.core.exception.OCRuntimeException: java.lang.NullPointerException
    at org.alfresco.service.cmr.repository.NodeRef.<init>(NodeRef.java:110)
    at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.enhancedGetProperties(AlfrescoEmbContentImpl.java:799)
    at sun.reflect.GeneratedMethodAccessor745.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice$1.execute(EmbeddedAlfrescoAdvice.java:72)
    at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464)
    at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:85)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy462.enhancedGetProperties(Unknown Source)
    at com.tsgrp.opencontent.core.util.OCUtil.getUpdatedPropertiesMap(OCUtil.java:1910)
    at com.tsgrp.opencontent.core.content.AbstractContentImpl.addUpdatedPropertiesMapToParams(AbstractContentImpl.java:286)
    at com.tsgrp.opencontent.core.content.AbstractContentImpl.enhancedUpdateObject(AbstractContentImpl.java:202)
```

**Comment by gsteimer** [comment]
Fixed in OC REV 23440
