### ISSUE TITLE
Cannot edit existing form on Alfresco

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1971]
The issue I saw with Copy Form (see #1962) seems to actually be happening on all AW forms.  The error in the log is:

```
2019-10-11 15:57:13,348	ajp-apr-8009-exec-2	ERROR	RESTService	Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.content.IContent| name: enhancedUpdateObject
com.tsgrp.opencontent.core.exception.OCRuntimeException: Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.content.IContent| name: enhancedUpdateObject
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:98) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.0.jar:3.2.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at com.sun.proxy.$Proxy461.enhancedUpdateObject(Unknown Source) ~[?:?]
	at com.tsgrp.opencontent.wizard.core.Wizard2Impl.savePageSetInstance(Wizard2Impl.java:678) ~[oc-hpiDemoAlf.3.wizard-3.2.0.jar:3.2.0]
...
Caused by: org.springframework.dao.ConcurrencyFailureException: Unexpected: current version does not appear to be 1st version in the list  [workspace://version2Store/5a9af291-4e60-483b-9d2e-754e14bedda9, workspace://SpacesStore/e2f7b1a0-07f6-44d0-86cc-7e6b002d0fe3]
	at org.alfresco.repo.version.Version2ServiceImpl.getCurrentVersionImpl(Version2ServiceImpl.java:891) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at org.alfresco.repo.version.Version2ServiceImpl.getCurrentVersion_aroundBody8(Version2ServiceImpl.java:432) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at org.alfresco.repo.version.Version2ServiceImpl$AjcClosure9.run(Version2ServiceImpl.java:1) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.2.jar:?]
	at org.alfresco.traitextender.RouteExtensions.intercept(RouteExtensions.java:100) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at org.alfresco.repo.version.Version2ServiceImpl.getCurrentVersion(Version2ServiceImpl.java:416) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at sun.reflect.GeneratedMethodAccessor1099.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.alfresco.repo.security.permissions.impl.AlwaysProceedMethodInterceptor.invoke(AlwaysProceedMethodInterceptor.java:41) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.alfresco.repo.security.permissions.impl.ExceptionTranslatorMethodInterceptor.invoke(ExceptionTranslatorMethodInterceptor.java:53) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.alfresco.repo.audit.AuditMethodInterceptor.proceedWithAudit(AuditMethodInterceptor.java:256) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at org.alfresco.repo.audit.AuditMethodInterceptor.proceed(AuditMethodInterceptor.java:216) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at org.alfresco.repo.audit.AuditMethodInterceptor.invoke(AuditMethodInterceptor.java:171) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) ~[spring-tx-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) ~[spring-tx-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.14.RELEASE.jar:3.2.14.RELEASE]
	at com.sun.proxy.$Proxy184.getCurrentVersion(Unknown Source) ~[?:?]
	at com.tsgrp.alfresco.content.util.dao.AlfrescoDaoUtils$1.doWork(AlfrescoDaoUtils.java:63) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.0.jar:3.2.0]
	at com.tsgrp.alfresco.content.util.dao.AlfrescoDaoUtils$1.doWork(AlfrescoDaoUtils.java:59) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.0.jar:3.2.0]
	at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:555) ~[alfresco-data-model-5.1.2.jar:5.1.2]
	at com.tsgrp.alfresco.content.util.dao.AlfrescoDaoUtils.synchronizeVersionStoreNodeProperties(AlfrescoDaoUtils.java:59) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.alfresco.util.AlfrescoEmbUtil.updateVersionHistory(AlfrescoEmbUtil.java:510) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.alfresco.event.events.AlfrescoVersionHistoryUpdateEvent.onUpdateObject(AlfrescoVersionHistoryUpdateEvent.java:35) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.event.OCPolicyComponentImpl.executeAfterUpdateObjectEvents(OCPolicyComponentImpl.java:174) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.core.content.AbstractContentImpl.enhancedUpdateObject(AbstractContentImpl.java:220) ~[oc-hpiDemoAlf.1.core-3.2.0.jar:3.2.0]
```

**Comment by egrahamtsg** [comment]
fixed with commit #23484 - injectable defaulted to false to control whether or not to create an updated props map

**Comment by cheinz-tsg** [comment]
Broken again with OC Commit #24780

**Comment by cheinz-tsg** [comment]
Opened new issue (https://github.com/tsgrp/HPI/issues/2087) rather than re-opening this one.
