### ISSUE TITLE
Cannot complete task for form with Workflow Document Attached

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2021]
From edge2, I cannot approve a task for a wizard form that has attached workflow documents.  The only error I'm seeing in the logs is:

```
2019-12-19 16:12:45,358	52693655	ajp-apr-8009-exec-9	ERROR	RESTService	One or more conditions for completeWizardApprovalRoute was invaild: The conditions didn't all pass for the action: completeWizardApprovalRoute
com.tsgrp.opencontent.core.exception.OCRuntimeException: One or more conditions for completeWizardApprovalRoute was invaild: The conditions didn't all pass for the action: completeWizardApprovalRoute
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:479)
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:224)
	at sun.reflect.GeneratedMethodAccessor1854.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)

```

**Comment by gsteimer** [comment]
Actual issue in OC is:

```
2020-01-02 11:39:58,672	36296435	ajp-apr-8009-exec-8	ERROR	TSGAbstractAppendSignaturePageImpl	Failed to create signature page
java.lang.NullPointerException
	at com.tsgrp.opencontent.wizard.core.esig.TSGAbstractAppendSignaturePageImpl.getValue(TSGAbstractAppendSignaturePageImpl.java:666)
	at com.tsgrp.opencontent.wizard.core.esig.TSGAbstractAppendSignaturePageImpl.resolveTokensSimple(TSGAbstractAppendSignaturePageImpl.java:598)
	at com.tsgrp.opencontent.wizard.core.esig.TSGAbstractAppendSignaturePageImpl.createSignaturePage(TSGAbstractAppendSignaturePageImpl.java:457)
	at com.tsgrp.opencontent.wizard.core.esig.TSGAbstractAppendSignaturePageImpl.appendSignaturePages(TSGAbstractAppendSignaturePageImpl.java:405)
	at com.tsgrp.opencontent.wizard.activiti.workflow.listener.CompleteUserTaskListener.notify(CompleteUserTaskListener.java:167)
```

**Comment by gsteimer** [comment]
Fixed with OC Rev 24209
CR: dgrumieaux
