### ISSUE TITLE
Logout does not work properly for Tomcat 8.5.38

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2023]
On both edge1 and edge3, logout is not correctly logging the user out.  It fails with the following error:

```
2019-12-20 11:26:08,087	ajp-nio-9009-exec-3	ERROR	RESTService	An invalid character [32] was present in the Cookie value
java.lang.IllegalArgumentException: An invalid character [32] was present in the Cookie value
	at org.apache.tomcat.util.http.Rfc6265CookieProcessor.validateCookieValue(Rfc6265CookieProcessor.java:182) ~[tomcat-coyote.jar:8.5.38]
	at org.apache.tomcat.util.http.Rfc6265CookieProcessor.generateHeader(Rfc6265CookieProcessor.java:115) ~[tomcat-coyote.jar:8.5.38]
	at org.apache.catalina.connector.Response.generateCookieString(Response.java:986) ~[catalina.jar:8.5.38]
	at org.apache.catalina.connector.Response.addCookie(Response.java:934) ~[catalina.jar:8.5.38]
	at org.apache.catalina.connector.ResponseFacade.addCookie(ResponseFacade.java:386) ~[catalina.jar:8.5.38]
	at com.tsgrp.opencontent.core.authentication.RESTAuthentication.setTicketCookie(RESTAuthentication.java:308) ~[oc-hpiDemoDctm.1.core-3.3.0.jar:3.3.0]
	at com.tsgrp.opencontent.core.authentication.RESTAuthentication.endSession(RESTAuthentication.java:234) ~[oc-hpiDemoDctm.1.core-3.3.0.jar:3.3.0]
```

From talking to @Kovacinski it appears that this is an issue with the version of Tomcat that edge1/3 are using (8.5.38).  It works on edge2 since the Alfresco Tomcat _is_ compatible with the recent changes around `app.ticket`.  We will need to find a fix that is compatible with both (and ideally Tomcat 9 as well).

**Comment by Kovacinski** [comment]
Fixed with revision 24200
