### ISSUE TITLE
Route for Review to Group does not work on Alfresco

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2029]
The new Route for Review to Group functionality added for a Documentum client does not work currently in Alfresco.  After fixing #2024 and testing the group-based functionality on Alfresco, I now see the subgroups of wizard contribs:

![image](https://user-images.githubusercontent.com/1377228/71831334-4cb9c400-306e-11ea-8274-314bef30eb2e.png)

However, when starting the route using the "user-based" option (where it just loops through the users in the group, and gives them each a review task), the route immediately finishes.  No tasks are sent out, and I actually get an email saying that the review route is finished.  The error in OC is:

```
2020-01-06 10:15:31,044	7754171	ajp-apr-8009-exec-10	DEBUG	AlfrescoDaoUtils	Updated node: workspace://version2Store/1d333440-e600-45dd-8cb0-be50b1406f6d
2020-01-06 10:15:31,044	7754171	ajp-apr-8009-exec-10	DEBUG	PrepareWizardReviewServiceTask	Error auditing event in PrepareWizardReviewServiceTask: 
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at com.tsgrp.opencontent.wizard.activiti.workflow.listener.PrepareWizardReviewServiceTask.execute(PrepareWizardReviewServiceTask.java:151)

...
	at com.tsgrp.opencontent.activiti.workflow.ActivitiWorkflowImpl.startWorkflow(ActivitiWorkflowImpl.java:595)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice$1.execute(EmbeddedAlfrescoAdvice.java:72)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464)
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:85)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy459.startWorkflow(Unknown Source)
	at com.tsgrp.opencontent.wizard.action.executer.StartWizardReviewWorkflowActionExecuter.executeImpl(StartWizardReviewWorkflowActionExecuter.java:88)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.executeImpl(AbstractActionExecuter.java:239)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:226)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:156)
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475)
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:224)

```

If I try this same thing, but use a group-based task, where one user from the group needs to sign off on the review task, I get a 500 error and the route does not start.  The error in OC is:

```
2020-01-06 10:17:29,922	7873049	ajp-apr-8009-exec-2	ERROR	EmbeddedAlfrescoAdvice	An unspecified OC exception occurred
com.tsgrp.opencontent.core.exception.OCRuntimeException: Could not start workflow.
	at com.tsgrp.opencontent.activiti.workflow.ActivitiWorkflowImpl.startWorkflow(ActivitiWorkflowImpl.java:598)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice$1.execute(EmbeddedAlfrescoAdvice.java:72)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464)
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:85)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy459.startWorkflow(Unknown Source)
	at com.tsgrp.opencontent.wizard.action.executer.StartWizardReviewWorkflowActionExecuter.executeImpl(StartWizardReviewWorkflowActionExecuter.java:88)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.executeImpl(AbstractActionExecuter.java:239)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:226)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:156)
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475)
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:224)

...
Caused by: org.activiti.engine.ActivitiException: Exception while invoking TaskListener: 0
	at org.activiti.engine.impl.bpmn.helper.ClassDelegate.notify(ClassDelegate.java:123)
	at org.activiti.engine.impl.delegate.TaskListenerInvocation.invoke(TaskListenerInvocation.java:34)
	at org.activiti.engine.impl.delegate.DelegateInvocation.proceed(DelegateInvocation.java:37)
	at org.activiti.engine.impl.delegate.DefaultDelegateInterceptor.handleInvocation(DefaultDelegateInterceptor.java:25)
	at org.activiti.engine.impl.persistence.entity.TaskEntity.fireEvent(TaskEntity.java:740)
	... 184 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.tsgrp.opencontent.wizard.activiti.workflow.listener.WizardReviewWorkflowCreateTaskListener.notify(WizardReviewWorkflowCreateTaskListener.java:108)
	at org.activiti.engine.impl.delegate.TaskListenerInvocation.invoke(TaskListenerInvocation.java:34)
	at org.activiti.engine.impl.delegate.DelegateInvocation.proceed(DelegateInvocation.java:37)
	at org.activiti.engine.impl.delegate.DefaultDelegateInterceptor.handleInvocation(DefaultDelegateInterceptor.java:25)
	at org.activiti.engine.impl.bpmn.helper.ClassDelegate.notify(ClassDelegate.java:121)

```

**Comment by jlittle-tsg** [comment]
OCMS -  WIZARD REVIEW WORKFLOW SELECTED GROUPS UPDATE - fix for issue https://github.com/tsgrp/HPI/issues/2029. Ensuring that a group's authorityid is passed to the backend instead of it's display name. This was causing calls to getChildren to bomb out on Alfresco (groups passed in without 'GROUP_" prefix).

CR: nquillin, dgrumieaux
Revision Number: 24689

OC - WIZARD REVIEW WORKFLOW DEFER ASSIGNMENT - fix for issue https://github.com/tsgrp/HPI/issues/2029. When a new group task is created, the group was showing as the assignee rather than the candidate group. We are now making sure that this is set to null in the assignment listener.

CR: nquillin, dgrumieaux
Revision Number: 24466
