### ISSUE TITLE
Cannot edit properties for any object that doesn't have hpi_metadataPositions

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2034]
Something went in recently that is preventing edit properties from working on any object that doesn't have the `hpi_metadataPositions` attribute on the type.

On edge1, the action fails with the following error:

```
2020-01-14 09:06:57,578	ajp-nio-9009-exec-10	ERROR	RESTService	Dictionary Service does not know of property: hpi_metadataPositions
java.lang.IllegalArgumentException: Dictionary Service does not know of property: hpi_metadataPositions
	at com.tsgrp.opencontent.dctm.content.DCTMContentImpl.getRepoName(DCTMContentImpl.java:2154) ~[oc-hpiDemoDctm.2.dctm-3.3.0.jar:3.3.0]
	at com.tsgrp.opencontent.dctm.content.DCTMContentImpl.doUpdateObject(DCTMContentImpl.java:1932) ~[oc-hpiDemoDctm.2.dctm-3.3.0.jar:3.3.0]
	at com.tsgrp.opencontent.core.content.AbstractContentImpl.updateObject(AbstractContentImpl.java:284) ~[oc-hpiDemoDctm.1.core-3.3.0.jar:3.3.0]
	at com.tsgrp.opencontent.core.action.executer.ViewEditPropertiesExecuter.executeImpl(ViewEditPropertiesExecuter.java:211) ~[oc-hpiDemoDctm.1.core-3.3.0.jar:3.3.0]
```

On edge2, the edit properties action works, but then hangs:

![image](https://user-images.githubusercontent.com/1377228/72357477-a9d9f900-36b0-11ea-96df-189f2ad95974.png)

Error in the console is:

```
Uncaught TypeError: Cannot read property 'get' of undefined
    at ocms-require.min-81f1207ca0d1c2b48cfd8f371a155153.js:231746
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (ocms-require.min-81f1207ca0d1c2b48cfd8f371a155153.js:10099)
    at action.ViewModel.self._populateOldAndNewValueArrays (ocms-require.min-81f1207ca0d1c2b48cfd8f371a155153.js:231736)
    at ocms-require.min-81f1207ca0d1c2b48cfd8f371a155153.js:231836
```

**Comment by cheinz-tsg** [comment]
Closed with OCMS commit #24553
