### ISSUE TITLE
Checkout to OneDrive Integration No Longer Working After Recent Graph API Updates

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2065]
The OneDrive integration no longer works in trunk after the recent changes to move to the Graph API.  As part of the fix, we should update the Documentation here:

https://github.com/tsgrp/HPI/wiki/Edit-Online-Configurations#microsoft-onedrive

The error in OC is:

```
Caused by: org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:88)
	at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:566)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:524)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:482)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:430)
	at com.tsgrp.opencontent.core.action.executer.CheckoutToCloudServiceActionExecuter.executeImpl(CheckoutToCloudServiceActionExecuter.java:120)
	... 52 more
```

**Comment by mwojno-tsg** [comment]
At the time of implementation for the new Graph API, I did not test email addresses outside the tenant of the API. Therefore, I think I have to add an additional step within the Msal authentication on the javascript side to correctly return an access token for a user with an email address outside the organizational tenant that created the API. 

https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-convert-app-to-be-multi-tenant

**Comment by mwojno-tsg** [comment]
This issue will hopefully be resolved with the OC commit: 24605 and the OCMS commit: 24823. A lot of re-factoring was done in this commit to help the efficiency of this integration as well as better error handling. Another change to the scopes was to add the 'Sites.ReadWrite.All', which could help alleviate any permission issues. Finally, a toggle was added to give the user the ability to choose between the checkout location to be personal or organization. This also could help alleviate any permission issues.

If this doesn't solve the issues edge environments are seeing, then I suggest trying to re-create the API making sure it was created in the correct way. There could be an issue with when the API was created versus when this was implemented.

**Comment by gsteimer** [comment]
This seems to be working again on edge2 now.  See @mwojno-tsg's message above for the commit revs.
