### ISSUE TITLE
TSG Renditions no longer Generating

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2100]
Currently on edge2, no documents are properly being renditioned.  I'm guessing this has something to do with the updates around auto-renditioning with Alfresco associations to make Share/ADF work properly.

Here's an example object that I created today:

![image](https://user-images.githubusercontent.com/1377228/79585079-e6910400-8094-11ea-81f0-0feb66280588.png)

It looks like it has the `tsg:renditioned` aspect applied, but no rendition is being generated.

**Comment by gsteimer** [comment]
Attempting to check in a controlled doc throws the following error:
```
2020-04-17 10:22:26,266	2708016	ajp-apr-8009-exec-5	ERROR	EmbeddedAlfrescoAdvice	An unspecified OC exception occurred
com.tsgrp.opencontent.core.exception.OCRuntimeException: Unhandled exception around OC method class: doEnhancedCreateObject
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.doEnhancedUpdateObject(AlfrescoEmbContentImpl.java:1101)
	at com.tsgrp.opencontent.core.content.AbstractContentImpl.enhancedUpdateObject(AbstractContentImpl.java:235)
	at sun.reflect.GeneratedMethodAccessor1428.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
...
Caused by: org.alfresco.repo.node.integrity.IntegrityException: 03170108 Found 2 integrity violations:
The association target multiplicity has been violated: 
   Source Node: workspace://SpacesStore/377b62f3-8726-4665-a1a3-31bab6d34f4e
   Association: Association[ class=ClassDef[name={http://www.alfresco.org/model/content/1.0}copiedfrom], name={http://www.alfresco.org/model/content/1.0}original, target class={http://www.alfresco.org/model/content/1.0}cmobject, source role=null, target role=null]
   Required target Multiplicity: 0..1
   Actual target Multiplicity: 2
The association target multiplicity has been violated: 
   Source Node: workspace://SpacesStore/377b62f3-8726-4665-a1a3-31bab6d34f4e
   Association: Association[ class=ClassDef[name={http://www.alfresco.org/model/content/1.0}copiedfrom], name={http://www.alfresco.org/model/content/1.0}original, target class={http://www.alfresco.org/model/content/1.0}cmobject, source role=null, target role=null]
   Required target Multiplicity: 0..1
   Actual target Multiplicity: 2
	at org.alfresco.repo.node.integrity.IntegrityChecker.checkIntegrity(IntegrityChecker.java:669)
	at org.alfresco.repo.node.integrity.IntegrityChecker.beforeCommit(IntegrityChecker.java:771)
	at org.alfresco.util.transaction.TransactionSupportUtil$TransactionSynchronizationImpl.beforeCommit(TransactionSupportUtil.java:498)
	at org.springframework.transaction.support.TransactionSynchronizationUtils.triggerBeforeCommit(TransactionSynchronizationUtils.java:95)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.triggerBeforeCommit(AbstractPlatformTransactionManager.java:925)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:738)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:724)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:475)
	at org.alfresco.util.transaction.SpringAwareUserTransaction.commit(SpringAwareUserTransaction.java:482)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:486)
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl$4.execute(AlfrescoEmbContentImpl.java:1083)
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl$4.execute(AlfrescoEmbContentImpl.java:886)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464)
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.doEnhancedUpdateObject(AlfrescoEmbContentImpl.java:886)
...
2020-04-17 10:22:26,266	2708016	ajp-apr-8009-exec-5	ERROR	RESTService	Unable to get bytes from file
com.tsgrp.opencontent.core.exception.OCRuntimeException: Unable to get bytes from file
	at com.tsgrp.opencontent.core.action.executer.CheckinActionExecuter.executeImpl(CheckinActionExecuter.java:115)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.executeImpl(AbstractActionExecuter.java:239)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:226)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:156)
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475)
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeWithAttachment(RESTAction.java:718)
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPostWithAttachment(RESTAction.java:594)
```

**Comment by gsteimer** [comment]
No errors in the OC log.  If you create a new document, it never gets a rendition.  Documents that were already present before this was broken will look like they work, but only if you don't change the content.  If you do change the content, it'll be apparent that the PDF from the previous version is getting carried forward.

**Comment by gsteimer** [comment]
Fixed with OC Rev 25099.  CR: ballen, aking
