### ISSUE TITLE
Manage Ad Hoc Document - Failing for Alfresco

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2160]
When adding an Ad-Hoc supporting document to an AW form, it looks like the upload works successfully.  However, the association is failing to be created on the OC side, so the supporting document is not visible from the stage.

The error in OC is:

```
2020-07-14 14:40:04,334	46601459	ajp-apr-8009-exec-15	ERROR	RESTService	Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.content.IContent| name: addRelation
com.tsgrp.opencontent.core.exception.OCRuntimeException: Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.content.IContent| name: addRelation
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy458.addRelation(Unknown Source)
	at com.tsgrp.opencontent.core.content.RESTContent.addRelation(RESTContent.java:1507)
...
Caused by: java.lang.IllegalArgumentException: Association {}aw_rel_supporting_document has not been defined in the data dictionary
	at org.alfresco.repo.policy.AssociationPolicyDelegate.checkAssocType(AssociationPolicyDelegate.java:90)
	at org.alfresco.repo.policy.AssociationPolicyDelegate.get(AssociationPolicyDelegate.java:176)
```

**Comment by mwojno-tsg** [comment]
Completed with OCMS commit at revision: 25486. The fix was adding `"manageadhocdocuments": manageAdHocDocumentsConfig,` to the `config` variable in the relevant `config-project.js`. Essentially, the project wasn't correctly overriding the `module.config().supportingDocumentRelationName` within the `manageadhocdocuments.js` and defaulting to the dctm association name.
