### ISSUE TITLE
Docusign job fails with decryption error

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2187]
The Docusign action and Job code handle the password encryption differently:

- Action - utilizes the correct new `@{ ... }` syntax. See https://github.com/tsgrp/OpenContent/wiki/Encrypting-a-Password#working-with-encrypted-values Using this syntax, Spring will automatically decrypt the password upon injection
- Job - code blindly tries to decrypt the property

With the above differences, either the action or the job won't work.  If the property is encrypted and does not use the `@{ ... }` syntax, then the Job will work but the Action will 401.  If the property _does_ use the `@{ ... }` syntax, then the action will work but the job will fail since the code is trying to decrpyt an already decrypted value.  The job will fail with:

```
Caused by: javax.crypto.IllegalBlockSizeException: Input length must be multiple of 8 when decrypting with padded cipher
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:913)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:824)
	at com.sun.crypto.provider.BlowfishCipher.engineDoFinal(BlowfishCipher.java:319)
	at javax.crypto.Cipher.doFinal(Cipher.java:2165)
	at com.tsgrp.util.TsgEncrypter.decrypt(TsgEncrypter.java:160)
	at com.tsgrp.opencontent.alfresco.job.RetrieveDocusignContentJob$1.execute(RetrieveDocusignContentJob.java:96)
```

The best solution here is to simply update the job to utilize the new `@{ ... }` syntax and _not_ blindly try to decrypt.

**Comment by aviking** [comment]
Issue resolved in OC commit: 25790

CR: gsteimer
