### ISSUE TITLE
Active Wizard Word Template Merge No Longer Works

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2195]
It seems that creating a wizard form that is tied to a Word template is no longer functioning correctly.  

When creating a wizard form in the mode where it creates a new document in the folder (Ex: Claims Create Letter or Contract Management MSA), the following error occurs:

```
2020-08-03 09:55:29,338	29491233	ajp-apr-8009-exec-5	ERROR	RESTService	there was an error trying to reset approval details
java.lang.RuntimeException: there was an error trying to reset approval details
	at com.tsgrp.opencontent.wizard.activiti.workflow.ActivitiClientWizardWorkflowImpl.resetApprovalDetails(ActivitiClientWizardWorkflowImpl.java:433)
	at com.tsgrp.opencontent.wizard.activiti.workflow.WizardWorkflowHelper.resetApprovalDetailsWhenNotInApprovalWorkflow(WizardWorkflowHelper.java:378)
	at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.executeImpl(FinishAndSubmitPSIActionExecutor.java:169)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.executeImpl(AbstractActionExecuter.java:239)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:226)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:156)
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475)
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:224)
...
Caused by: com.tsgrp.opencontent.core.exception.OCRuntimeException: could not find workflow definition object in the repository. Cannot create new approval details object
	at com.tsgrp.opencontent.wizard.activiti.workflow.WizardWorkflowHelper.generateNewApprovalDetails(WizardWorkflowHelper.java:72)
	at com.tsgrp.opencontent.wizard.activiti.workflow.ActivitiClientWizardWorkflowImpl.resetApprovalDetails(ActivitiClientWizardWorkflowImpl.java:430)
	... 54 more

```

When creating the form from the header action (in this mode the Word template PDF becomes the AW form PDF), the following error occurs:

```
2020-08-03 09:53:30,583	29372478	ajp-apr-8009-exec-10	ERROR	RESTService	Error creating pdf rendition of wizard form!
com.tsgrp.opencontent.core.exception.OCRuntimeException: Error creating pdf rendition of wizard form!
	at com.tsgrp.opencontent.wizard.PSIJSONUtil.jsonToPdf(PSIJSONUtil.java:793)
	at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.executeImpl(FinishAndSubmitPSIActionExecutor.java:98)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.executeImpl(AbstractActionExecuter.java:239)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:226)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:156)
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475)
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:224)
...
Caused by: com.tsgrp.opencontent.core.exception.OCRuntimeException: Unable to fetch Mail Merge form with Id: 
	at com.tsgrp.opencontent.wizard.PSIJSONUtil.generatePDFFromMailMergeTemplate(PSIJSONUtil.java:1036)
	at com.tsgrp.opencontent.wizard.PSIJSONUtil.jsonToPdf(PSIJSONUtil.java:780)
	... 53 more
Caused by: com.tsgrp.opencontent.core.exception.OCRuntimeException: Error occured transforming using the Alfresco External Transformation Server
	at com.tsgrp.opencontent.transformation.ExternalAlfrescoTransformer.transformSync(ExternalAlfrescoTransformer.java:129)
	at com.tsgrp.opencontent.core.transformation.TransformationImpl.transform(TransformationImpl.java:86)
	at com.tsgrp.opencontent.universal.template.AbstractWordDocumentTemplatingImpl.performMailMerge(AbstractWordDocumentTemplatingImpl.java:237)
	at com.tsgrp.opencontent.wizard.PSIJSONUtil.generatePDFFromMailMergeTemplate(PSIJSONUtil.java:1032)
	... 54 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
```

**Comment by gsteimer** [comment]
It looks like the error above was a red herring.  After the fix for #2196 , this is working again.
