### ISSUE TITLE
AW form cannot be created if it does not have workflow roles

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2196]
With the commit for #2164 , we introduced an issue where the form creation will fail with the following error if the form template does NOT utilize workflow roles:

```
2020-08-03 09:55:29,338	29491233	ajp-apr-8009-exec-5	ERROR	RESTService	there was an error trying to reset approval details
java.lang.RuntimeException: there was an error trying to reset approval details
	at com.tsgrp.opencontent.wizard.activiti.workflow.ActivitiClientWizardWorkflowImpl.resetApprovalDetails(ActivitiClientWizardWorkflowImpl.java:433)
	at com.tsgrp.opencontent.wizard.activiti.workflow.WizardWorkflowHelper.resetApprovalDetailsWhenNotInApprovalWorkflow(WizardWorkflowHelper.java:378)
	at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.executeImpl(FinishAndSubmitPSIActionExecutor.java:169)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.executeImpl(AbstractActionExecuter.java:239)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:226)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:156)
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475)
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:224)
...
Caused by: com.tsgrp.opencontent.core.exception.OCRuntimeException: could not find workflow definition object in the repository. Cannot create new approval details object
	at com.tsgrp.opencontent.wizard.activiti.workflow.WizardWorkflowHelper.generateNewApprovalDetails(WizardWorkflowHelper.java:72)
	at com.tsgrp.opencontent.wizard.activiti.workflow.ActivitiClientWizardWorkflowImpl.resetApprovalDetails(ActivitiClientWizardWorkflowImpl.java:430)
	... 54 more
```

**Comment by grahamsinger** [comment]
Closed with OC revision 25929.
