### ISSUE TITLE
Customized Images cannot restore to default on Documentum

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2217]
The #2181 enhancement looks great when it comes to uploading new images.  However, resetting to the default images fails with the following error in OC: 

```
2020-08-10 11:34:29,816	ajp-nio-9009-exec-5	ERROR	RESTService	An issue occured when deleting Asset with name: login-logo.png under appId: default
com.tsgrp.opencontent.core.exception.OCRuntimeException: An issue occured when deleting Asset with name: login-logo.png under appId: default
	at com.tsgrp.opencontent.core.config.persistence.RepositoryConfigServiceImpl.removeAssetFile(RepositoryConfigServiceImpl.java:1248) ~[oc-hpiDemoDctm.1.core-3.4.0.jar:3.4.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
...
Caused by: com.tsgrp.opencontent.core.exception.OCNotSupportedException: Force Delete is not supported for Documentum
	at com.tsgrp.opencontent.dctm.content.DCTMContentImpl.doEnhancedDeleteObject(DCTMContentImpl.java:1250) ~[oc-hpiDemoDctm.2.dctm-3.4.0.jar:3.4.0]
	at com.tsgrp.opencontent.core.content.AbstractContentImpl.enhancedDeleteObject(AbstractContentImpl.java:417) ~[oc-hpiDemoDctm.1.core-3.4.0.jar:3.4.0]
	at com.tsgrp.opencontent.core.config.persistence.RepositoryConfigServiceImpl.removeAssetFile(RepositoryConfigServiceImpl.java:1245) ~[oc-hpiDemoDctm.1.core-3.4.0.jar:3.4.0]
```

**Comment by Kovacinski** [comment]
Closed with OC Revision: 25921
