### ISSUE TITLE
HBase GetParents Implementation Sometimes Returns The Object's Own ID

### ISSUE THREAD

**Issue by cheinz-tsg** [tsgrp/HPI#2237]
HBaseExtendedContentImpl::GetParents will return an array with two ids, the parent object's id as well as the object's own id, if the object is indexed in Solr and Case Prefix Mode is configured for OC. This is a result of an initial solr query on the object (which looks for the object's rel_parent property and correcty returns the parent object's id) followed by an attempt to find the parent object's id again through a method specific to Case Prefix Mode, which will ultimately return the object's own id. Although it is uncommon for an object to be indexed in Solr in case prefix mode, it is a valid scenario that should be handled.

Noticeable errors that are caused by this bug include wizard form creation erroring-out and related object queries excluding documents that should not be excluded (incorrectly excludes a document when the logic is attempting to exclude the document's parent folder).

Logs when wizard form creation errors out:
```
com.tsgrp.opencontent.core.exception.OCRuntimeException: Failed to get parent path of page set instance to create workflow definition
        at com.tsgrp.opencontent.wizard.workflow.Wizard2WorkflowImpl.createOrUpdateWorkflowDefinition(Wizard2WorkflowImpl.java:841) [oc-hbase-demo.3.wizard-3.4.0.jar:3.4.0]
        at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.executeImpl(FinishAndSubmitPSIActionExecutor.java:116) [oc-hbase-demo.3.wizard-3.4.0.jar:3.4.0]
        at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.executeImpl(AbstractActionExecuter.java:239) [oc-hbase-demo.1.core-3.4.0.jar:3.4.0]
        at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:226) [oc-hbase-demo.1.core-3.4.0.jar:3.4.0]
        at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:156) [oc-hbase-demo.1.core-3.4.0.jar:3.4.0]
        at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475) [oc-hbase-demo.1.core-3.4.0.jar:3.4.0]
        at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:224) [oc-hbase-demo.1.core-3.4.0.jar:3.4.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) [spring-web-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) [spring-web-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) [spring-webmvc-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) [spring-webmvc-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) [spring-webmvc-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) [spring-webmvc-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) [spring-webmvc-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:998) [spring-webmvc-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:901) [spring-webmvc-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [servlet-api.jar:?]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:875) [spring-webmvc-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.45]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.45]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.45]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.45]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.45]
        at com.tsgrp.opencontent.rest.filter.OCTimingFilter.doFilterInternal(OCTimingFilter.java:83) [oc-hbase-demo.1.core-3.4.0.jar:3.4.0]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.1.RELEASE.jar:5.1.1.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.45]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.45]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:8.5.45]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.45]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528) [catalina.jar:8.5.45]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:8.5.45]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.45]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [catalina.jar:8.5.45]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.45]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:8.5.45]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) [tomcat-coyote.jar:8.5.45]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.45]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810) [tomcat-coyote.jar:8.5.45]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-coyote.jar:8.5.45]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_221]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.45]
```

Code that throws error (notice the parent ids length check)
```
if(parents == null || parents.getError() || parents.getObjects().length != 1){
      throw new OCRuntimeException("Failed to get parent path of page set instance to create workflow definition");
}
```

**Comment by cheinz-tsg** [comment]
Fixed with OC Commit #25980. Now in addition to the check on whether prefix mode is enabled, there is another check on whether prefix mode is used by the type of the document being queried (as this can vary from type to type). If the type is using a prefix, then there is no way the solr query for "rel_parent" will return an id. If not, it is guaranteed that the solr query will return the id and that no additional work needs to be done.
