### ISSUE TITLE
AW Admin - Cannot load update property value impact screen

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2279]
When trying to load the Update Property Value impact screen in AW admin the page fails to load with the error below.

![image](https://user-images.githubusercontent.com/1377228/93502662-a3a1b980-f8dc-11ea-84cc-89e8ab8f7758.png)

```
Caused by: com.tsgrp.dfi.DfiException: Could not read JSON: Unrecognized field "prefixKey" (Class com.tsgrp.opencontent.core.config.model.OCTypeDefinition), not marked as ignorable
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@66bde24e; line: 1, column: 32467] (through reference chain: com.tsgrp.opencontent.core.config.model.OCTypeDefinition["prefixKey"]); nested exception is org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "prefixKey" (Class com.tsgrp.opencontent.core.config.model.OCTypeDefinition), not marked as ignorable
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@66bde24e; line: 1, column: 32467] (through reference chain: com.tsgrp.opencontent.core.config.model.OCTypeDefinition["prefixKey"])
	at com.tsgrp.wizard.tags.GetUpdateablePropertiesTag.doStartTag(GetUpdateablePropertiesTag.java:101)
	at org.apache.jsp.jsp.ia_005fadmin_005fupdate_005fproperty_005fvalues_jsp._jspService(ia_005fadmin_005fupdate_005fproperty_005fvalues_jsp.java:289)
	... 34 more
```

**Comment by gsteimer** [comment]
Note - this same error is happening on edge1 and edge2, so the error is not repo specific

**Comment by gsteimer** [comment]
Note - no OC error is being thrown.  The actual error in the AW admin logs is:

```
Thursday, September 17, 2020 1:36:06 PM CDT Class: GetUpdateablePropertiesTag Method: doStartTag
	DfiException: org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Unrecognized field "prefixKey" (Class com.tsgrp.opencontent.core.config.model.OCTypeDefinition), not marked as ignorable
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@33046a03; line: 1, column: 32467] (through reference chain: com.tsgrp.opencontent.core.config.model.OCTypeDefinition["prefixKey"]); nested exception is org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "prefixKey" (Class com.tsgrp.opencontent.core.config.model.OCTypeDefinition), not marked as ignorable
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@33046a03; line: 1, column: 32467] (through reference chain: com.tsgrp.opencontent.core.config.model.OCTypeDefinition["prefixKey"])
	at org.springframework.http.converter.json.MappingJacksonHttpMessageConverter.readInternal(MappingJacksonHttpMessageConverter.java:125)
	at org.springframework.http.converter.AbstractHttpMessageConverter.read(AbstractHttpMessageConverter.java:153)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:81)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:454)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:409)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:207)
	at com.tsgrp.wizard.tags.GetUpdateablePropertiesTag.fetchUpdateableProperties(GetUpdateablePropertiesTag.java:172)
	at com.tsgrp.wizard.tags.GetUpdateablePropertiesTag.doStartTag(GetUpdateablePropertiesTag.java:82)
...
Thursday, September 17, 2020 1:36:06 PM CDT Class: GetUpdateablePropertiesTag Method: doStartTag
	DfiException: org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Unrecognized field "prefixKey" (Class com.tsgrp.opencontent.core.config.model.OCTypeDefinition), not marked as ignorable
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@33046a03; line: 1, column: 32467] (through reference chain: com.tsgrp.opencontent.core.config.model.OCTypeDefinition["prefixKey"]); nested exception is org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "prefixKey" (Class com.tsgrp.opencontent.core.config.model.OCTypeDefinition), not marked as ignorable
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@33046a03; line: 1, column: 32467] (through reference chain: com.tsgrp.opencontent.core.config.model.OCTypeDefinition["prefixKey"])
	at org.springframework.http.converter.json.MappingJacksonHttpMessageConverter.readInternal(MappingJacksonHttpMessageConverter.java:125)
	at org.springframework.http.converter.AbstractHttpMessageConverter.read(AbstractHttpMessageConverter.java:153)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:81)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:454)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:409)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:207)
	at com.tsgrp.wizard.tags.GetUpdateablePropertiesTag.fetchUpdateableProperties(GetUpdateablePropertiesTag.java:172)
	at com.tsgrp.wizard.tags.GetUpdateablePropertiesTag.doStartTag(GetUpdateablePropertiesTag.java:82)
```

Could point to a model jar conflict error?

**Comment by gsteimer** [comment]
Fixed with AW Admin REV: 7810
