### ISSUE TITLE
Microsoft Graph API SSL Certificate Issue

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2282]
Something seems to have changed that's breaking the Office 365 edit online functionality.  On edge2 (Alfresco), the checkout fails with the following error:

```
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on PUT request for "https://graph.microsoft.com/v1.0/me/drive/root:/OCMS_Working_Copies/TSG-126.docx:/content": sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:534)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:482)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:430)
	at com.tsgrp.opencontent.core.action.executer.CheckoutToCloudServiceActionExecuter.executeImpl(CheckoutToCloudServiceActionExecuter.java:125)
	... 52 more
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by mwojno-tsg** [comment]
Tony installed a the new `https://graph.microsoft.com` certificate that they recently changed to the JVM for edge 2 and this fixed the issue with certification.

**Comment by gsteimer** [comment]
Seems like this is happening again on edge2 and release2

**Comment by gsteimer** [comment]
It looks like this is also affecting the Send to Docusign action, although the error is slightly different:

```
2021-10-07 09:03:41,815	387299327	ajp-apr-8009-exec-1	DEBUG	SendToDocuSignActionExecuter	STEP 1:  Sending Login request...

2021-10-07 09:03:41,908	387299420	ajp-apr-8009-exec-1	ERROR	RESTService	java.lang.IllegalArgumentException: SSLv3d
java.lang.RuntimeException: java.lang.IllegalArgumentException: SSLv3d
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at com.tsgrp.opencontent.universal.action.executer.SendToDocuSignActionExecuter.executeImpl(SendToDocuSignActionExecuter.java:136)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.executeImpl(AbstractActionExecuter.java:239)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:226)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:156)
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475)
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:226)
...
Caused by: java.lang.IllegalArgumentException: SSLv3d
	at sun.security.ssl.ProtocolVersion.valueOf(Unknown Source)
	at sun.security.ssl.ProtocolList.convert(Unknown Source)
	at sun.security.ssl.ProtocolList.<init>(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.setEnabledProtocols(Unknown Source)
```

**Comment by gsteimer** [comment]
Fixing the cert fixed both issues above
