### ISSUE TITLE
ACA PnP changing extendPermissionModel bean id in module context 

### ISSUE THREAD

**Issue by mwojno-tsg** [tsgrp/HPI#2334]
## Overview
- There was a bean conflict in a customer's env that also used `extendPermissionModel` bean id. Therefore, it threw off permissions for the PnP ACA env, which produced a lot issues whenever the permission model was hit. 

```
[2020-11-24 18:32:55,860|ERROR|AspectSecurityBehaviour|doWork|150] failed running doWork!
java.lang.UnsupportedOperationException: Can not find wizard_form_pending_approval
	at org.alfresco.repo.security.permissions.impl.model.PermissionModel$MutableState.getPermissionReference(PermissionModel.java:1012)
	at org.alfresco.repo.security.permissions.impl.model.PermissionModel.getPermissionReference(PermissionModel.java:1858)
	at org.alfresco.repo.security.permissions.impl.PermissionServiceImpl.getPermissionReference_aroundBody58(PermissionServiceImpl.java:1190)
	at org.alfresco.repo.security.permissions.impl.PermissionServiceImpl$AjcClosure59.run(PermissionServiceImpl.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:257)
	at org.alfresco.traitextender.AJExtender.localProceed(AJExtender.java:728)
	at org.alfresco.traitextender.AJProxyTrait.invoke(AJProxyTrait.java:86)
	at com.sun.proxy.$Proxy40.getPermissionReference(Unknown Source)
	at 
```

## Solution
- The solution was to change the `extendPermissionModel` bean id to `pnpExtendPermissionModel` bean id. 
- This documentation also confirms that it is probably best practice to prefix this bean id to avoid conflicts: https://docs.alfresco.com/5.0/concepts/dev-extensions-modules-custom-permission-model.html

**Comment by mwojno-tsg** [comment]
Issue closed with OC commit: **26551**. changed permission model bean id to 'com.tsgrp.opencontent.extendPermissionModel' instead of 'extendPermissionModel'. We ran into a bean conflict with pnp paas env that threw off permissions for ACA. The better practice for the bean id is declaring what module they are in anyways.

Following project's module context was changed: 
- policy-and-procedure-alf6
- insurance-alf6
- hpi-demo-alf
- acs5-accelerator-base
- acs6-accelerator-base
- ocms-demo-alf6
- oaAlfresco (added)

CR: gsteimer, dgrumieaux
