### ISSUE TITLE
Checkin from O365 failing with NPE

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2355]
On release1 (Documentum), the O365 / Word Online integration cannot check in a document.  The following error is thrown:

```
2021-01-21 15:01:28,206	ajp-nio-8009-exec-4	ERROR	RESTService	null
java.lang.NullPointerException: null
	at com.tsgrp.opencontent.core.action.executer.CheckinFromCloudServiceActionExecuter.checkinFromMicrosoftOnline(CheckinFromCloudServiceActionExecuter.java:254) ~[oc-hpiDemoDctm.1.core-3.4.2.jar:3.4.2]
	at com.tsgrp.opencontent.core.action.executer.CheckinFromCloudServiceActionExecuter.executeImpl(CheckinFromCloudServiceActionExecuter.java:129) ~[oc-hpiDemoDctm.1.core-3.4.2.jar:3.4.2]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.executeImpl(AbstractActionExecuter.java:239) ~[oc-hpiDemoDctm.1.core-3.4.2.jar:3.4.2]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:226) ~[oc-hpiDemoDctm.1.core-3.4.2.jar:3.4.2]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:156) ~[oc-hpiDemoDctm.1.core-3.4.2.jar:3.4.2]
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475) ~[oc-hpiDemoDctm.1.core-3.4.2.jar:3.4.2]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:226) ~[oc-hpiDemoDctm.1.core-3.4.2.jar:3.4.2]
```
For some reason, this is not happening on edge2 and release2 (Alfresco).  Here is the document I was testing with (newly created today - 01/21/2021):

https://release1.tsgrp.com/ocms/Stage/ControlledDocs/0b0000038003b82c%7C0900000380057a14

**Comment by gsteimer** [comment]
Note - this may be something to do with "old" documents.  After checking out and checking in normally, editing online seems to work.
