### ISSUE TITLE
User Prefs failing to save

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#2357]
Not sure how this is happening, but my user preferences object will randomly fail to save on edge2 (Alfresco).  The error in the console is:

```
2021-01-21 15:59:49,458	30338043	ajp-apr-8009-exec-8	ERROR	RESTService	Error creating JSON object with the request and grabbing name of user preference: JSONObject[&quot;id&quot;] not found.
com.tsgrp.opencontent.core.exception.OCRuntimeException: Error creating JSON object with the request and grabbing name of user preference: JSONObject["id"] not found.
	at com.tsgrp.opencontent.core.preferences.GenericPreferencesService.updatePreferencesByName(GenericPreferencesService.java:274)
	at com.tsgrp.opencontent.core.userpreferences.persistence.RESTUserPreferencesService.saveUserPreference(RESTUserPreferencesService.java:157)
...
Caused by: org.json.JSONException: JSONObject["id"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at org.json.JSONObject.getString(JSONObject.java:669)
	at com.tsgrp.opencontent.core.preferences.GenericPreferencesService.updatePreferencesByName(GenericPreferencesService.java:254)
```

My only recourse is to delete my user prefs object from the repository.  I can't pinpoint how this is happening, but it has happened twice today.

**Comment by gsteimer** [comment]
Cannot reproduce - bumping the priority down to 3.x.  We can move this back to the 3.5 queue if it crops up again
