### ISSUE TITLE
Misleading autofile error thrown when uploading document with certain configurations 

### ISSUE THREAD

**Issue by jlittle-tsg** [tsgrp/HPI#2378]
When the `tsgrp-autofile.amp` is applied and you upload a document to PnP OCMS, the following error is thrown even though the document is autofiled correctly.

```
Unable to autofile document workspace://SpacesStore/9870348c-51db-46cf-8169-7b99fb0d5a3a
java.lang.Exception: Unable to locate autofile configuration object for type {http://www.activewizard.com/model/content/1.0}qualityDocument
        at com.tsgrp.autofile.policy.AutofilePolicy.retrieveAutofileConfigNode(AutofilePolicy.java:475)
        at com.tsgrp.autofile.policy.AutofilePolicy$1.doWork(AutofilePolicy.java:229)
        at com.tsgrp.autofile.policy.AutofilePolicy$1.doWork(AutofilePolicy.java:182)
        at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:602)
        at org.alfresco.repo.security.authentication.AuthenticationUtil.runAsSystem(AuthenticationUtil.java:642)
        at com.tsgrp.autofile.policy.AutofilePolicy.onAddAspect(AutofilePolicy.java:182)
        at jdk.internal.reflect.GeneratedMethodAccessor2087.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.alfresco.repo.policy.JavaBehaviour$JavaMethodInvocationHandler.invoke(JavaBehaviour.java:181)
        at com.sun.proxy.$Proxy81.onAddAspect(Unknown Source)
        at jdk.internal.reflect.GeneratedMethodAccessor379.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by gsteimer** [comment]
@jlittle-tsg @dgrumieaux - is this error specific to ACS 7?  I don't recall seeing any issues with ACS 5 or 6.

**Comment by jlittle-tsg** [comment]
@gsteimer Thinking so. Not seeing this error on ACS 6.2.

**Comment by jlittle-tsg** [comment]
Resolved with Autofile Amp Revision 10465

------------ Commit Log ------------
LOGGING - changing the exception catch in onAddAspect from a logger.error to a logger.warn to prevent a misleading error from popping up in the logs when uploading a document in certain scenarios (i.e. pnp) even when autofiling was successful. 

CRs: aking, dvora
