### ISSUE TITLE
User Preferences Left Locked

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#2418]
For some reason, after the update for #2413 somehow user's preferences objects are left checked out:

![image](https://user-images.githubusercontent.com/1377228/119727806-5b0da900-be38-11eb-8733-26cbf9c5e9ff.png)

This causes all future user preferences updates to fail with:

```
2021-05-26 15:32:09,843	49556768	ajp-apr-8009-exec-2	WARN 	GenericPreferencesService	User preference object is already locked - workspace://SpacesStore/7f4a7ba5-867a-4b25-a8f0-b01394d9ee4e
com.tsgrp.opencontent.core.exception.OCRuntimeException: Unknown error while locking object with id workspace://SpacesStore/7f4a7ba5-867a-4b25-a8f0-b01394d9ee4e.
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.lockDocument(AlfrescoEmbContentImpl.java:293)
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.lockDocument(AlfrescoEmbContentImpl.java:261)
	at sun.reflect.GeneratedMethodAccessor1787.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
...
Caused by: com.tsgrp.opencontent.core.exception.OCObjectLockedException: Unable to acquire a lock - object with id: workspace://SpacesStore/7f4a7ba5-867a-4b25-a8f0-b01394d9ee4e is already locked.
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.lockDocument(AlfrescoEmbContentImpl.java:285)
	... 62 more
```

The temporary "fix" is to simply unlock the object.  After doing that, user prefs updates work fine, but eventually the object is locked again.

**Comment by gsteimer** [comment]
Doing a little more digging, I found in the logs where it's failing to unlock the user preferences.  Unfortunately there's no stack trace (@dhruvvora94 is going to add something), but here's around where the error occurs:

```
2021-05-26 15:26:23,317|INFO |AbstractAlfrescoEmbQueryImpl|buildFTSQuery|1550] Generated Query: =hpi\:indexStatus:New AND TYPE:insuranceDemo\:claimsDocument AND -ASPECT:cm\:workingcopy AND -=cvn:isActiveVersion:false
[2021-05-26 15:26:23,317|DEBUG|AbstractAlfrescoEmbQueryImpl|getNumberOfResults|155] results is PagingLuceneResultSet
[2021-05-26 15:26:24,929|DEBUG|RESTAction|evaluateActions|130] Resolving actions: bulkUpload-noContext,createWizardForm-noContext,createFolder-noContext,generateWorkflowReport-noContext took: 0 seconds.
[2021-05-26 15:26:24,945|DEBUG|ActivitiNotificationImpl|getNotifications|95] Begin ActivitiNotificationImpl.getNotifications...
[2021-05-26 15:26:27,368|DEBUG|RESTQueryUtil|parseRestrictionConfig|519] Parsing restriction config for non-composite type: Quality Document
[2021-05-26 15:26:27,384|DEBUG|AbstractAlfrescoEmbQueryImpl|doExecuteQuery|382] Running query using Alfresco APIs
[2021-05-26 15:26:27,400|INFO |AbstractAlfrescoEmbQueryImpl|buildFTSQuery|1550] Generated Query: (@tsg\:documentNumber:\*TSG\* AND =tsg\:status:Effective) AND TYPE:aw\:qualityDocument AND -ASPECT:cm\:workingcopy AND -=cvn:isActiveVersion:false
[2021-05-26 15:26:27,415|DEBUG|AbstractAlfrescoEmbQueryImpl|getNumberOfResults|141] results is SolrJSONResultSet
[2021-05-26 15:26:27,728|DEBUG|LogstashPerformanceLoggingImpl|createPerformanceLog|67] gsteimer search 23 Chrome-v90 eventDuration 276
[2021-05-26 15:26:29,682|DEBUG|RESTAction|evaluateActions|130] Resolving actions: bulkUpload-noContext,createWizardForm-noContext,createFolder-noContext,generateWorkflowReport-noContext took: 0 seconds.
[2021-05-26 15:26:29,682|DEBUG|ActivitiNotificationImpl|getNotifications|95] Begin ActivitiNotificationImpl.getNotifications...
2021-05-26 15:26:30,495  INFO  [solr.component.AsyncBuildSuggestComponent] [Suggestor-alfresco-1] Building suggester index for: shingleBasedSuggestions
 [2021-05-26 15:26:32,477|INFO |RESTUserPreferencesService|saveUserPreference|146] Found prefs for user: gsteimer Updating preferences.
[2021-05-26 15:26:32,555|DEBUG|AbstractContentImpl|enhancedUpdateObject|228] ---CHECKING FOR BEFORE UPDATE EVENTS ---
[2021-05-26 15:26:32,586|DEBUG|AbstractContentImpl|enhancedUpdateObject|237] ---CHECKING FOR AFTER UPDATE EVENTS ---
[2021-05-26 15:26:32,602|DEBUG|AlfrescoDaoUtils|doUpdateVersionNode|184] Adding properties to node workspace://version2Store/57ac24b9-b07a-4ae4-bee2-8dddcebcc23a
[2021-05-26 15:26:32,602|DEBUG|AlfrescoDaoUtils|doUpdateVersionNode|195] Updated node: workspace://version2Store/57ac24b9-b07a-4ae4-bee2-8dddcebcc23a
[2021-05-26 15:26:32,852|INFO |RESTUserPreferencesService|saveUserPreference|146] Found prefs for user: gsteimer Updating preferences.
[2021-05-26 15:26:33,149|DEBUG|AbstractContentImpl|enhancedUpdateObject|228] ---CHECKING FOR BEFORE UPDATE EVENTS ---
[2021-05-26 15:26:33,149|DEBUG|EmbeddedAlfrescoAdvice|invoke|87] Access Denied
[2021-05-26 15:26:33,149|DEBUG|EmbeddedAlfrescoAdvice|invoke|87] Access Denied
[2021-05-26 15:26:33,149|ERROR|GenericPreferencesService|updatePreferencesByName|310] failed to unlock document workspace://SpacesStore/9136ca16-c27e-4f6d-bdc5-ec055c9c1534
[2021-05-26 15:26:33,664|DEBUG|EmbeddedAlfrescoAdvice|invoke|87] Access Denied
2021-05-26 15:27:00,999  INFO  [solr.component.AsyncBuildSuggestComponent] [Suggestor-alfresco-1] Built suggester shingleBasedSuggestions, took 30504 ms
 2021-05-26 15:27:01,187  INFO  [solr.component.AsyncBuildSuggestComponent] [Suggestor-alfresco-1] Building suggester index for: shingleBasedSuggestions
 2021-05-26 15:27:30,524  INFO  [solr.component.AsyncBuildSuggestComponent] [Suggestor-alfresco-1] Built suggester shingleBasedSuggestions, took 29337 ms
 2021-05-26 15:29:22.590 ERROR 4204 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

java.lang.NullPointerException: null

[2021-05-26 15:30:00,038|DEBUG|RemoveOATempFilesActionExecuter|executeImpl|87] Looking in directory: D:\Alfresco_Edge\alfresco-enterprise-5.1.2\tomcat\temp to delete old temp files...
[2021-05-26 15:30:00,038|DEBUG|RemoveOATempFilesActionExecuter|executeImpl|87] Looking in directory: D:\Alfresco_Edge\alfresco-enterprise-5.1.2\tomcat\temp to delete old temp files...
[2021-05-26 15:30:00,038|DEBUG|CleanUpStuckIndexingDocumentsJob|computeThresholdTime|140] Using threshold=300 seconds.
[2021-05-26 15:30:00,038|DEBUG|CleanUpStuckIndexingDocumentsJob|execute|47] thresholdTime=2021-05-26 03:25:00
[2021-05-26 15:30:00,038|DEBUG|GetMeetingRecordingsJob|execute|32] Starting getMeetingRecordingsJob
[2021-05-26 15:30:00,038|DEBUG|CleanUpStuckIndexingDocumentsJob|findIndexingDocs|164] Executing indexing docs query: TYPE:"cm:content" AND =@hpi:indexStatus:"Indexing"
[2021-05-26 15:30:00,053|DEBUG|AbstractAlfrescoEmbQueryImpl|doExecuteQuery|382] Running query using Alfresco APIs
[2021-05-26 15:30:00,053|INFO |AbstractAlfrescoEmbQueryImpl|buildFTSQuery|1550] Generated Query: =oa\:isDownloaded:false AND -ASPECT:cm\:workingcopy AND -=cvn:isActiveVersion:false
[2021-05-26 15:30:00,100|INFO |CleanUpStuckIndexingDocumentsJob|processStuckDocs|76] No results from the indexing docs query.
```

The actual error is this line:

```
[2021-05-26 15:26:33,149|ERROR|GenericPreferencesService|updatePreferencesByName|310] failed to unlock document workspace://SpacesStore/9136ca16-c27e-4f6d-bdc5-ec055c9c1534
```

That object ID is the `gsteimer` user prefs object on edge2

**Comment by gsteimer** [comment]
@dhruvvora94 - ok - the updated logging is giving us a better error message when this happens.  Here's the actual error that's leaving the user prefs locked:

```
021-05-31 22:46:18,997	75581859	ajp-apr-8009-exec-13	ERROR	GenericPreferencesService	failed to unlock document workspace://SpacesStore/c3a488ae-03e6-40ba-9916-410834b80445
com.tsgrp.opencontent.core.exception.OCAuthenticationException: Access Denied
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:88)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy454.getLockOwner(Unknown Source)
	at com.tsgrp.opencontent.core.preferences.GenericPreferencesService.updatePreferencesByName(GenericPreferencesService.java:303)
	at com.tsgrp.opencontent.core.userpreferences.persistence.RESTUserPreferencesService.saveUserPreference(RESTUserPreferencesService.java:158)
	at sun.reflect.GeneratedMethodAccessor1574.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
...
Caused by: org.alfresco.repo.security.authentication.AuthenticationException: 04310302 Unable to validate ticket
	at org.alfresco.repo.security.authentication.AbstractChainingAuthenticationService.validate(AbstractChainingAuthenticationService.java:368)
	at sun.reflect.GeneratedMethodAccessor799.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
        ...
        at com.tsgrp.opencontent.alfresco.context.ServiceRegistryProxy.getServiceRegistry(ServiceRegistryProxy.java:50)
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.getLockOwner(AlfrescoEmbContentImpl.java:1539)
	at sun.reflect.GeneratedMethodAccessor1094.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice$1.execute(EmbeddedAlfrescoAdvice.java:72)

**Comment by Kovacinski** [comment]
Closed with revision: 27059
