### ISSUE TITLE
Obsolete Document Fails

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#2457]
Obsoleting a document fails on edge2 with the following error:

```
2021-11-05 09:37:29,239	28918747	ajp-apr-8009-exec-9	ERROR	RESTService	java.lang.String cannot be cast to java.lang.Boolean
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at com.tsgrp.opencontent.wizard.action.executer.ObsoleteDocumentActionExecuter.executeImpl(ObsoleteDocumentActionExecuter.java:94)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.executeImpl(AbstractActionExecuter.java:239)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:226)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:156)
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475)
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:235)
	at sun.reflect.GeneratedMethodAccessor1840.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
```

Based on the error, I'm guessing this has to do with the admin slider switch update.  See #2312 and #2162

**Comment by engerernoah** [comment]
A previous update converted the obsolete document configs from storing in Strings to storing in booleans causing the class cast exception. Solution for this just required removing and re-adding the obsolete document configs in edge2.

**Comment by gsteimer** [comment]
Note - related to #2312.  We need to come up with a way to fix this across all actions
