### ISSUE TITLE
Signature pages do not apply properly after editing the form during approval

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#592]
If configured, it's possible to edit a form during the workflow route.  If you edit a form during the route and then try to append an eSignature page, the page does not appear at all.  Steps to reproduce:

1. On edge1, create a `TS Edit in Workflow` form.  Be sure to choose more than one workflow approver
1. As the first approver, just approve.  The signature page will appear as expected.
1. As the second approver, edit the form and change something.  Finish the form to see your changes.
1. At this point, the signature page will be gone.  This is expected.
1. Approve.  The signature page will **not** be appended.

What should happen is the signature page should be appended with *both* signatures added.

**Comment by gsteimer** [comment]
I just tried this out on Edge1 for workflow documents, and the same thing happens.  So, we need to make sure this works for:

- [ ] Editing a form during approval and then adding an eSig
- [ ] Editing a workflow doc during approval and then adding an eSig

In both cases, we should test:

1. Edit form and doc as approver 1
1. Sign
1. Edit form and doc as approver 2
1. Sign

After the above steps, both signatures should be visible on the sig pages.

**Comment by aviking** [comment]
Fixed locally, waiting on Code Review

**Comment by aviking** [comment]
Fixed with OC commit 11016

**Comment by gsteimer** [comment]
Doc editing during the signature route works great, if the document is a 0.x version.  But, it fails for any 1.x document being routed.  Here's the error:

```
DfException:: THREAD: TP-Processor1; MSG: [DM_API_E_BADID]error:  "Bad ID given: 0000000000000000"; ERRORCODE: 100; NEXT: null
	at com.documentum.fc.common.DfException.newBadIdException(DfException.java:28)
	at com.documentum.fc.client.impl.session.Session.getObjectManager(Session.java:796)
	at com.documentum.fc.client.impl.session.Session.getObject(Session.java:857)
	at com.documentum.fc.client.impl.session.SessionHandle.getObject(SessionHandle.java:586)
	at com.tsgrp.opencontent.dctm.content.DCTMContentImpl.getEnhancedProperties(DCTMContentImpl.java:182)
	at com.tsgrp.opencontent.dctm.content.DCTMContentImpl.enhancedGetObject(DCTMContentImpl.java:1364)
	at com.tsgrp.opencontent.wizard.core.esig.TSGAbstractAppendSignaturePageImpl.createSignaturePage(TSGAbstractAppendSignaturePageImpl.java:499)
	at com.tsgrp.opencontent.wizard.core.esig.TSGAbstractAppendSignaturePageImpl.appendSignaturePages(TSGAbstractAppendSignaturePageImpl.java:402)
	at com.tsgrp.opencontent.wizard.activiti.workflow.listener.CompleteUserTaskListener.notify(CompleteUserTaskListener.java:145)
```

The actual error on line 402 is that `docSigMap.getKey()` is returning `null`.

From talking to @dgrumieaux - it seems like that whole loop should be refactored.  This line looks really suspect:

```Java
docSignatureMap.entrySet().iterator().next();
```

The keys should be the chron IDs, so why can't we just iterate over the keySet?  Something like this:

```Java
for(String docChronId : docSignatureMap.keys())
{
...
}
```

@aviking

**Comment by aviking** [comment]
Fixed with OC commit: 11044
