### ISSUE TITLE
Send Notifictions: Searching for Groups throws an  Exception

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/hpi#606]
Searching for a group in Send Notifications on edge1:

![selection_005](https://cloud.githubusercontent.com/assets/3905463/6602368/46ff34a2-c7e9-11e4-825c-2738eb9e4c5c.png)

throws an OC exception:

![selection_006](https://cloud.githubusercontent.com/assets/3905463/6602364/43234f8a-c7e9-11e4-9a09-a3c3aa9245b7.png)

**Comment by tconnellytsg** [comment]
Fixed with OC Revision #11081 by implementing group searching in dctm searchAuhorities method.

**Comment by gsteimer** [comment]
Searching for groups works, but sending now fails.  The error in OC is:

```
2015-03-16 10:33:51,882	1304828	TP-Processor6	ERROR	RESTService	
java.lang.NullPointerException
	at com.tsgrp.opencontent.universal.action.executer.SendNotificationActionExecuter.executeImpl(SendNotificationActionExecuter.java:116)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:180)
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:303)
```

From debugging the code, it looks like the `groups` on line 112 is null.

**Comment by b-k-white** [comment]
HPI was just sending the wrong attribute off of the group variable. Fixed this. 
CR - JK
HPI 11905
