### ISSUE TITLE
HPI not Compatible with Thumbnail Server

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#607]
While configuring HPI for a potential client, we found that HPI/OC is not compatible with Documentum thumbnail server.  Basically, when a PDF is uploaded via HPI, a number of renditions get created (the rendition column is set to '2', which is the same for a normal PDF rendition).  There are a bunch of jpeg renditions as well as an XML rendition.

Interestingly, the following code fails in `DCTMExtendedContentImpl#getContentFormats`

```Java
String dql = "SELECT r_object_id, full_format, rendition FROM dmr_content WHERE any parent_id='" + objectId + "' ORDER BY rendition ASC";
List<String[]> results = DfcUtil.queryStringsList(session, dql);

ArrayList<EnhancedCompleteObject> objects = new ArrayList<EnhancedCompleteObject>();

Iterator it = results.iterator();
while(it.hasNext())
{
	String[] tempArray =(String[]) it.next();
	EnhancedCompleteObject object = new EnhancedCompleteObject();
	EnhancedObjectContent content = new EnhancedObjectContent();
	//setting contentType to be full_format
	content.setContentType( tempArray[1] );  // <- Fails with NPE
...
}
```

To me, this should mean that one of the returned formats does not have a full_format.  However, they all do (at least that's what the query run in DA is telling us).

To fix this, I think we need to:

-[ ] Figure out why the code is NPE'ing above
-[ ] Update the oc-config-dctm.xml to include mimetypes for the weird jpeg content types

**OR**

- [ ] Assuming the contract in `ExtendedContentImpl` allows for it, figure out a way to filter thumbnail renditions out of the query so they never get into the while loop.

Marking this as Upon Client Request since, for this particular client's application, they don't want thumbnails created for the content.  They're simply going to turn off thumbnail server for the particular object types they're using for the HPI evaluation.

**Comment by gsteimer** [comment]
Update from the client. Here's the stack trace:

```
java.lang.NullPointerException
        at com.tsgrp.opencontent.dctm.extendedcontent.DCTMExtendedContentImpl.getContentFormats(DCTMExtendedContentImpl.java:350)
        at com.tsgrp.opencontent.core.content.RESTContent.getMimetype(RESTContent.java:534)
        at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
        at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:426)
```
