### ISSUE TITLE
Send Notification - user list includes Documentum groups

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#633]
See the screenshot below - groups are included in the list of users for sending notifications.  It looks like the query on the OC side is not properly filtering out `r_is_group` properly (groups are in the `dm_user` table in Documentum)

![image](https://cloud.githubusercontent.com/assets/1377228/6927954/6c5f3d46-d7b6-11e4-8111-a1982ff31e94.png)

**Comment by gsteimer** [comment]
Fixed in OC Rev 11265.

**Comment by mikeblum** [comment]
The AW Users in Group query is broken now. See TS Simple Metadata Rules. Here's the stacktrace from OC:

[2015-04-02 14:51:41,292|ERROR|DCTMUserImpl|searchAuthorities|900] [DM_QUERY_E_SYNTAX]error:  "A Parser Error (syntax error) has occurred in the vicinity of:  SELECT u.r_object_id, u.use
r_login_name, u.user_name, u.user_address FROM dm_user u WHERE r_is_group = FALSE  AND  AND"
DfException:: THREAD: http-bio-9080-exec-5; MSG: [DM_QUERY_E_SYNTAX]error:  "A Parser Error (syntax error) has occurred in the vicinity of:  SELECT u.r_object_id, u.user_login_name, u.us
er_name, u.user_address FROM dm_user u WHERE r_is_group = FALSE  AND  AND"; ERRORCODE: 100; NEXT: null
        at com.documentum.fc.client.impl.docbase.DocbaseExceptionMapper.newException(DocbaseExceptionMapper.java:57)
        at com.documentum.fc.client.impl.connection.docbase.MessageEntry.getException(MessageEntry.java:39)
        at com.documentum.fc.client.impl.connection.docbase.DocbaseMessageManager.getException(DocbaseMessageManager.java:137)
        at com.documentum.fc.client.impl.connection.docbase.netwise.NetwiseDocbaseRpcClient.checkForMessages(NetwiseDocbaseRpcClient.java:310)
        at com.documentum.fc.client.impl.connection.docbase.netwise.NetwiseDocbaseRpcClient.applyForCollection(NetwiseDocbaseRpcClient.java:434)
        at com.documentum.fc.client.impl.connection.docbase.DocbaseConnection$3.evaluate(DocbaseConnection.java:1190)
        at com.documentum.fc.client.impl.connection.docbase.DocbaseConnection.evaluateRpc(DocbaseConnection.java:1056)
        at com.documentum.fc.client.impl.connection.docbase.DocbaseConnection.applyForCollection(DocbaseConnection.java:1178)
        at com.documentum.fc.client.impl.docbase.DocbaseApi.exec(DocbaseApi.java:84)
        at com.documentum.fc.client.impl.session.Session.query(Session.java:3322)
        at com.documentum.fc.client.impl.session.SessionHandle.query(SessionHandle.java:2255)
        at com.documentum.fc.client.DfQuery.runQuery(DfQuery.java:167)
        at com.documentum.fc.client.DfQuery.execute(DfQuery.java:211)
        at com.tsgrp.util.dctm.DfcUtil.queryStringsList(DfcUtil.java:379)
        at com.tsgrp.util.dctm.DfcUtil.queryStringsList(DfcUtil.java:416)
        at com.tsgrp.opencontent.dctm.user.DCTMUserImpl.searchAuthorities(DCTMUserImpl.java:882)
        at com.tsgrp.opencontent.wizard.core.query.UsersInGroupsQuery.getUsersInGroup(UsersInGroupsQuery.java:103)
        at com.tsgrp.opencontent.wizard.core.query.UsersInGroupsQuery.getResults(UsersInGroupsQuery.java:51)
        at com.tsgrp.opencontent.wizard.core.Wizard2Impl.executeAWQueryAction(Wizard2Impl.java:1740)
        at com.tsgrp.opencontent.wizard.core.RESTWizard2.executeWizardQuery(RESTWizard2.java:240)

**Comment by gsteimer** [comment]
Woops, sorry - this is probably due to my update  to DctmUserImpl
yesterday. There must be a way through that appends two 'and's. If you
can't fix it I can when I'm back in the office on Monday.

**Comment by gsteimer** [comment]
Resolved with @mikeblum's updated in OC rev 11298
