### ISSUE TITLE
Upon Deleting a Form Template, WizardLifecycleActionService fails preventing all lifecycle transitions for existing PSIs

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#635]
On edge1, trying to cancel a form created with the `ts_metadata_rules` subtype fails with the following error in the JMS:

```
2015-04-09 10:25:12,954 INFO  [STDOUT] 10:25:12,954 ERROR [http-0.0.0.0-9080-3] com.tsgrp.wizard.dctm.lifecycle.WizardLifecycleActionService - Error in WizardLifecycleActionService#userAction: [DM_API_E_BADID]error:  "Bad ID given: 0000000000000000"
DfException:: THREAD: http-0.0.0.0-9080-3; MSG: [DM_API_E_BADID]error:  "Bad ID given: 0000000000000000"; ERRORCODE: 100; NEXT: null
	at com.documentum.fc.common.DfException.newBadIdException(DfException.java:28)
	at com.documentum.fc.client.impl.session.Session.getObjectManager(Session.java:773)
	at com.documentum.fc.client.impl.session.Session.getObject(Session.java:834)
	at com.documentum.fc.client.impl.session.SessionHandle.getObject(SessionHandle.java:580)
	at com.tsgrp.wizard.dctm.lifecycle.WizardLifecycleActionService.getActivePageSetDoc(WizardLifecycleActionService.java:322)
	at com.tsgrp.wizard.dctm.lifecycle.WizardLifecycleActionService.userAction(WizardLifecycleActionService.java:126)
	at com.documentum.server.impl.method.lifecycle.BPCommon.invokeUserAction(BPCommon.java:193)
```

**Comment by gsteimer** [comment]
This is due to the code in `WizardLifecycleActionService.java`, which needs to look at the active page set.  Right before I tried this, I deleted and renamed the page set, so the queries are failing because the queries in `getActivePageSetDoc` are looking for a page set name, which no longer exists.

I'll rename this issue and mark as Upon Client Request

**Comment by gsteimer** [comment]
This ended up being really easy, so I just went ahead and fixed it.  OC Rev 12035
