### ISSUE TITLE
Controlled Docs on Alfresco - View Entire Version History

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#666]
In the Compliance Solution on Alfresco, when creating a minor version off of an Effective major version, we need to create a new node in the repository and then related to the previous version using a `tsg:supersedes` relationship.  See [here] (https://github.com/tsgrp/hpi/wiki/TSG-Compliance-Solution#alfresco) for more information.

However, one downside to this is that when viewing versions of a controlled doc in Alfresco, you only see the version tree for that particular major version.  For example, if a controlled doc has versions 1.0, 2.0, and 3.0 through 3.5, viewing versions of 3.5 only shows versions back to 3.1.  Viewing versions of 2.0 will only show 2.0.

To fix this, the code that gets the version tree in OC must follow `tsg:supersedes` relationships backwards and forwards in order to view the entire object tree.

Before working on this, be sure to vet the design with @dgrumieaux, @gsteimer, and @benallenallen

**Comment by dgrumieaux** [comment]
Have a fix awaiting on a branch for code review on Monday.

**Comment by gsteimer** [comment]
This is close, but there's a permissions issue when viewing versions of 3.0:

```
13:37:37,792 ERROR [com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl] [ajp-apr-9009-exec-5] Unhandled Exception: 04180025 Access Denied.  You do not have the appropriate permissions to perform this operation.
org.alfresco.repo.security.permissions.AccessDeniedException: 04180025 Access Denied.  You do not have the appropriate permissions to perform this operation.
	at org.alfresco.repo.security.permissions.impl.ExceptionTranslatorMethodInterceptor.invoke(ExceptionTranslatorMethodInterceptor.java:50)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.alfresco.repo.audit.AuditMethodInterceptor.invoke(AuditMethodInterceptor.java:158)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy78.getWorkingCopy(Unknown Source)
	at com.tsgrp.opencontent.alfresco.util.AlfrescoEmbUtil.getWorkingCopy(AlfrescoEmbUtil.java:427)
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.enhancedGetProperties(AlfrescoEmbContentImpl.java:518)
	at sun.reflect.GeneratedMethodAccessor688.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:309)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice$1.execute(EmbeddedAlfrescoAdvice.java:68)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:454)
	at com.tsgrp.opencontent.alfresco.core.EmbeddedAlfrescoAdvice.invoke(EmbeddedAlfrescoAdvice.java:81)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy351.enhancedGetProperties(Unknown Source)
	at com.tsgrp.opencontent.alfresco.extendedcontent.AlfrescoEmbExtendedContentImpl.objectIdToEco(AlfrescoEmbExtendedContentImpl.java:359)
	at com.tsgrp.opencontent.alfresco.extendedcontent.AlfrescoEmbExtendedContentImpl.getAllVersions(AlfrescoEmbExtendedContentImpl.java:339)
```

View versions works fine if you login as admin.

**Comment by benallenallen** [comment]
Interesting... first reaction is to wrap everything in a "RunAsAdmin", but that wouldn't be a good idea as it may defeat the permissions that we are purposefully setting. Whatever we end up doing needs to be sure to take into account the permissions that are actually set on a document...

**Comment by gsteimer** [comment]
I think we're ok - according to @dgrumieaux, we would expect this error, the code just doesn't handle it.  Basically, the code is trying to follow the tree no matter what, but you really can't do that because normal users may not have access to the superseded versions.

**Comment by dgrumieaux** [comment]
I just commit a fix that will catch access errors and simply not show that
document instead of erroring out.

**Comment by dgrumieaux** [comment]
Fixed and merged to trunk. OC commit 11645
