### ISSUE TITLE
Delete Document - Audit Action Config Issues

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#705]
In the Delete Document admin config, there's a section that has this config:

![image](https://cloud.githubusercontent.com/assets/1377228/8239821/e65e9434-15c3-11e5-8f6e-5062b27dd5bd.png)

In the above image, the attribute isn't set, hence both 'off' and 'on' are grayed out.  However, as soon as you select one or the other, the audit is always recorded.  So basically, once you select either value, the audit will be attempted.

I noticed this because when configuring this on edge1 for controlled documents, it fails creating the audit with the error below, even though I had the audit config set to "off".

We should test that the config in the admin works properly, and then make sure it works properly with either value selected.

```
2015-06-18 13:55:46,476	522844	TP-Processor1	ERROR	RESTService	Error creating audit event.
com.tsgrp.opencontent.core.exception.OCRuntimeException: Error creating audit event.
	at com.tsgrp.opencontent.dctm.audit.DCTMAuditImpl.createAuditEvent(DCTMAuditImpl.java:71)
	at com.tsgrp.opencontent.core.action.executer.DeleteDocumentActionExecuter.executeImpl(DeleteDocumentActionExecuter.java:108)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:180)
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:303)
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:426)
	at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:414)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:790)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:560)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:643)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
	at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:311)
	at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:776)
	at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:705)
	at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:898)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.tsgrp.opencontent.core.audit.AuditUtil.mapToString(AuditUtil.java:90)
	at com.tsgrp.opencontent.dctm.audit.DCTMAuditImpl.createAuditEvent(DCTMAuditImpl.java:66)
	... 32 more
```

**Comment by aviking** [comment]
FIxed with HPI Commit: 12512 and OC Commit: 11924.
CR: Dan G.
