### ISSUE TITLE
Cannot complete or save form on Alfresco

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#843]
@mikeblum - Not sure what happened in OC yesterday, but I can no longer save or complete a form on edge2.  I get this oc error:

```
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy388.addRelation(Unknown Source)
	at com.tsgrp.opencontent.wizard.core.Wizard2Impl.savePageSetInstance(Wizard2Impl.java:1013)
	at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.executeImpl(FinishAndSubmitPSIActionExecutor.java:50)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:180)
```

**Comment by gsteimer** [comment]
Odd - I can't reproduce this outside of the one form that doesn't work.  I'll poke around more

**Comment by gsteimer** [comment]
Can't reproduce this anymore on edge.  Not sure what was going on...
