### ISSUE TITLE
Cannot complete auto-delegated task on review route

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#891]
In testing #845 it looks like tasks auto-delegate properly in a review route, but I cannot process the task.  See below:

**Inbox Proxy**
![image](https://cloud.githubusercontent.com/assets/1377228/11009267/54f2b556-849b-11e5-83b0-810e3dedac42.png)

**Review task - successfully auto-delegated and audited**
![image](https://cloud.githubusercontent.com/assets/1377228/11009279/6c7c6b54-849b-11e5-90ee-607864546da3.png)

**View Status - incorrect (still lists cobrien)**
I'm guessing this is the root cause of the error:
![image](https://cloud.githubusercontent.com/assets/1377228/11009302/8cb92e3e-849b-11e5-96e6-dd9b8ad38420.png)

**Complete Task as Delegate User**
Fails with this error:
```
2015-11-06 15:29:11,506	55108841	TP-Processor7	ERROR	RESTService	Exception while invoking TaskListener: Exception while invoking TaskListener: A signature occurred but no signature event was available in ApprovalDetails.
org.activiti.engine.ActivitiException: Exception while invoking TaskListener: Exception while invoking TaskListener: A signature occurred but no signature event was available in ApprovalDetails.
	at org.activiti.engine.impl.persistence.entity.TaskEntity.fireEvent(TaskEntity.java:537)
	at org.activiti.engine.impl.persistence.entity.TaskEntity.complete(TaskEntity.java:146)
...
Caused by: com.tsgrp.opencontent.core.exception.OCRuntimeException: A signature occurred but no signature event was available in ApprovalDetails.
	at com.tsgrp.opencontent.wizard.activiti.workflow.listener.CompleteReviewTaskListener.notify(CompleteReviewTaskListener.java:92)
	at org.activiti.engine.impl.delegate.TaskListenerInvocation.invoke(TaskListenerInvocation.java:34)
```

@aviking - I'm guessing you'll need to fix this for your current client.  Talk to @nwoodbine if you have any questions - she recently fixed an issue with reassign/delegate and updating the assignee list properly.

**Comment by ZachGerth** [comment]
Closed with OC Revision #13139. The issue was two-fold; the signature events were not being appropriately updated with the new user proxy, and the assignees list was not being set/updated properly when an assignee had a proxy.

**Comment by gsteimer** [comment]
I just tested this on edge1 and it's still not working.  

Successful auto-delegation:
![image](https://cloud.githubusercontent.com/assets/1377228/11219957/eff45124-8d22-11e5-9a8d-bbe5de4fd48d.png)

The status is still showing the original user:
![image](https://cloud.githubusercontent.com/assets/1377228/11219935/d93f7cce-8d22-11e5-8906-020a4aa7c7b0.png)

Completing the route fails:
```
2015-11-17 11:57:50,702	42376335	TP-Processor3	ERROR	RESTService	Exception while invoking TaskListener: Exception while invoking TaskListener: A signature occurred but no signature event was available in ApprovalDetails.
org.activiti.engine.ActivitiException: Exception while invoking TaskListener: Exception while invoking TaskListener: A signature occurred but no signature event was available in ApprovalDetails.
	at org.activiti.engine.impl.persistence.entity.TaskEntity.fireEvent(TaskEntity.java:537)
	at org.activiti.engine.impl.persistence.entity.TaskEntity.complete(TaskEntity.java:146)
...
Caused by: com.tsgrp.opencontent.core.exception.OCRuntimeException: A signature occurred but no signature event was available in ApprovalDetails.
	at com.tsgrp.opencontent.wizard.activiti.workflow.listener.CompleteReviewTaskListener.notify(CompleteReviewTaskListener.java:92)
	at org.activiti.engine.impl.delegate.TaskListenerInvocation.invoke(TaskListenerInvocation.java:34)
```

@ZachGerth @aviking

**Comment by gsteimer** [comment]
I'll take this one for now - It looks like something isn't updating properly in Jenkin's SVN checkout, so the old code is being executed on edge...

@ZachGerth @aviking - FYI
