### ISSUE TITLE
Cannot Export Objects with Blank Dates to Excel

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#897]
With the updates to #824, OC fails if you try to export an object that has a blank date.  It works perfectly fine if the objects have dates, like so:

![image](https://cloud.githubusercontent.com/assets/1377228/11247693/ce1c0860-8de2-11e5-8de8-7c535d626903.png)

But fails, if I select the next document (or all docs):

![image](https://cloud.githubusercontent.com/assets/1377228/11247706/db332c9a-8de2-11e5-8d0d-48f444904325.png)

The error is:
```
2015-11-18 10:51:38,149	3530524	TP-Processor6	ERROR	RESTService	Error formatting excel export objects
com.tsgrp.opencontent.core.exception.OCRuntimeException: Error formatting excel export objects
	at com.tsgrp.opencontent.core.excel.WorkbookSection.dateFormatObject(WorkbookSection.java:277)
	at com.tsgrp.opencontent.core.excel.WorkbookSection.dateFormatObjects(WorkbookSection.java:236)
	at com.tsgrp.opencontent.core.excel.WorkbookSection.setDateFormat(WorkbookSection.java:214)
	at com.tsgrp.opencontent.universal.action.executer.ExportSearchResultsActionExecuter.createWbSections(ExportSearchResultsActionExecuter.java:152)
...
Caused by: java.lang.NullPointerException
	at java.text.SimpleDateFormat.parse(Unknown Source)
	at java.text.DateFormat.parse(Unknown Source)
	at com.tsgrp.opencontent.core.excel.WorkbookSection.dateFormatObject(WorkbookSection.java:270)
```

@ladams13 @m-brouillette - I'm assinging Marc because I'll bet that your current client will need this ASAP.

**Comment by m-brouillette** [comment]
We now properly skip formatting if a field is blank or not a date.

Fixed in OC REV - 13253
CR - dgrumieux

**Comment by gsteimer** [comment]
Found a small issue - for some reason on Controlled Documents, if you export a doc without an effective date, all of the dates get the wrong format.  This isn't happening for periodic review date, however.

Export without a blank effective date
![image](https://cloud.githubusercontent.com/assets/1377228/11371346/a9446b86-928d-11e5-9bad-3a04538c5a93.png)


Export with a blank effective date
![image](https://cloud.githubusercontent.com/assets/1377228/11371330/971275b6-928d-11e5-8444-6a37389dc7b2.png)

**Comment by gsteimer** [comment]
Update from @m-brouillette - the issue only occurs when the _first_ document has a blank date.

**Comment by m-brouillette** [comment]
Fix the issue with blank dates.  For some reason we previously were only check the first object for its field types.

OC REV - 13294
