### ISSUE TITLE
Cannot Create Subfolder with HBase backend

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#909]
When trying to create a subfolder in the Controlled Documents trac on edge3, I get the following error:

**HPI**
![image](https://cloud.githubusercontent.com/assets/1377228/11599324/ca2f01de-9a8b-11e5-802e-d7fad6108680.png)

**OC**
```
2015-12-04 13:30:01,473	38452575	ajp-8509-3	ERROR	RESTService	
java.lang.NullPointerException
	at com.tsgrp.opencontent.core.content.RESTContent.getIdByPath(RESTContent.java:2124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
```

I'm guessing the update that went in a few months ago to ensure duplicate folders aren't created isn't working on HBase...

**Comment by zkeller** [comment]
This was actually due to a change I made earlier this week to make the check more efficient. Instead of fetching the children of the folder each time to check, it now checks the path of where the folder would be created to see if it exists. If we get a 404, then we are safe to create it. If it comes back with a value, that means the folder already exists.

@nwoodbine this was the update I spoke to you about briefly

**Comment by dgrumieaux** [comment]
Oh yes and I looked at it too. I think we decided the HBase implementation just needs to throw the right type of exception so that it throws a 404 instead of a 500. OCObjectNotFoundException if memory serves

**Comment by CodyWatson15** [comment]
Closed with Revision 13426
