### ISSUE TITLE
Power Promote fails - cannot find approval details folder

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#986]
Power promote fails on edge2 (I'm assuming edge1 and 3 will have the same behavior:

![image](https://cloud.githubusercontent.com/assets/1377228/12734939/65bfe306-c909-11e5-982b-ab62e8c375d9.png)

The error in OC is:

```
Caused by: com.tsgrp.opencontent.core.exception.OCRuntimeException: Error when creating new approval details object from the repository: com.tsgrp.opencontent.core.exception.OCObjectNotFoundException: Unable to find object with path: ${wizard.approval.details.folder}
	at com.tsgrp.opencontent.alfresco.util.AlfrescoEmbUtil.getNodeRefByPath(AlfrescoEmbUtil.java:705)
	at com.tsgrp.opencontent.alfresco.util.AlfrescoEmbUtil.getIdByPathOrId(AlfrescoEmbUtil.java:646)
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.enhancedCreateObject(AlfrescoEmbContentImpl.java:355)
```

From looking through the code, it looks like something happened to the `wizard.approval.details.folder` property - it's not set in any of our `*-defaults` properties files.  I have to fix this for the TSG prod environment (2.4 tag), but I'll merge it to trunk as well.

@nwoodbine - is the path for the folder in HBase the same as what we have in Documentum and Alfresco?  It should be `/Wizard/docApprovalDetails`.  If it's something else, we'll just override it in `wizard-hbase-defaults`

**Comment by gsteimer** [comment]
Fixed with OC Rev 13680
