### ISSUE TITLE
When streaming content to Stage, exception thrown in OC log

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#988]
When streaming content through PDF.js or Stream Viewer, the error below is spit out to the OC log.  The odd thing is that there are no issues visible to the user.  The content is loaded fine in the stage.

When testing this - remember that once you view it the first time, you'll have to try another doc.  If you view a doc more than once, OC correctly returns a 304 and the content isn't streamed at all.

I don't remember seeing this in the past - what could be going on here?

@dgrumieaux @benallenallen @mikeblum - any ideas?  I don't see this at all on edge1, so I'm marking this as an Alfresco issue.

OC error:

```
10:00:19,518 ERROR [com.tsgrp.opencontent.core.content.RESTContent] [http-apr-8080-exec-4] Failed to stream content
java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:325)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
	at com.tsgrp.openoverlay.itext.ITextOverlayEngine.overlay(ITextOverlayEngine.java:276)
	at com.tsgrp.opencontent.core.content.RESTContent.streamNonChunkedData(RESTContent.java:885)
	at com.tsgrp.opencontent.core.content.RESTContent.getContent(RESTContent.java:722)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

...
10:09:00,494 ERROR [com.tsgrp.opencontent.core.content.RESTContent] [ajp-apr-8009-exec-6] Failed to retrieve content.
java.lang.IllegalStateException: Cannot call sendError() after the response has been committed
	at org.apache.catalina.connector.ResponseFacade.sendError(ResponseFacade.java:450)
	at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:119)
	at com.tsgrp.opencontent.core.content.RESTContent.streamNonChunkedData(RESTContent.java:899)
	at com.tsgrp.opencontent.core.content.RESTContent.getContent(RESTContent.java:722)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
10:09:00,494 ERROR [com.tsgrp.opencontent.rest.RESTService] [ajp-apr-8009-exec-6] Cannot call sendError() after the response has been committed
java.lang.IllegalStateException: Cannot call sendError() after the response has been committed
	at org.apache.catalina.connector.ResponseFacade.sendError(ResponseFacade.java:450)
	at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:119)
	at com.tsgrp.opencontent.core.content.RESTContent.getContent(RESTContent.java:774)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by mikeblum** [comment]
This looks like Jackson is closing the stream - it doesn't look like specifically an Alfresco issue... Could we not be properly closing our content streams as they get sent to the client?

**Comment by gsteimer** [comment]
Fixed by @benallenallen's OpenOverlay commit Rev 217.  OC deployment should update dependencies to OpenOverlay 1.4.2
