### ISSUE TITLE
Start Workflow Fails if user has not previously accessed HPI

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#989]
If you try to start a workflow and one of the approvers has never accessed HPI before, the following error occurs and the workflow cannot start:

```
13:43:00,843 ERROR [com.tsgrp.opencontent.rest.RESTService] [http-apr-8080-exec-5] Could not start workflow.
com.tsgrp.opencontent.core.exception.OCRuntimeException: Could not start workflow.
	at com.tsgrp.opencontent.activiti.workflow.ActivitiWorkflowImpl.startWorkflow(ActivitiWorkflowImpl.java:362)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
Caused by: org.activiti.engine.ActivitiException: Exception while invoking TaskListener: Exception while invoking TaskListener: Exception while invoking TaskListener: Exception while invoking TaskListener: Unable to find object with path: hpi/user/abeecher
	at org.activiti.engine.impl.persistence.entity.TaskEntity.fireEvent(TaskEntity.java:537)
...
Caused by: org.activiti.engine.ActivitiException: Exception while invoking TaskListener: Exception while invoking TaskListener: Unable to find object with path: hpi/user/abeecher
	at org.activiti.engine.impl.persistence.entity.TaskEntity.fireEvent(TaskEntity.java:537)
	at org.activiti.engine.impl.persistence.entity.TaskEntity.setAssignee(TaskEntity.java:438)
	at com.tsgrp.opencontent.wizard.activiti.workflow.listener.CreateUserTaskListener.notify(CreateUserTaskListener.java:96)
...
Caused by: com.tsgrp.opencontent.core.exception.OCObjectNotFoundException: Unable to find object with path: hpi/user/abeecher
	at com.tsgrp.opencontent.alfresco.util.AlfrescoEmbUtil.getNodeRefByPath(AlfrescoEmbUtil.java:705)
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.getObjectByPath(AlfrescoEmbContentImpl.java:1164)
	at sun.reflect.GeneratedMethodAccessor823.invoke(Unknown Source)
```
I'm guessing this is a side-effect of the changes we made to make workflow task proxy work on Alfresco and HBase (see #845).  In any case, we need to make a sensible default assumption about whatever the code is looking for in the `/hpi/user/{user}` folder.

@dgrumieaux - not sure if this is going to be an issue for your current client.

**Comment by dgrumieaux** [comment]
Yes it is good catch.

**Comment by gsteimer** [comment]
Note - this also happens if you try to delegate / reassign to a user that doesn't have a user preferences object.

**Comment by dgrumieaux** [comment]
Shouldn't all references to userprefs be a findOrCreate call?

**Comment by gsteimer** [comment]
@dgrumieaux I think this is coming from the code where it checks to see if the user's inbox is proxied, which is all in OC vs. anything in HPI.  I think we just need to make the generic "does the user have an inbox proxy set" code smart enough to handle the case where the user doesn't have a user preferences object (and not actually try to create the user prefs).

**Comment by dgrumieaux** [comment]
Can we just try catch the proxy check in our Activiti listener, and if the call fails, carry on as if the user does not have a proxy?

**Comment by gsteimer** [comment]
Assuming the `ActivitiWorkflowImpl#getInboxProxyUser` is where the issue is coming from (which I think it is), can't we just handle it there?

**Comment by dgrumieaux** [comment]
Makes sense to me - we might want to log a WARN or something so that if the code starts failing for some other reason that we have an idea that something was going wrong.

**Comment by gsteimer** [comment]
@nwoodbine - can this be closed?

**Comment by nwoodbine** [comment]
Fixed by making inbox proxy call safe for non-existent user preferences object (OC Rev 14037). In the future we will want to "service" out user prefs so we don't have to catch all getObjectByPath errors each time we try to access, and standardize the special cases of user prefs. (see https://github.com/tsgrp/HPI/issues/770)
