### ISSUE TITLE
Cannot create AW form - HotDocs merge issue

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#993]
The HotDocs merge is causing AW forms to fail to create on edge:

![image](https://cloud.githubusercontent.com/assets/1377228/12850221/4b6b260e-cbe9-11e5-9584-66951dad71a9.png)

Error in OC is: 

```
com.tsgrp.opencontent.core.exception.OCRuntimeException: Error generating merged document.
	at com.tsgrp.opencontent.wizardhotdocs.action.executor.WizardHotDocsFinishAndSubmitPSIActionExecutor.doPostSubmitActions(WizardHotDocsFinishAndSubmitPSIActionExecutor.java:155)
	at com.tsgrp.opencontent.wizard.action.executer.FinishAndSubmitPSIActionExecutor.executeImpl(FinishAndSubmitPSIActionExecutor.java:115)
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:183)
...
Caused by: org.json.JSONException: JSONObject["targetFolderId"] not found.
	at org.json.JSONObject.get(JSONObject.java:516)
	at com.tsgrp.opencontent.wizardhotdocs.action.executor.WizardHotDocsFinishAndSubmitPSIActionExecutor.doPostSubmitActions(WizardHotDocsFinishAndSubmitPSIActionExecutor.java:72)
```

@alieblich @mikeblum

**Comment by alieblich** [comment]
Fixed with OC rev 13730
